### ISSUE TITLE
storage: prefixes is not returned during object listing if query.SetAttrSelection is used

### ISSUE THREAD

**Issue by deka108** [googleapis/google-cloud-go#2696] opened 2020-08-06 17:45 UTC
**Client**

Storage on `cloud.google.com/go/storage v0.62.0`

**Code**

I have a test that checks listing behavior when the bucket contains objects with and without prefix. 

The test looks something like this:

```go
func (t *TestSuite) TestGCS_ListObjectPrefixes(c *C)() {
	query := storage.Query{
		Delimiter: "/",
		StartOffset: "...",
	}
	query.SetAttrSelection([]string{...})
	it := s.client.Bucket(s.bktName).Objects(context.Background(), &query)
	it.PageInfo()
	pager := iterator.NewPager(it, 10, "")

	var entries []*storage.ObjectAttrs
	_, err = pager.NextPage(&entries)
	c.Assert(err, IsNil)

	var prefixes []string
	var items []string
	for _, entry := range entries{
		if entry.Prefix != "" {
			prefixes = append(prefixes, entry.Prefix)
		} else {
			items = append(items, entry.Name)
		}
	}
	c.Assert(len(items) > 0, Equals, true)
	c.Assert(len(prefixes) > 0, Equals, true)
}
```

**Expected behavior**

Prefix objects should still exist in the results if they really exist in the bucket. So the test should pass.

**Actual behavior**

The test failed to assert that prefixes exist in the results.

Prefix objects won't show up if we use `SetAttrSelection`. I expect setting attribute selection in the SDK should not interfere with the actual list response https://cloud.google.com/storage/docs/json_api/v1/objects/list#response. 

**Proposed Solution**
The request fields parameter in `ObjectIterator.fetch` https://github.com/googleapis/google-cloud-go/blob/3f2988d48e253a8e290b8c0e821284eead1131a0/storage/bucket.go#L1156 should also contain `prefixes` and not just `nextPageToken` and `items(...)` .

I had verified this with the JSON API, including `prefixes` ie. `nextPageToken,prefixes,items(name,etag,updated,contentType)` in the `fields` query parameter will yield expected results

**Comment by codyoss** [comment] 2020-08-06 17:49
This looks like a dupe of #1763. Closing.

**Closed by codyoss** 2020-08-06 17:49 UTC
Labels: api: storage, triage me
