### ISSUE TITLE
all: add ability to disable HTTP/2

### ISSUE THREAD

**Issue by koallen** [googleapis/google-cloud-go#4540] opened 2021-08-02 09:59 UTC
**Is your feature request related to a problem? Please describe.**
Golang by default (since 1.6) uses HTTP/2 when I talk to the Google Cloud API (storage API specifically in my case), this is causing performance limitation because

- We use Google's Interconnect which limits each TCP connection to a maximum of 3Gbps (https://cloud.google.com/network-connectivity/docs/interconnect/quotas)
- HTTP/2 has multiplexing so each process only opens a single TCP connection

**Describe the solution you'd like**
Based on Golang's documentation, to disable HTTP/2 I'd have to either add `GODEBUG=http2client=0` or set `TLSNextProto` to an empty map. In the context of this package, if I want to change `TLSNextProto` I'd have to construct a `http.Client` and pass to `option.WithHTTPClient`, but this means I lose the ability to customize the client with other options

> When used, the WithHTTPClient option takes precedent over all other supplied options.

Ideally, another option like `option.WithoutHTTP2` should be introduced to set `TLSNextProto` internally. Or, maybe provide an option like `option.WithTransportOptions` which allows customizing any `http.Transport` parameters. (this is what AWS Go SDK v2 has: https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/custom-http/#other-settings)

**Comment by codyoss** [comment] 2021-08-03 14:38
Hey @koallen thanks for the detailed report. I am curious if you could provide a concrete example of why `option.WithHTTPClient` does not work for you?

**Comment by koallen** [comment] 2021-08-03 15:12
Hi @codyoss, that does work, however it is a bit involved, here is a snippet of what I did (`gcp_http` is actually `google.golang.org/api/transport/http`)

```golang

clientOptions := []option.ClientOption{option.WithScopes(raw.DevstorageReadWriteScope), option.WithEndpoint("https://storage.googleapis.com/storage/v1")}

customTransport := http.DefaultTransport.(*http.Transport).Clone()
customTransport.MaxIdleConnsPerHost = 100
customTransport.ForceAttemptHTTP2 = false
customTransport.TLSNextProto = map[string]func(authority string, c *tls.Conn) http.RoundTripper{}

gcpTransport, err := gcp_http.NewTransport(ctx, customTransport, clientOptions...)
if err != nil {
	return fmt.Errorf("failed to create GCP transport: %v", err)
}
customClient := &http.Client{Transport: gcpTransport}

client, err := storage.NewClient(ctx, option.WithHTTPClient(customClient))
```

It does work, I've tested it. However, some of the settings are actually the default in the SDK but because I used `option.WithHTTPClient` I need to explicitly set those. For example

- `MaxIdleConnsPerHost` is set in https://github.com/googleapis/google-api-go-client/blob/master/transport/http/dial.go#L170
- `WithScopes` and `WithEndpoint` is set in https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L119-L123

I think setting `MaxIdleConnsPerHost` by myself is totally OK, this is just a performance knob. But I don't really like setting the scope and endpoint manually because it means if people are not careful (or they are not familiar with the internals of this package) they may end up with a broken client (e.g. I was getting weird auth errors before I set the `clientOptions` to `NewTransport`) after calling `storage.NewClient` because when `option.WithHTTPClient` is provided, `storage.NewClient` doesn't modify the client what so ever even when the client is missing some important options required by the APIs.

Not sure if I explained it clearly, I can clarify further if you have questions.

**Comment by koallen** [comment] 2021-08-03 15:22
Also, one must figure out that the client's transport has to be generated by `NewTransport` because it wraps quite a few layers on top of the bare `http.Transport`, passing in an HTTP client with `http.Transport` also end up with weird errors.

I think overall what I wanna say is that the current design makes any customization at the transport layer difficult, and requires the person to have some in-depth knowledge about the SDK internals.

**Comment by codyoss** [comment] 2021-08-04 15:09
@koallen Thanks again for the detailed feedback. I agree this can be tricky to get right. I think this would also be fixed(made better) if we decided to move forward with #1962. If we do not move forward with that issue I think this is something we could document better, I agree. If you don't realize that `NewTransport` handles the auth bits it could be surprising that you need to pass scopes there for proper access. Would you agree that this would be considered a dupe of the linked issue? If so I would like to close this issue in favor of that one. Please feel free to add more context there if you wish.

**Comment by koallen** [comment] 2021-08-04 15:44
Thanks for pointing me to that issue, didn't see that when I was searching for existing issues. It looks like exactly what I was talking about here, so I think I'm fine closing this in favor of that. I also agree that we should at least document the `WithHTTPClient` option better.

**Comment by codyoss** [comment] 2021-08-04 15:59
Awesome, thanks again for the great feedback!

**Closed by codyoss** 2021-08-04 15:59 UTC
Labels: type: question
