### ISSUE TITLE
spanner: unflake TestBatchDML_WithMultipleDML

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1398] opened 2019-04-18 17:50 UTC
```
--- FAIL: TestBatchDML_WithMultipleDML (0.01s)
    transaction_test.go:317: got 8 requests, want 7 requests:
        got:
        *spanner.CreateSessionRequest: database:"mockdb" session:<> ]
        *spanner.BeginTransactionRequest: session:"mockdb-1555606371930968880" options:<read_write:<> > ]
        *spanner.ExecuteSqlRequest: session:"mockdb-1555606371930968880" transaction:<id:"transaction-1" > sql:"SELECT * FROM whatever" params:<> seqno:1 ]
        *spanner.ExecuteBatchDmlRequest: session:"mockdb-1555606371930968880" transaction:<id:"transaction-1" > statements:<sql:"SELECT * FROM whatever" params:<> > statements:<sql:"SELECT * FROM whatever" params:<> > seqno:2 ]
        *spanner.ExecuteSqlRequest: session:"mockdb-1555606371930968880" transaction:<id:"transaction-1" > sql:"SELECT * FROM whatever" params:<> seqno:3 ]
        *spanner.ExecuteBatchDmlRequest: session:"mockdb-1555606371930968880" transaction:<id:"transaction-1" > statements:<sql:"SELECT * FROM whatever" params:<> > seqno:4 ]
        *spanner.CommitRequest: session:"mockdb-1555606371930968880" transaction_id:"transaction-1" ]
        *spanner.DeleteSessionRequest: name:"mockdb-1555606371930968880" ]
        
        want:
        *spanner.CreateSessionRequest: ]
        *spanner.BeginTransactionRequest: ]
        *spanner.ExecuteSqlRequest: ]
        *spanner.ExecuteBatchDmlRequest: ]
        *spanner.ExecuteSqlRequest: ]
        *spanner.ExecuteBatchDmlRequest: ]
        *spanner.CommitRequest: ]
```

https://sponge.corp.google.com/target?id=62bb3aeb-128a-4c00-8594-ca3eaefc9a75&target=cloud-go-libraries/google-cloud-go/continuous/go111&searchFor=&show=ALL&sortBy=STATUS

**Comment by olavloite** [comment] 2019-04-21 13:13
(Most probably) related to #1382 and caused by the SessionPool maintainer that aggressively deletes sessions on its first iteration that is started directly after the creation of the SessionPool. This should also be solved by https://code-review.googlesource.com/c/gocloud/+/40150.

**Comment by olavloite** [comment] 2019-10-28 08:49
Fixed by https://github.com/googleapis/google-cloud-go/commit/80979225afc76a1e08783859dc578ff0c0cffabd

**Closed by olavloite** 2019-10-28 08:49 UTC
Labels: api: spanner, type: cleanup
