### ISSUE TITLE
metadata: PubSub Trigger for Cloud Function: Metadata is missing from context

### ISSUE THREAD

**Issue by pkpfr** [googleapis/google-cloud-go#2848] opened 2020-09-11 22:49 UTC
**Client**

PubSub Trigger for Cloud Function

**Environment**

Cloud Function Builder

**Go Environment**

$ go 1.13

**Code**

```go

type PubSubMessage struct {
	Data []byte `json:"data"`
}

func PubSubCloudFunction(ctx context.Context, msg PubSubMessage) error {
	meta, err := metadata.FromContext(ctx)
	if err != nil {
		return err
	}
        ...
}
```

**Expected behaviour**

Error should be nil and meta should not be nil 

**Actual behaviour**

Meta is nil and error is `unable to find metadata`

**Additional context**

v0.65.0

**Comment by codyoss** [comment] 2020-09-15 17:00
Hey, do you have any more details on how to reproduce this? This is what I did and it worked fine:

1. Created a go.mod for the function
`go.mod`
```
module example.com/cloudfunctions

go 1.14

require cloud.google.com/go v0.65.0
```

2. Deploy
```
gcloud functions deploy PubSubCloudFunction \
--runtime go113 \
--trigger-topic test
```

3. Publish a message
```
gcloud pubsub topics publish test --message=testing                                                                                     
```

4. Checked logs
```
2020/09/15 16:52:49 Metadata: EventID:1532636192783688 Timestamp:2020-09-15 16:52:48.653 +0000 UTC EventType:google.pubsub.topic.publish
2020/09/15 16:52:49 Message: testing
```

**Comment by vinicius-b** [comment] 2020-09-15 17:29
Hey there @codyoss having this issue when vendorizing dependencies. With go modules it is working fine but need to vendorize to use private dependencies. Any thoughts?

**Comment by pkpfr** [comment] 2020-09-15 20:01
I am vendorizing with private dependencies and using dep.  Go mod is currently not an option for me.

**Comment by codyoss** [comment] 2020-09-15 20:21
This is a dupe of #1947. Please see the following commet:

https://github.com/googleapis/google-cloud-go/issues/1947#issuecomment-692881766

**Closed by codyoss** 2020-09-15 20:21 UTC
Labels: api: functions, needs more info, type: question
