### ISSUE TITLE
spanner: integration_test.go does not always clean up instances

### ISSUE THREAD

**Issue by tbpg** [googleapis/google-cloud-go#1887] opened 2020-03-26 12:06 UTC
**Client**

Spanner

**Environment**

Kokoro

**Code**

https://github.com/googleapis/google-cloud-go/blob/96a82502032cccc921fd09367c337b44ecc7a3f3/spanner/integration_test.go#L174-L207

**Expected behavior**

There is a cleanup function in this test, but it seems it's not always called (e.g. if we cancel the test in the middle). We expect this test to always pass.

**Actual behavior**

Instances don't get cleaned up, we run into a limit, then we can't create another instance.

**Additional context**

Led to #1883, which is why I'm labeling this P1. We should either reuse one instance or improve the logic for cleaning them up.

I cleaned up the instances in the test project manually, but  this will probably happen again in another month or two.

**Comment by hengfengli** [comment] 2020-03-29 22:06
I have run the integration test multiple times. It cleans up the instance for both successful and failed results. However, I found that when the test panic (e.g., a timeout panic), the instance is not deleted. The issue is: 

```golang
func TestMain(m *testing.M) {
	cleanup := initIntegrationTests()
	res := m.Run() // <-- a panic occurs
	cleanup() // <-- this will not run
	os.Exit(res)
}
```

So what we can do is: 

```golang
func TestMain(m *testing.M) {
	cleanup := initIntegrationTests()
        defer cleanup() // add this for a panic, but this will not run when calling os.Exit()
	res := m.Run()
	cleanup() // we also need to keep this for os.Exit()
	os.Exit(res)
}
```

**Comment by skuruppu** [comment] 2020-04-01 03:23
@hengfengli I think #1883 has links to all the failed tests.

**Comment by hengfengli** [comment] 2020-04-01 04:26
@skuruppu Yes, but these links only show the symptoms but not the root causes. I wonder if sometimes, a test run gets a timeout and then the created instance is left over (the root cause). After accumulating a while, we can't create more instances in that region (the symptom).

**Comment by skuruppu** [comment] 2020-04-01 22:07
I haven't checked myself but do the logs show where the tests fail? Or are all of those failures because a node wasn't available to create an instance?

**Comment by hengfengli** [comment] 2020-04-01 22:30
The logs only show failures where we try to create new instances, but failed. 

All of those failures are: 

```bash
2020/03/23 21:34:31 waiting for instance creation to finish failed: rpc error: code = ResourceExhausted desc = Project 36639933145 cannot add 1 nodes in region .
```

The test can't create a new instance.

**Comment by olavloite** [comment] 2020-04-02 11:49
This problem seems to be coming from a different integration test than the 'normal' integration tests for the Spanner client library. The test that seems to trigger the problem is `TestIntegration_StartBackupOperation`, which is defined in `admin/database/apiv1/integration_test.go`, and not the 'normal' `integration_test.go` file in the root of the client lib.

**Comment by olavloite** [comment] 2020-04-02 12:05
My guess is that the root of this problem might be this part of the code:

https://github.com/googleapis/google-cloud-go/blob/f1aafe9b6a344e283d0330c7c0f27cf7a9eaf351/spanner/admin/database/apiv1/integration_test.go#L275-L279

If the deletion of the backup fails for whatever reason, Cloud Spanner will not allow the instance to be deleted. As an extra safety, Cloud Spanner refuses to delete any instance that contains one or more backups. If only the deletion of the backup fails, the integration test will _succeed_, but you will see this in the log:

```
=== RUN   TestIntegration_StartBackupOperation
--- PASS: TestIntegration_StartBackupOperation (166.53s)
    integration_test.go:148: failed to drop instance projects/appdev-soda-spanner-staging/instances/gotest-1585828773340445582-01 (error rpc error: code = FailedPrecondition desc = Cannot delete instance projects/appdev-soda-spanner-staging/instances/gotest-1585828773340445582-01 because it contains backups. Please delete the backups before deleting the instance.), might need a manual removal
PASS
```

**Comment by olavloite** [comment] 2020-04-02 12:26
See https://code-review.googlesource.com/c/gocloud/+/54210

**Comment by hengfengli** [comment] 2020-04-03 00:11
Thanks for finding this. I couldn't reproduce this when I run the entire IT multiple times locally. Then, I thought this is caused by a panic. 

But we don't see any "failed to delete backup" in the log, which means the backend returns a successful deletion of backup. When we call to delete the instance, it still thinks the instance has a backup. Somehow like this: 

```bash
delete_backup() // success

delete_instance() // failed due to a backup with this instance (deletion is still ongoing?)
```

Then, a fix should be: 

```bash
delete_backup() // success

sleep(?) or a method keep listing backups from the instance to
make sure that no backups is with this instance

delete_instance() // this will become successful
```

So I think https://code-review.googlesource.com/c/gocloud/+/54210 doesn't solve the issue yet.

**Comment by hengfengli** [comment] 2020-04-03 00:24
```
=== RUN   TestIntegration_StartBackupOperation
--- PASS: TestIntegration_StartBackupOperation (166.53s)
    integration_test.go:148: failed to drop instance projects/appdev-soda-spanner-staging/instances/gotest-1585828773340445582-01 (error rpc error: code = FailedPrecondition desc = Cannot delete instance projects/appdev-soda-spanner-staging/instances/gotest-1585828773340445582-01 because it contains backups. Please delete the backups before deleting the instance.), might need a manual removal
PASS
```

@olavloite Did you see this in a kokoro build or your local test?

**Comment by olavloite** [comment] 2020-04-03 05:48
> === RUN   TestIntegration_StartBackupOperation
> --- PASS: TestIntegration_StartBackupOperation (166.53s)
>     integration_test.go:148: failed to drop instance projects/appdev-soda-spanner-staging/instances/gotest-1585828773340445582-01 (error rpc error: code = FailedPrecondition desc = Cannot delete instance projects/appdev-soda-spanner-staging/instances/gotest-1585828773340445582-01 because it contains backups. Please delete the backups before deleting the instance.), might need a manual removal
> PASS

I triggered this on my local environment by running the backup test with the `DeleteBackup` line commented out.

I think we need to split this into two separate problems:
1. The problem at hand in this issue is that old instances don't get cleaned up. The most probable reason for that is that there are instances with one or more backups left on the project. The only fix for that is to first delete the backup and then delete the instance. This is something that we should want in any case, as this delete action is a fallback for when something else fails, and the current fallback code is incorrect. Deleting an instance while it still has a backup will always fail.
1. There is one or more test cases that does not (always) clean up their own instances. Those instances are also in such a state that they cannot be deleted by the cleanup code in 1. The most probable test case is therefore the backup test case. We should investigate both the failed and successful test runs of that test case to try to find the reason for that, and we probably also need to add some logging to it to figure out what is going on.

Regarding timeout panics: Are we seeing those in the kokoro logs? Because I would expect a test case that panics because of a timeout to be marked as failed.

**Comment by hengfengli** [comment] 2020-04-06 05:53
@olavloite Thanks for clarifying it. 

1. This issue is fixed by your CL https://code-review.googlesource.com/c/gocloud/+/54210. 
2. I have checked the log of both successful and failed recent tests, but I couldn't find any logs about failing to delete instances or backups. 

The entire test suite of spanner is definitely run less than the current timeout [45 mins](https://github.com/googleapis/google-cloud-go/blob/5b53923ad39ce2797b5f902bc15acbb20d080259/internal/kokoro/continuous.sh#L61). It should not be caused by a timeout panic.

**Closed** 2020-04-07 06:51 UTC
Labels: :rotating_light:, api: spanner, priority: p1, type: bug
