### ISSUE TITLE
storage: unflake TestIntegration_DeleteObjectInBucketWithRetentionPolicy

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1509] opened 2019-07-16 17:30 UTC
```
=== RUN   TestIntegration_DeleteObjectInBucketWithRetentionPolicy
--- FAIL: TestIntegration_DeleteObjectInBucketWithRetentionPolicy (1.17s)
	integration_test.go:2805: integration_test.go:2476: object delete: googleapi: Error 403: Object 'go-integration-test-20190716-59922409620576-0016/some-object' is subject to bucket's retention policy and cannot be deleted, overwritten or archived until 2019-07-17T10:40:44.179854783-07:00, forbidden
```

https://sponge.corp.google.com/invocation?tab=Build+Log&id=6a26c5c1-e865-4d4c-8a71-2ea424369e51&searchFor=

https://source.cloud.google.com/results/invocations/6a26c5c1-e865-4d4c-8a71-2ea424369e51/targets

**Comment by jadekler** [comment] 2019-07-16 17:30
cc @odeke-em

**Comment by odeke-em** [comment] 2019-07-18 05:35
Thank you for the report @jadekler! Let me take a look.

**Comment by odeke-em** [comment] 2019-07-18 06:08
Hmm, am not sure what's going on aside perhaps from the backend tripping:

a) We've got tests to ensure that we properly send all the right attributes to an update
b) I've ran concurrently 3 instances with `go test -run=DeleteObjectInBucketWithRetentionPolicy -v -count=100` and can't reproduce the problem

**Comment by jadekler** [comment] 2019-07-18 14:42
Ah right on. Well... hm. Maybe we close this issue and just see if it comes up again? WDYT @odeke-em ?

**Comment by odeke-em** [comment] 2019-07-19 06:19
Yes, please let's close it. If it persists then we'll go into Sherlock Holmes mode to debug :)

**Closed by odeke-em** 2019-07-19 06:19 UTC
Labels: api: storage, type: cleanup
