### ISSUE TITLE
secretmanager: rpc error while iterating secret version using secretIterator.New() post ListSecrets() after new secretManager version upgrade

### ISSUE THREAD

**Issue by patels30** [googleapis/google-cloud-go#10946] opened 2024-10-03 03:49 UTC
## Client

secretManager Client

## Environment

OS (github runner): 15~22.04.1-Ubuntu SMP

```bash
$ go version
go version go1.23.1 linux/amd64
```

## Code and Dependencies

```go
type SecretVersionDetails struct {
	SecretVersion *secretmanagerpb.SecretVersion
	Type          string
	Status        string
}

func (smc *SecretManagerClient) FetchSecrets(ctx context.Context) ([]config.SecretVersionDetails, error) {

	reqAllSecrets := &secretmanagerpb.ListSecretsRequest{
		Parent: "projects/abc-sample",
		Filter: secretLabelFilter,
	}

	secretIterator := smc.client.ListSecrets(ctx, reqAllSecrets)

	secretVersionDetails := make([]config.SecretVersionDetails, 0)
	for {
		secret, err := secretIterator.Next()
		if err == iterator.Done {
			break
		}

		if err != nil {
			log.Error().Err(err).Msg("error at secretIterator.Next()")
			return nil, err
		}

		// Check only latest versions
		req := &secretmanagerpb.GetSecretVersionRequest{
			Name: secret.Name + "/versions/latest",
		}

		secretVersion, err := smc.client.GetSecretVersion(ctx, req)

		if err != nil {
			log.Error().Err(err).Msg("error at getting latest secret version")
		} else if secretVersion.State == secretmanagerpb.SecretVersion_ENABLED {
			secretVersionDetails = append(secretVersionDetails, config.SecretVersionDetails{
				SecretVersion: secretVersion,
				Type:          secret.Labels["secrettype"],
			})
		} else {
			log.Info().Str("Version State", secretVersion.State.String()).Str("SecretVersion Name", secretVersion.Name).Msg("secretVersion may be Disabled or Destroyed")
		}
	}

	return secretVersionDetails, nil
}

```

<details>
  <summary>go.mod</summary>

```text
module github.com/sample/apps

go 1.23

toolchain go1.23.1

require (
	cloud.google.com/go/secretmanager v1.14.1
	google.golang.org/api v0.196.0
	google.golang.org/grpc v1.66.0
)
```

</details>

## Expected behavior

It always returned the version details.

## Actual behavior

Getting error

`{"level":"error","error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: EOF\"","time":"2024-10-03T13:27:16+10:00","message":"error at secretIterator.Next()"}`

## Additional context

We are seeing this error after upgrading the secretManager to 1.41.0 -> 1.41.1. and below

![image](https://github.com/user-attachments/assets/188f5550-520d-48e3-876f-8677bb99a6d3)

**Comment by codyoss** [comment] 2024-10-03 18:54
Can please share how you authenticate your client today? Do you use any custom auth options or just default? I am unable to reproduce this as is. This sounds like a TLS issue if I had to guess. Can you verify what version of `cloud.google.com/go/auth` you are pulling in when you are getting this error?

**Comment by codyoss** [comment] 2024-10-04 20:16
Of the changes in the release notes for [0.9.2](https://github.com/googleapis/google-cloud-go/blob/main/auth/CHANGES.md#092-2024-08-30) this is the only one that stood out as it may affect something at this layer: https://github.com/googleapis/google-cloud-go/pull/10733

Are you by chance doing anything with the `http.DefaultTransport`?

**Comment by codyoss** [comment] 2024-10-14 14:55
We are investigating this issue. Closing this as dupe of #10844

**Closed by codyoss** 2024-10-14 14:55 UTC
Labels: status: investigating, api: secretmanager
