### ISSUE TITLE
pubsub: high volume/throughput leading to a lot of "context deadline exceeded" even with long timeouts

### ISSUE THREAD

**Issue by dboshardy** [googleapis/google-cloud-go#2831] opened 2020-09-09 21:25 UTC
**Client**

PubSub

**Environment**

Alpine Docker on MBP, also running just on MBP
**Go Environment**

```bash
$ go version
go version go1.15 darwin/amd6

$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/axb171/Library/Caches/go-build"
GOENV="/Users/axb171/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/me/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH=/Users/me
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ml/ngxwgkcj5vv48vd9qq__svdc0000gp/T/go-build764646392=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
**Code**
The confirmation is created as a goroutine using the publish result from client.Publish(). The `Client` here is my own interface for some other business logic. 
```go

// Using these batch settings
c.topic.PublishSettings.Timeout = 2 * time.Minute
c.topic.PublishSettings.BufferedByteLimit = 2 * 2e9
c.topic.PublishSettings.ByteThreshold = 1 * 1024 * 1024 

...


func (c *Client) confirm(result *pubsub.PublishResult, wg *sync.WaitGroup) {
	defer wg.Done()
	ctx, cancelFunc := context.WithTimeout(c.ctx, time.Duration(10)*time.Minute)
	_, err := result.Get(ctx)
	if err != nil {
		cancelFunc()
		log.Errorf("%s : Error confirming message: %s", c.batchId, err)
		return
	}
	atomic.AddUint64(c.confirmedCount, 1)
	return
}

```
**Expected behavior**

Messages publish and confirm successfully.

**Actual behavior**

Messages publish, but confirmation via `result.Get(ctx)` yields `context deadline exceeded` even with a 10 minute context timeout. 

I tried logging the number of coroutines and it never got about 12k using GOMAXPROC=2

**Screenshots**
Clearly it's publishing messages.
<img width="260" alt="Screen Shot 2020-09-09 at 4 22 44 PM" src="https://user-images.githubusercontent.com/2131537/92656493-c4548880-f2b8-11ea-9ba9-3bd863ce5d89.png">

**Comment by hongalex** [comment] 2020-09-09 22:18
Thanks for filing an issue.

A couple followups so I can try to reproduce this issue.
1. Could you describe your rate of publish?
1. What version of the pubsub library are you using?
1. What is the percentage of message publishes that you are getting `context deadline exceeded` from?

**Comment by dboshardy** [comment] 2020-09-10 13:47
Rate of publish is very high.  About 100k/min.

This happened both with a previous version I had pinned 1.3.1, and the newest, 1.6.1 that I had hoped might fix the issue.  

Looking at the counts, around the time I started getting the panic, the counts are:

```published: 317353
confirmed: 41587
```

And they increase at roughly the same rate, but in different proportion. The confirmation consistently is about 10% of published messages.  

So I'm guessing this isn't an error, per se, it's a API-rate issue.  Though, I would be surprised if my first go program maxed out Google's Pubsub API.

**Comment by hongalex** [comment] 2020-09-10 17:10
> So I'm guessing this isn't an error, per se, it's a API-rate issue. Though, I would be surprised if my first go program maxed out Google's Pubsub API.

It seems like it's possible, but without detailed project info (which I don't recommend sharing on Github), it would be difficult to verify.
Publisher throughput can be found [here](https://cloud.google.com/pubsub/quotas#quotas), and it does seem like 100k/minute _might_ be getting close to that depending on what region you publish to.
If you aren't already, you might be able to increase this by publishing to a larger regional endpoint. Specifically, passing in `option.WithEndpoint("us-central1-pubsub.googleapis.com:443")` in your  `pubsub.NewClient` call.

You could also try using different batch settings. Currently, publish batches are small due to the default `DelayThreshold: 10 * time.Millisecond,  CountThreshold: 100`.
In high publish cases, I might recommend increasing `DelayThreshold` to `500 * time.Millisecond` and `CountThreshold` to be closer to 1000. This is based on your 100k/minute rate.
Depending on the size of your messages, you might have to increase `PublishSettings.ByteThreshold` as well.

This will increase the latency of your publishes, but considering you were setting timeout to be 2 minutes anyway, it might be fine.

> That times out far before the 10 minute mark. So it seems it's not respecting the timeout I give it.

That's likely due to your `c.topic.PublishSettings.Timeout = 2 * time.Minute` setting.

**Comment by dboshardy** [comment] 2020-09-10 20:26
How would the publish timeout setting affect the result confirmation which is using a child context?  Shouldn't it honor the timeout in the child, or is the timeout in the parent going to short circuit that timeout?


I'm also a bit confused. I took the nuclear option and set the timeouts both to 10 minutes but get `context deadline exceeded` at about 2-3 minutes and around 50k messages confirmed regardless of other settings I've tweaked.  Is there some max timeout it's overriding my 10 minute timeout with?

**Comment by hongalex** [comment] 2020-09-10 20:51
> How would the publish timeout setting affect the result confirmation which is using a child context? Shouldn't it honor the timeout in the child, or is the timeout in the parent going to short circuit that timeout?

Ah, maybe not. This timeout affects the publish RPC, but assuming that it goes through, it shouldn't have an effect on `Get` call. I conflated it because you mentioned you were seeing a 2 minute timeout.

> If I don't care about timeouts, would you still recommend the settings above? What is the logic you used to derive those settings?

Essentially, the max number of messages that can be bundled in one `Publish` request is 1000 messages or 10 MB. Assuming 100k messages every minute, that's about 1.6k messages per second.
The 500 millisecond timing is a bit arbitrary,  but it will guarantee you can publish 120k messages per second without any issue.

> And, is a timeout in this case from a growing lag from publish to confirmation due to publish going faster than can be confirmed? Is there a way to make confirmation faster? Or do I just have to make publishing slower?

Are your confirmations being handled in individual goroutines? If so, there really shouldn't be a reason why it's taking so long.

Ultimately, I suspect this is a client side issue (either with the library or the machine). Have you seen anything abnormal in terms of CPU/memory usage when you are publishing these messages?

**Comment by hongalex** [comment] 2020-09-10 20:52
Could you also share the size of your messages so I can get a better understanding of your throughput? It'll help me get a better working reproduction assuming changing the publish settings doesn't work for you.

**Comment by dboshardy** [comment] 2020-09-10 21:09
> Ultimately, I suspect this is a client side issue (either with the library or the machine). Have you seen anything abnormal in terms of CPU/memory usage when you are publishing these messages?

I haven't tried profiling CPU/mem yet. I've been using GOMAXPROCS=2 to simulate a k8s pod with a 2vCPU request.  

Message size can unfortunately vary wildly depending on the request. What I'm testing with right now, the messages are fairly uniformly around 2800B. 

> Are your confirmations being handled in individual goroutines? If so, there really shouldn't be a reason why it's taking so long.

Yep, that's how I handle it.

```go
func (c *Client) Publish(message <-chan []byte, wg *sync.WaitGroup) {
	defer wg.Done()
	for msg := range message {
		message := &pubsub.Message{
			Attributes: map[string]string{
				"project":    config.Config().Project,
				"source":     c.source,
				"table":      c.table,
				"batch_id": c.batchId,
			},
			Data: msg,
		}
		result := c.topic.Publish(c.ctx, message)
		wg.Add(1)
		go c.confirm(result, wg)
		atomic.AddUint64(c.publishedCount, 1)
	}
	log.Debugf("%s : Ending message publishing...", c.batchId)
	return
}
```

After discovering what was causing the timeout (the context being used in `Topic.Publish`), upping that timeout prevented the early timeout I was seeing. But the confirmed:published count ratio is still a good 1:3 (using the settings you suggested).  Is that just the beset I'll get?  

I'm looking at the `Topic.Publish` source and I don't see the context that is passed in used anywhere.  I see in the `initBundler` call it used its own `context.TODO` and a child context with a timeout specified in the PublishSettings.  It's likely my own naivete when it comes to Go, but how does the context I pass into `Topic.Publish` end up used at all?  It clearly is as my PublishSettings timeout has been 10 minutes before changing the `Topic.Publish` context to a longer timeout, thus preventing the `context deadline exceeded` I had been seeing after the expected 3 minutes.

**Comment by dboshardy** [comment] 2020-09-10 21:51
I also tried giving `Topic.Publish` the background context which shouldn't have any deadline, and used the 10 minute `PublishSettings` timeout and _that_ timed out after 10 minutes.  Is the timeout for `Topic.Publish` for each individual call to `Topic.Publish`?  If so, this would mean one (or more) publish calls are taking in excess of 10 minutes, which doesn't make sense to me looking at the code.

**Comment by hongalex** [comment] 2020-09-10 22:19
> how does the context I pass into Topic.Publish end up used at all? 

You're right, it's not being used. I suspect another problem is that you're reusing the context from the client `c.ctx` for both the `Publish` and the `Get` call. Rather than doing this, the parent context that's passed in to `confirm()` should be a background context.

```
func (c *Client) confirm(result *pubsub.PublishResult, wg *sync.WaitGroup) {
	defer wg.Done()
	ctx, cancelFunc := context.WithTimeout(context.Background(), time.Duration(10)*time.Minute)
        ....
```

**Comment by dboshardy** [comment] 2020-09-11 15:00
I'll give that a shot thanks.  Is this a Go thing, or something peculiar to this client?  Forgive me, this is my first real Go project.

**Comment by hongalex** [comment] 2020-09-11 16:20
I'm actually not 100% sure this will solve your issue, but if you pass in the background context for now, you will be guaranteed that any derived contexts are not cancelled except by your timeout.

**Comment by dboshardy** [comment] 2020-09-11 20:50
It did fix the timeout.  It's confirming the publish, albeit slowly.  Still lagging by a significant margin behind the publishing.  It's slow to the point of being slower than the python version of the application I'm writing. That to me makes no sense.  I tested this against the pubsub emulator, and it was 2 orders of magnitude faster than the equivalent python app.  



Something interesting.  I think I was bottlenecking this with the max procs.  Upping `GOMAXPROC` to 2, there is basically no lag in confirmation.  Which makes me think something about the way the pubsub client was working was being handicapped in some way.  I tried messing with my concurrency settings and it seems it needs a minimum of 2 to keep up.   I'm curious as to your take on why this would be the case?

**Comment by hongalex** [comment] 2020-09-11 23:42
> Upping GOMAXPROC to 2, there is basically no lag in confirmation

Well by default, `PublishSettings.NumGoroutines` is limited to 25 * `GOMAXPROC`, so doubling it allows more messages to be sent at once which makes sense. In addition, by limiting the number of goroutines (through `GOMAXPROC`), there's probably a queue of messages waiting to be confirmed. To verify this, you should be able to determine how many goroutines are spawned with different `GOMAXPROC`.

> I've been using GOMAXPROCS=1 to simulate a k8s pod with a 1vCPU request

I think with your current publish volume, you may just need to increase your number of CPUs. Happy to discuss this further, but since it doesn't seem to be an issue with the client library, I'll be closing this issue now.

**Closed by hongalex** 2020-09-11 23:42 UTC
Labels: api: pubsub, status: investigating

**Comment by dboshardy** [comment] 2020-09-14 14:48
Thanks for your help, @hongalex!
