### ISSUE TITLE
iam/apiv1: IamPolicyClient.GetIamPolicy results in a 404 error

### ISSUE THREAD

**Issue by Carestab** [googleapis/google-cloud-go#10914] opened 2024-09-25 06:57 UTC
## Client

iam

## Environment

MacBook Pro M1 Sonoma 14.5

**$ go version**

`go version go1.22.7 darwin/arm64`

**$ go env**

```
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/user/Library/Caches/go-build'
GOENV='/Users/user/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/user/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/user/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go@1.22/1.22.7/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/opt/homebrew/Cellar/go@1.22/1.22.7/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.7'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/user/VisualStudio/GO/clean-temp-perm/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/5j/z6v8nzcj59bb_4c09jznj5kh0000gn/T/go-build2782481485=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

## Code and Dependencies

```package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	// "strings"

	asset "cloud.google.com/go/asset/apiv1"
	"cloud.google.com/go/asset/apiv1/assetpb"
	iam "cloud.google.com/go/iam/apiv1"
	"cloud.google.com/go/iam/apiv1/iampb"
	"google.golang.org/api/iterator"
)

func main() {
	scope := flag.String("scope", "organizations/ORG_ID", "Scope of the search.")
	query := flag.String("query", "", "Query statement.")
	flag.Parse()
	ctx := context.Background()
	client, err := asset.NewClient(ctx)

	if err != nil {
		log.Fatalf("asset.NewClient: %v", err)
	}
	defer client.Close()

	req := &assetpb.SearchAllResourcesRequest{
		Scope:      *scope,
		Query:      *query,
		AssetTypes: []string{"cloudresourcemanager.googleapis.com/Project"},
	}
	it := client.SearchAllResources(ctx, req)

	iamClient, err := iam.NewIamPolicyClient(ctx)

	if err != nil {
		log.Fatalf("iam.NewIamPolicyRESTClient: %v", err)
	}

	for {
		resource, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			log.Fatal(err)
		}
		// fmt.Println(resource)
		// Gets the project's policy
		iamReq := &iampb.GetIamPolicyRequest{
			Resource: resource.GetName(),
			// Resource: fmt.Sprintf("//iam.googleapis.com/projects/%s/serviceAccounts/%s-compute@developer.gserviceaccount.com",resource.GetAdditionalAttributes().GetFields()["projectId"].GetStringValue(),strings.Split(resource.GetProject(),"/")[1]),
			Options: &iampb.GetPolicyOptions{
				RequestedPolicyVersion: 3,
			},
		}
		fmt.Println(iamReq.GetResource())
		iamPolicy, err := iamClient.GetIamPolicy(ctx, iamReq)
		if err != nil {
			fmt.Println(err)
		}
		fmt.Println(iamPolicy)
	}

}
```

**go mod**

```
module form/clean-temp-perm

go 1.22.7

require (
	cloud.google.com/go/asset v1.20.2
	cloud.google.com/go/iam v1.2.1
	google.golang.org/api v0.198.0
)

require (
	cloud.google.com/go v0.115.1 // indirect
	cloud.google.com/go/accesscontextmanager v1.9.1 // indirect
	cloud.google.com/go/auth v0.9.4 // indirect
	cloud.google.com/go/auth/oauth2adapt v0.2.4 // indirect
	cloud.google.com/go/compute/metadata v0.5.2 // indirect
	cloud.google.com/go/longrunning v0.6.1 // indirect
	cloud.google.com/go/orgpolicy v1.14.0 // indirect
	cloud.google.com/go/osconfig v1.14.1 // indirect
	github.com/felixge/httpsnoop v1.0.4 // indirect
	github.com/go-logr/logr v1.4.2 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da // indirect
	github.com/golang/protobuf v1.5.4 // indirect
	github.com/google/s2a-go v0.1.8 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/googleapis/enterprise-certificate-proxy v0.3.4 // indirect
	github.com/googleapis/gax-go/v2 v2.13.0 // indirect
	go.opencensus.io v0.24.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.55.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.55.0 // indirect
	go.opentelemetry.io/otel v1.30.0 // indirect
	go.opentelemetry.io/otel/metric v1.30.0 // indirect
	go.opentelemetry.io/otel/trace v1.30.0 // indirect
	golang.org/x/crypto v0.27.0 // indirect
	golang.org/x/net v0.29.0 // indirect
	golang.org/x/oauth2 v0.23.0 // indirect
	golang.org/x/sync v0.8.0 // indirect
	golang.org/x/sys v0.25.0 // indirect
	golang.org/x/text v0.18.0 // indirect
	golang.org/x/time v0.6.0 // indirect
	google.golang.org/genproto v0.0.0-20240903143218-8af14fe29dc1 // indirect
	google.golang.org/genproto/googleapis/api v0.0.0-20240903143218-8af14fe29dc1 // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20240903143218-8af14fe29dc1 // indirect
	google.golang.org/grpc v1.67.0 // indirect
	google.golang.org/protobuf v1.34.2 // indirect
)
```

</details>

## Expected behavior

I am indicating the name of the resource based on the issue https://github.com/googleapis/google-cloud-go/issues/8671#issue-1938085302 so it should return the iam policies applied to the project. 

## Actual behavior

It is returning the following error:

`rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type "text/html; charset=UTF-8"`

I have tried pointing to service accounts but the same error occurs.

## Additional context

It is the same question as the issue https://github.com/googleapis/google-cloud-go/issues/8671#issue-1938085302 but as it is closed, I am not sure if I should open another one or just comment on the previous one.

**Comment by quartzmo** [comment] 2024-09-27 18:29
Duplicate of #8761

**Closed by quartzmo** 2024-09-27 18:29 UTC
Labels: triage me, api: iam
