### ISSUE TITLE
G Suite Admin Directory SDK: unable to authenticate

### ISSUE THREAD

**Issue by derekperkins** [googleapis/google-cloud-go#1892] opened 2020-03-31 03:35 UTC
We're having trouble accessing the G Suite Admin Directory API. It doesn't have a wrapper in this repo, but the metadata package it consumes does live here. I am wondering if this library suffers from the same issue with Workload Identity on GKE as both the Java and .Net SDKs.
googleapis/google-auth-library-java#283
googleapis/google-api-dotnet-client#1409

I made a quick PR via the GitHub UI after tracing down the header setting, but I know you don't accept PRs here. #1891

**Comment by derekperkins** [comment] 2020-03-31 03:38
cc @whizard @mordfustang

**Comment by derekperkins** [comment] 2020-03-31 14:55
At its most basic, this is what we're trying to do. We've tried various combinations of passing in explicit scopes, but nothing seems to change the outcome.

	adminService, err := admin.NewService(c)
	if err != nil {
		return nil, err
	}

	resp, err := adminService.Groups.Insert(&admin.Group{
		Description: description,
		Email:       email,
		Name:        groupName,
	}).Do()

We've also tried various combinations of auth scopes, but it seems that `https://www.googleapis.com/auth/admin.directory.group` should be sufficient for what we need. We also enabled `Domain wide delegation` on the service account, even though it seems like this SA shouldn't need to be impersonating any accounts. It's not very clear to me what the purpose is for that setting.

![image](https://user-images.githubusercontent.com/3588778/78040090-3305e100-732c-11ea-99dd-2703944ffdbe.png)

**Comment by codyoss** [comment] 2020-03-31 14:57
Thanks for the detailed report, I will try to to spin up a cluster and figure out what is going on.

**Comment by derekperkins** [comment] 2020-03-31 15:15
As I mentioned in the other issue, Workload Identity has been great for our other GCP calls, but most of those use this package or the genproto libraries, not the api libraries. From what I can tell, they all route auth the same way. We've been on GCP for 6 years and have a good understanding of IAM, so this has been very surprising.

I also tried deploying with this associated PR vendored, but it didn't seem to make a difference. I only suspected it because I found issues with those other SDKs.

If it is relevant, we're currently running GKE 1.15.8-gke.3 on masters and node pools, not on a release channel. The gke-metadata-server daemonset is running `gke.gcr.io/gke-metadata-server:20200103_0300_RC0`

**Comment by codyoss** [comment] 2020-03-31 17:19
With my first attempt of reproducing this I tried to use the storage client: `google.golang.org/api/storage/v1`.  I did this as I am more familiar /w this api and it _should_ be very similar, if not identical,  to how admin directory authenticates since it too is an apiary. 

Results: I was able successfully authenticate my from GKE /w Workload Identity.
Example code:
```go
	service, err := storage.NewService(context.Background(), option.WithScopes("storage.buckets.get"))
	if err != nil {
		log.Fatalf("unable to create service: %v", err)
	}

	_, err = service.Buckets.Get("my-bucket").Do()
	if err != nil {
		log.Fatalf("unable to make call: %v", err)
	}
	log.Println("Things are working :)")
``` 

I will try /w the api you were using next.

What is the error message you were receiving?

**Comment by derekperkins** [comment] 2020-03-31 17:31
We've been able to authenticate storage, logging, tracing, profiler, and Config Connector via Workload Identity. G Suite just seems to be a totally different beast, particularly because we're getting useless errors back, unlike the other services. For normal IAM, we get errors back stating which service account is being used and what specific permission it is failing on. In fact, we often use this for permission discovery to assign minimal privileges. This is the only error we're getting back:

```
&googleapi.Error{Code:403, Message:"Insufficient Permission: Request had insufficient authentication scopes.", Body:"{\"error\":{\"errors\":[{\"domain\":\"global\",\"reason\":\"insufficientPermissions\",\"message\":\"Insufficient Permission: Request had insufficient authentication scopes.\"}],\"code\":403,\"message\":\"Insufficient Permission: Request had insufficient authentication scopes.\"}}", Header:http.Header(nil), Errors:[]googleapi.ErrorItem{googleapi.ErrorItem{Reason:"insufficientPermissions", Message:"Insufficient Permission: Request had insufficient authentication scopes."}}}
```

When I look at the GKE metadata server logs, I see requests going out and coming back with 200 responses for this specific scope.

`"/computeMetadata/v1/instance/service-accounts/default/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.group HTTP/200 size=526"`

**Comment by codyoss** [comment] 2020-03-31 17:36
cc @broady

**Comment by codyoss** [comment] 2020-03-31 17:44
@derekperkins Does this work for you locally if you provide the GSA your KSA references?

**Comment by MordFustang21** [comment] 2020-03-31 19:07
When providing the credentials json file via env ```GOOGLE_APPLICATION_CREDENTIALS``` we get this error.
```
googleapi: Error 403: Not Authorized to access this resource/api, forbidden
```

**Comment by codyoss** [comment] 2020-03-31 19:29
This would seem to me then to not have anything to due /w Workload Identity. This seems more like an api needs to be activated or a proper scope set.

**Comment by derekperkins** [comment] 2020-03-31 19:40
Agreed, sorry for the false lead on Workload Identity. 

The core issue of authentication not working is still there, though maybe this is best suited back on the other repo. As far as I can tell, we are setting all the correct scopes and have enabled all the correct apis. The error isn't providing details, I can't find any audit logs for G Suite access, and nothing is coming through the IAM / Access Approval audit logs.

**Comment by codyoss** [comment] 2020-03-31 19:44
Closing this issue, and will provide a short summary on the sister issue of progress so far.

**Closed by codyoss** 2020-03-31 19:44 UTC
Labels: api: compute, priority: p2, type: bug
