### ISSUE TITLE
bigquery: Query failure randomly

### ISSUE THREAD

**Issue by dminoror** [googleapis/google-cloud-go#5478] opened 2022-02-08 02:54 UTC
**Client**

Bigquery

**Environment**

Ubuntu 20.04.3
using Visual Studio Code SSH-Remote

**Go Environment**

$ go version
go version go1.17.2 linux/amd64

**Code**

```go
	client, err := gcpbigquery.NewClient(ctx, projectID, opts...)

	queryStr := `A simple table`

	q := client.Query(queryStr)

	q.QueryConfig.DisableQueryCache = true
	job, err := q.Run(ctx)
	it, err := job.Read(ctx)
	
	var res map[string]gcpbigquery.Value
	err = it.Next(&res)
	fmt.Printf("err = %s\n", err)

	bs, _ := json.Marshal(res)
	fmt.Printf("res = %s\n", string(bs))
```

**Expected behavior**

Query succeed, got table data.

**Actual behavior**

Query failure randomly. Got two type error message, depending on different table:
`flate: corrupt input before offset 7`
`invalid character '%' looking for beginning of object key string`

**Additional context**

This issue happened once in two to five times query. Cannot reproduce in local client.  

Replace the code 
```go
	job, err := q.Run(ctx)
	it, err := job.Read(ctx)
```
to
```go
	it, err := q.Read(ctx)
```
the issue would not happen again, but we want use the first one for memory saving.

The error came from `iterator.go:139`, hope this helps.
<img width="866" alt="截圖 2022-02-08 上午10 09 21" src="https://user-images.githubusercontent.com/7036910/152909055-8ab26b13-2455-495e-88c4-b1f73f831876.png">

**Comment by shollyman** [comment] 2022-02-08 18:17
Thanks for the report.  This is interesting.  

The `flate` error is related to gzip compression, and the other error is related to malformed json.  My first suspicion is there's something odd about the transport.  Any chance your network traffic is transiting some kind of intercepting proxy, or something else that might be intercepting bytes and altering them?  Alternately, are you doing anything like providing a custom HTTP transport when instantiating the bigquery client?

The error surfacing from the iterator tells me that this surfaced while calling the backend API method jobs.getQueryResults, which returns a page of query result rows.

**Comment by dminoror** [comment] 2022-02-09 09:53
Hi shollyman

Thanks for your reply

We had check our network environment, shouldn't have the problem you mentioned.

It's not happened when using `q.Read(ctx)`. So we think there are something weird in job using.

Also, we had reproduce this issue in other environment (macOS). But the chances are much lower.

**Comment by shollyman** [comment] 2022-02-09 20:46
The significant difference between `q.Read()` and `q.Run()` is primarily in the starting method (jobs.query vs jobs.insert).  Both paths end can end up calling into jobs.getQueryResults when iterating multiple pages of rows, but if you're getting this on the first row/page it may be something orthogonal to the row data itself.  Could you confirm if this manifests immediate or after iterating multiple rows?

The `compress/flate` dependency is quite deep down (e.g. in `net/http`); the bigquery library doesn't use it directly.

Your initial response indicated you're possibly providing variadic opts to `NewClient()`, but it's not clear what they might be.  Mind sharing?

**Comment by dminoror** [comment] 2022-02-14 09:40
We think the error result probably is return after the request finished. The job ID is succeed.  

NewClient() providing variadic opts is `nil`, sorry for the misunderstanding.

After more experiment, we summarized as follows:

The table data:
![截圖 2022-02-14 下午5 28 09](https://user-images.githubusercontent.com/7036910/153836799-4aa965af-4753-4242-bbae-647fdb846eee.png)
csv:
```
c_event_name,c_created_at,c_cdp_user_id,c_app_user_id,c_client_id,session_id
purchase,2022-01-28T08:16:01.139Z,a_user1,55555,user1,
purchase,2022-01-28T08:16:01.139Z,a_user1,55555,user1,
page_view,2022-01-28T08:16:01.139Z,a_user2,111111,user2,
page_view,2022-01-28T08:16:01.139Z,a_user2,111111,user2,
事件,2021-09-22T07:00:00Z,測試,APPu1,user1,
事件,2021-09-22T07:00:00Z,測試,APPu1,user1,
```

`SELECT * FROM table` wouldn't occurred error.
`SELECT c_event_name FROM table` error rate is 80%.
`SELECT c_app_user_id  FROM table` wouldn't occurred error.

Selecting specific field, and the result content is chinese english mixed have higher error rate.

**Comment by shollyman** [comment] 2022-02-15 21:14
Thanks for the additional details, I'll see if I can make progress reproducing and narrowing this down on my end.

**Comment by shollyman** [comment] 2022-02-24 17:56
I'm still having issues reproducing this, but we did catch an instance of a flate error in our continuous testing: https://github.com/googleapis/google-cloud-go/issues/5697

Will continue to see if I can figure out how to increase the odds of inducing the error.

**Comment by shollyman** [comment] 2022-03-02 03:42
Good news!  Was finally able to get this to repro, investigating it in concert with backend folks now.

**Comment by dminoror** [comment] 2022-03-02 04:56
Glad to hear that! Thank very much.

**Comment by shollyman** [comment] 2022-03-02 17:45
Current state:  I have a consistent repro currently.  It's rather simple, and is triggering consistently for me:
```
sql := `
	SELECT vals FROM UNNEST([
		"123",
		"456",
		"678"
		]) as vals ORDER BY RAND()`
	q := client.Query(sql)
	q.DisableQueryCache = true

	for i := 0; i < numRuns; i++ {

		job, err := q.Run(ctx)
		if err != nil {
			t.Errorf("Run %d failed: %v", i, err)
		}
		it, err := job.Read(ctx)
		if err != nil {
			t.Errorf("Read %d failed (%q): %v", i, job.ID(), err)
		}

		// read a row, to ensure we're populating the iterator page.
		var row []bigquery.Value
		err = it.Next(&row)
		if err != nil {
			t.Fatalf("Next %d failed (%q): %v", i, job.ID(), err)
		}
		t.Logf("#%d (%q) row: %v", i, job.ID(), row)
	}
}
```

With the repro, I was able to start digging into the details.  Go behaviors worth noting:

* Go will by default try to upgrade http requests to http2
* Go will attempt compression by default

You can control the compression behavior via `DisableCompression` on [`http.Transport`](https://pkg.go.dev/net/http#Transport).

You can disable http2 upgrades via use of the GODEBUG variable (documented in net/http):
`GODEBUG=http2client=0  # disable HTTP/2 client support`

By controlling these behaviors explicitly, a better picture of the failure emerges:

|           | **DisableCompression=false** | **DisableCompression=true**               |   |   |
|-----------|------------------------------|-------------------------------------------|---|---|
| **http1** | flate error                  | EOF                                       |   |   |
| **http2** | flate error                  | http2 stream close error (INTERNAL_ERROR) |   |   |

This appears to demonstrate there's a failure in a backend component is causing an improper closure of the connection.  Because of Go's expectations around compression, it's attempting to decode an invalid payload yielding the `flate` errors, because it doesn't have a valid byte stream of compressed bytes.  With the compression disabled, we see the failure manifest as an http2 protocol error (server sends RST_STREAM with an INTERNAL_ERROR code), or a straight up EOF served in the http1 case.

To verify that this failure is not go specific, I ended up using curl as well; the same failures emerge.
e.g. `curl -v --http1.1 -H "Authorization: Bearer <token>" https://bigquery.googleapis.com/bigquery/v2/projects/...`

Right now the investigation continues to understand where/how this response is failing in the backend flow.

**Comment by shollyman** [comment] 2022-03-02 17:58
Internal issue: 221843771

**Comment by shollyman** [comment] 2022-03-14 04:08
Following up on this.  A fix to the problematic backend component has been released, and has now propagated fully. 

An abridged version of what was going on: An intermediate software component involved in routing data between callers and various backend components could, under certain edge cases, cause the response sent back to callers to become malformed.  In Go, this would present as a `flate` error, as the malformed response wasn't properly gzip encoded.  Other languages/tools may have reported other variations of gzip issue, or premature closing of the http response.

I'm closing the issue at this time, but please reach out if you're finding this issue still presenting.

**Comment by dminoror** [comment] 2022-03-14 06:27
Hi shollyman,  
We had test newest bigquery library  
```
cloud.google.com/go v0.100.2  
cloud.google.com/go/bigquery v1.29.0
```
But the issue still happening.  
We also try `GODEBUG=http2client=0`, not helpful.

**Comment by shollyman** [comment] 2022-03-14 15:27
Sounds like another failure mode is still present if you're still observing this. The issue is related to the backend, so the library version should not be of concern.

Is the frequency rate the same, or has the overall rate of failure dropped over the last week?  Any further details you can share to help reproduce the issue?

**Comment by dminoror** [comment] 2022-03-17 05:57
After more testing, We hadn't occured the issue again.
I think the issue can be close, very thank for your help.

**Comment by shollyman** [comment] 2022-03-29 03:21
Re-closing this.

**Closed by shollyman** 2022-03-29 03:21 UTC
Labels: type: question, api: bigquery, priority: p2
