### ISSUE TITLE
errorreporting: use batch requests inside bundler handler

### ISSUE THREAD

**Issue by escholtz** [googleapis/google-cloud-go#1620] opened 2019-10-16 14:16 UTC
The errorreporting bundler makes individual calls to the API. It seems like this defeats the purpose of using the bundler package.

It might be more appropriate to use a request that includes multiple events (if one exists) OR a queue with request workers instead of a bundler. 

```go
bundler := bundler.NewBundler((*pb.ReportErrorEventRequest)(nil), func(bundle interface{}) {
        reqs := bundle.([]*pb.ReportErrorEventRequest)
        for _, req := range reqs {
                _, err = client.apiClient.ReportErrorEvent(ctx, req)
                if err != nil {
                        client.onError(err)
                }
        }
})
```

**Comment by codyoss** [comment] 2020-12-08 15:36
The use of the bundler in the package is a little different but it is still valid. Here it is used to make `Client.Report` a non-blocking method.(As opposed to `Client.ReportSync`) So the aim here in here seems to be more non-blocking and less so throughput. Closing as by design.

**Closed by codyoss** 2020-12-08 15:36 UTC
Labels: api: clouderrorreporting, type: cleanup
