### ISSUE TITLE
storage: context cancellations lead to hanging client after a few mins

### ISSUE THREAD

**Issue by annanay25** [googleapis/google-cloud-go#3018] opened 2020-10-14 12:45 UTC
**Client**

Storage (Read client)

**Environment**

k8s running on GCP (alpine image).

**Go Environment**

$ go version
1.15
$ go env
GO111MODULE=on CGO_ENABLED=0 

**Expected behavior**

Client processes requests and handles context cancellations.

**Actual behavior**

After about 10 min or so, the storage client hangs and is unable to process requests. 

**Screenshots**

![Screenshot 2020-10-14 at 5 20 52 PM](https://user-images.githubusercontent.com/10982987/95985487-47ca4200-0e42-11eb-8c1c-16de869376d2.png)

**Additional context**

This started happening **after we implemented context cancellations**. We fire multiple Read requests using the same bucket handler and cancel the passed context after one successful return. However, after roughly 10 min every time (as shown in the attached screenshot), the latency to gcs spikes significantly possibly because of some resource exhaustion in the gcs client.

I turned on the `GODEBUG=http2debug=1` flag and could see the following in the log lines:

```
http2: Transport received RST_STREAM stream=51985 len=4 ErrCode=INTERNAL_ERROR
.
.
http2: Transport failed to get client conn for storage.googleapis.com:443: http2: no cached connection was available
.
Transport received SETTINGS len=18, settings: MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=16384
.
.
http2: Transport received RST_STREAM stream=51985 len=4 ErrCode=INTERNAL_ERROR

```
(^ this has been filtered for noise)

There are several threads out there reporting a similar issue and so I patched our vendor with the latest `net` package (following this thread https://github.com/golang/go/issues/40423) but the problem persists. Probably the only thing that changed was the read client started hanging after 15 min as opposed to 10 min previously. There are also no metrics exposed from the storage client which makes this difficult to debug.

**Comment by tritone** [comment] 2020-10-19 02:29
Thanks for your report. I've seen at least one similar-sounding issue in the past that didn't have a conclusive resolution (#1624) but not in a while. If you have the time to make a minimal example that reproduces the hang, that would be super helpful for us to try and debug what's going on here.

Also, any specifics that you would find helpful as far as metrics?

**Comment by tritone** [comment] 2022-01-07 23:44
I'm going to close this since we haven't gotten any further follow up. Feel free to open new issues if you have further reports or if you want to file a feature request regarding metrics.

**Closed by tritone** 2022-01-07 23:44 UTC
Labels: api: storage, status: investigating, needs more info
