### ISSUE TITLE
profiler: cpu slowly (linearly) going up

### ISSUE THREAD

**Issue by felix-tiket** [googleapis/google-cloud-go#4726] opened 2021-09-04 08:42 UTC
**Client**

Profiler

**Environment**

Observed @ Alpine Docker on GKE

**Go Environment**

go version 1.15

**Code**

```
	profilerCfg := profiler.Config{
		Service:        cfg.ServiceName,
		ServiceVersion: cfg.ServiceVersion,
		DebugLogging:   cfg.EnableDebug,
		ProjectID:      cfg.ProjectID,
		Zone:           cfg.Zone,
		Instance:       cfg.Instance,
		MutexProfiling: cfg.EnableMutexProfiling,
		AllocForceGC:   cfg.EnableForceGC,
	}

	if err := profiler.Start(profilerCfg); err != nil {
		logrus.WithField("err", err).Fatal("failed to start profiler")
	}
```

We turn on the Mutex Profiling and but turn off the AllocForceGC when this happens

**Expected behavior**

Stable CPU

**Actual behavior**

CPU slowly (linearly) going up without many hit to the servers (the only hit is health-check per second)

**Screenshots**

![image](https://user-images.githubusercontent.com/67895152/132088581-7e796378-1e1a-4966-9661-5cda9bd4f207.png)

at 3rd Sept, I turned off the Cloud Profiler, and notice that the CPU is stable.. Every time, I *restarted* the pod, the CPU went down, but the next some days it slowly going up and it's "persistent"

**Additional context**

We're using the latest library

**Comment by felix-tiket** [comment] 2021-09-30 11:01
Is there any updates regarding this?

**Comment by amchiclet** [comment] 2021-10-01 17:40
Unfortunately, no updates, but I'll be a bit more freed up in 2 weeks and will make sure to prioritize this.

By the way, you mentioned there is a health check per second. Is there anything else? What is the server workload like, e.g. memory allocations/deallocations? So maybe I can try to reproduce and make it happen more quickly.

**Comment by felix-tiket** [comment] 2021-10-02 01:10
Alloc Profiling is turned on, and the server workload is none except for the profiler running and the health check per second.. it does not receive any traffic at all yet when I posted this issue..

**Comment by amchiclet** [comment] 2021-10-19 00:59
I've been unsuccessful reproducing this so far. I set up things differently though:
* I used this [workload](https://cloud.google.com/profiler/docs/quickstart-go-app#running_the_sample_application), but changed the config to match yours.
* I ran this on a Debian 11 VM in Google Cloud on Compute Engine.

I let it run over the weekend, and the CPU utilization was stable ~70% all the time.

I could try reproducing this on Alpine in GKE, but I'm more suspicious that my benchmark doesn't have the same behavior as your application. I have some other workloads in mind that I'll likely try out before trying to match environment.

Just wanted to keep you posted. If you have any additional info, feel free to comment.

**Comment by amchiclet** [comment] 2021-10-20 19:29
I think I'm able to reproduce this, but with a rather contrived benchmark. For this specific benchmark, the problem is likely related to alloc profiling. I'll try running this benchmark again with alloc profiling disabled.

For the health checking, does the server receive a health check request or does it send health check to other services? Are you using a specific GitHub health check library?

**Comment by amchiclet** [comment] 2021-12-02 18:28
Closing this as non-reproducible now.

**Closed by amchiclet** 2021-12-02 18:28 UTC
Labels: type: question, api: cloudprofiler
