### ISSUE TITLE
Consider making PubSub `Message.ackID` public

### ISSUE THREAD

**Issue by lc-chrisbarton** [googleapis/google-cloud-go#1596] opened 2019-09-25 22:10 UTC
## PubSub

We would like to log the `Message.ackID` so we can use it with the gcloud command-line tools to directly ack/nack messages that appear in our error logs

**Comment by jadekler** [comment] 2019-09-26 03:39
Out of curiousity, what's the advantage of gcloud acking/nacking instead of the client library doing so? o.O

**Comment by lc-chrisbarton** [comment] 2019-09-26 03:44
Well occasionally it takes some investigation to understand why a message cannot be processed and if it should be removed. This happens to us every few months with data sent by external parties. It happened today and it is very convenient to be able to use tools to do some surgery on the subscription.

**Comment by jadekler** [comment] 2019-09-26 03:45
Makes sense - thanks for satisfying my curiousity!

**Comment by lc-chrisbarton** [comment] 2019-09-26 03:46
See https://github.com/googleapis/google-cloud-go/issues/454

**Comment by hongalex** [comment] 2019-09-27 21:56
@jadekler Personally, I'm in favor of this change. It increases our API surface a bit, but ultimately could be useful for reason as @lc-chrisbarton has mentioned.

AFAICT, this can be simply fixed by a one-line change on `message.go`. Is there anything else I might be missing (or that we need to test) to make this change safe?

**Comment by jadekler** [comment] 2019-09-30 15:25
Seems reasonable to me. Do other languages do so? If we make it public here I suspect it should be public everywhere.

cc @kamalaboulhosn

**Comment by kamalaboulhosn** [comment] 2019-09-30 17:30
@hongalex @jadekler We should not make ackID public in the client libraries. There are implications if someone acks out-of-band. The message will still count against flow control until the modack period has expired. If this is done with enough messages, the subscriber may stop getting message entirely. Given the prescriptive nature of the client libraries, I don't want to expose more than needs to be.

With regard to the original issue, it sounds like the problem is a "poison pill" message that doesn't adhere to the expected message type or something of that nature. We are investigating adding some features to Pub/Sub as a whole that are designed specifically to deal with this case.

**Closed** 2019-10-09 20:29 UTC
Labels: api: pubsub, type: feature request
