### ISSUE TITLE
storage: ambiguous import

### ISSUE THREAD

**Issue by yawnak** [googleapis/google-cloud-go#11286] opened 2024-12-13 15:50 UTC
## Client

Storage

## Environment

lsb_release -a                                                                                  

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

go version go1.23.4 linux/amd64

## Code and Dependencies

<details>
  <summary>go.mod</summary>

```text
module github.com/my-org/payout-service

go 1.23.2

require (
	cloud.google.com/go v0.116.0
	cloud.google.com/go/spanner v1.73.0
	github.com/my-org/cache v1.0.14
	github.com/my-org/config v1.0.46
	github.com/my-org/currency-code v1.0.5
	github.com/my-org/db-company-model v1.0.193
	github.com/my-org/db-payout-model v1.0.22
	github.com/my-org/encryptor v1.0.2
	github.com/my-org/entities v1.0.11
	github.com/my-org/env v1.0.12
	github.com/my-org/errors v1.0.2
	github.com/my-org/flow v1.0.1
	github.com/my-org/iam-client v1.0.22
	github.com/my-org/log v1.0.3
	github.com/my-org/note-client v1.0.21
	github.com/my-org/payout-client v1.0.43
	github.com/my-org/pubsub v1.0.16
	github.com/my-org/server v1.0.18
	github.com/my-org/storage v1.0.14
	github.com/my-org/style v1.0.5
	github.com/my-org/timezone v1.0.2
	github.com/my-org/utils v1.0.77
	github.com/google/uuid v1.6.0
	google.golang.org/grpc v1.69.0
)

require (
	cel.dev/expr v0.19.1 // indirect
	cloud.google.com/go/auth v0.12.0 // indirect
	cloud.google.com/go/auth/oauth2adapt v0.2.6 // indirect
	cloud.google.com/go/compute/metadata v0.5.2 // indirect
	cloud.google.com/go/iam v1.3.0 // indirect
	cloud.google.com/go/monitoring v1.22.0 // indirect
	cloud.google.com/go/pubsub v1.45.3 // indirect
	cloud.google.com/go/secretmanager v1.14.2 // indirect
	cloud.google.com/go/storage v1.48.0 // indirect
	github.com/GoogleCloudPlatform/grpc-gcp-go/grpcgcp v1.5.2 // indirect
	github.com/GoogleCloudPlatform/opentelemetry-operations-go/detectors/gcp v1.25.0 // indirect
	github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/metric v0.49.0 // indirect
	github.com/GoogleCloudPlatform/opentelemetry-operations-go/internal/resourcemapping v0.49.0 // indirect
	github.com/my-org/billing v1.0.0 // indirect
	github.com/my-org/direction v1.0.17 // indirect
	github.com/my-org/notification-service v1.0.1 // indirect
	github.com/allegro/bigcache/v3 v3.1.0 // indirect
	github.com/census-instrumentation/opencensus-proto v0.4.1 // indirect
	github.com/cespare/xxhash/v2 v2.3.0 // indirect
	github.com/cncf/xds/go v0.0.0-20240905190251-b4127c9b8d78 // indirect
	github.com/disintegration/imaging v1.6.2 // indirect
	github.com/envoyproxy/go-control-plane v0.13.1 // indirect
	github.com/envoyproxy/protoc-gen-validate v1.1.0 // indirect
	github.com/felixge/httpsnoop v1.0.4 // indirect
	github.com/getsentry/sentry-go v0.30.0 // indirect
	github.com/go-logr/logr v1.4.2 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	github.com/golang/groupcache v0.0.0-20241129210726-2c02b8208cf8 // indirect
	github.com/google/s2a-go v0.1.8 // indirect
	github.com/googleapis/enterprise-certificate-proxy v0.3.4 // indirect
	github.com/googleapis/gax-go/v2 v2.14.0 // indirect
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	github.com/mitchellh/mapstructure v1.5.0 // indirect
	github.com/nyaruka/phonenumbers v1.4.3 // indirect
	github.com/paulmach/orb v0.11.1 // indirect
	github.com/planetscale/vtprotobuf v0.6.1-0.20241121165744-79df5c4772f2 // indirect
	github.com/ringsaturn/tzf v0.16.0 // indirect
	github.com/ringsaturn/tzf-rel v0.0.2024-b // indirect
	github.com/ringsaturn/tzf-rel-lite v0.0.2024-b // indirect
	github.com/rs/zerolog v1.33.0 // indirect
	github.com/samber/lo v1.47.0 // indirect
	github.com/schollz/closestmatch v2.1.0+incompatible // indirect
	github.com/stripe/stripe-go/v76 v76.25.0 // indirect
	github.com/tidwall/geoindex v1.7.0 // indirect
	github.com/tidwall/geojson v1.4.5 // indirect
	github.com/tidwall/rtree v1.10.0 // indirect
	github.com/twpayne/go-polyline v1.1.1 // indirect
	github.com/valkey-io/valkey-go v1.0.51 // indirect
	github.com/vmihailenco/msgpack/v5 v5.4.1 // indirect
	github.com/vmihailenco/tagparser/v2 v2.0.0 // indirect
	go.mongodb.org/mongo-driver v1.17.1 // indirect
	go.opencensus.io v0.24.0 // indirect
	go.opentelemetry.io/contrib/detectors/gcp v1.32.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.57.0 // indirect
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.57.0 // indirect
	go.opentelemetry.io/otel v1.32.0 // indirect
	go.opentelemetry.io/otel/metric v1.32.0 // indirect
	go.opentelemetry.io/otel/sdk v1.32.0 // indirect
	go.opentelemetry.io/otel/sdk/metric v1.32.0 // indirect
	go.opentelemetry.io/otel/trace v1.32.0 // indirect
	golang.org/x/crypto v0.30.0 // indirect
	golang.org/x/exp v0.0.0-20241204233417-43b7b7cde48d // indirect
	golang.org/x/image v0.23.0 // indirect
	golang.org/x/net v0.32.0 // indirect
	golang.org/x/oauth2 v0.24.0 // indirect
	golang.org/x/sync v0.10.0 // indirect
	golang.org/x/sys v0.28.0 // indirect
	golang.org/x/text v0.21.0 // indirect
	golang.org/x/time v0.8.0 // indirect
	google.golang.org/api v0.210.0 // indirect
	google.golang.org/genproto v0.0.0-20241206012308-a4fef0638583 // indirect
	google.golang.org/genproto/googleapis/api v0.0.0-20241206012308-a4fef0638583 // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20241206012308-a4fef0638583 // indirect
	google.golang.org/grpc/stats/opentelemetry v0.0.0-20241028142157-ada6787961b3 // indirect
	google.golang.org/protobuf v1.35.2 // indirect
)

```

</details>

## Expected behavior

go mod tidy works

## Actual behavior

go mod tidy                                                                                     17:49:23
go: github.com/my-org/payout-service/pkg imports
        github.com/my-org/storage imports
        cloud.google.com/go/storage imports
        google.golang.org/grpc/stats/opentelemetry: ambiguous import: found package google.golang.org/grpc/stats/opentelemetry in multiple modules:
        google.golang.org/grpc v1.69.0 (/home/yawnak/go/pkg/mod/google.golang.org/grpc@v1.69.0/stats/opentelemetry)
        google.golang.org/grpc/stats/opentelemetry v0.0.0-20241028142157-ada6787961b3 (/home/yawnak/go/pkg/mod/google.golang.org/grpc/stats/opentelemetry@v0.0.0-20241028142157-ada6787961b3)

## Additional context

Started after upgrading to v1.48.0

**Comment by tritone** [comment] 2024-12-13 17:49
This is a duplicate of #11283, follow there for the fix.

**Closed by tritone** 2024-12-13 17:49 UTC
Labels: type: bug, api: storage, priority: p1

**Comment by 5t4lk** [comment] 2024-12-13 23:56
:/
