### ISSUE TITLE
storage: storage client hangs on corrupted gzip data

### ISSUE THREAD

**Issue by liron-l** [googleapis/google-cloud-go#8588] opened 2023-09-18 10:22 UTC
**Client**

Storage

**Environment**

Any

**Go Environment**

$ go version
$ go env
go version go1.20.5 linux/amd64

**Code**

e.g.
```go
m, err := r.body.Read(p[n:])
		n += m
		r.seen += int64(m)
		if err == nil || err == io.EOF {
			return n, err
		}
		// Read failed (likely due to connection issues), but we will try to reopen
		// the pipe and continue. Send a ranged read request that takes into account
		// the number of bytes we've already seen.
		res, err := r.reopen(r.seen)
		if err != nil {
			// reopen already retries
			return n, err
		}
```
This will indefinitely hang when the gzip data is corrupted
```
gzip -d somefile
head -c 30 somefile.gz > somefile.corrupted.gz
upload file to storage account
set content-encoding gzip
```

**Expected behavior**

Stop processing the request

**Actual behavior**

Code continuously run HTTP requests

**Screenshots**

![image](https://github.com/googleapis/google-cloud-go/assets/10955685/22092925-2784-4470-ae3b-1c4966186c92)

**Additional context**
error is `io.ErrUnexpectedEOF`, should add dedicated handling

**Comment by tritone** [comment] 2023-09-18 19:06
This is a bit of a tricky case. The error `io.ErrUnexpectedEOF` is a pretty typical error to occur when the network connection is interrupted mid-download, so it's impossible for the client to disambiguate what the cause is. We have the error marked as [retryable](https://github.com/googleapis/google-cloud-go/blob/storage/v1.33.0/storage/invoke.go#L110) for other non-streaming RPCs. Downloading corrupted gzip data is not really a typical use case for the client; we also get into questions of decompressive transcoding on the server side.

Could you try the following two things (which will change how the download works under the hood) with your object and let me know if you get the same error in all cases, or something different?

1. Try setting ReadCompressed: `client.Bucket("bucket").Object("object").ReadCompressed(true).NewReader(...)`.
2. Separately, try creating a client using the `WithJSONReads` option.

**Comment by liron-l** [comment] 2023-09-19 04:54
Hi @tritone 
Thanks for your detailed reply.
Note that we use this library to download 3rd party data, so we can't control whether the data is corrupted.

1. This works, but it forces us to move the unziping part to our client code (including content discovery) and I don't think this is a good option
2. This hangs without `ReadCompressed(true)` and fails on  `custom Accept-Encoding headers not allowed`

Can we control the retry for the client side? I don't think hanging and performing 100k queries is considered good client behavior.

**Comment by liron-l** [comment] 2023-09-20 09:57
@tritone what are your thoughts on the issue? do you think this can be fixed?

**Comment by tritone** [comment] 2023-09-20 15:45
I think the best path in the immediate term is for you to use `ReadCompressed` and add gzip decompression logic to the application code. This way, you can handle any issues related to data corruption and get an appropriate error from the `compress/gzip` package. I don't think there is a lot of boilerplate that must be written IIUC.

After thinking about this some more I think it may be a bug in the [transcoding](https://cloud.google.com/storage/docs/transcoding) layer of GCS that the data is being sent in an invalid format, rather than gracefully returning an error from the service. If you file a customer support issue we may be able to investigate internally on that front (we need an internal support case to share details like bucket and object names for that investigation).

As far as client side retry, we recommend setting a context deadline on all requests to GCS in order to avoid indefinite retries. See https://pkg.go.dev/cloud.google.com/go/storage#hdr-Retrying_failed_requests . Did you have this in your application?

Retrying downloads is somewhat complicated given that (as in this case, from the client's perspective) the initial request can succeed but the download is interrupted midway through and must be resumed. I can look into making some kind of out for this situation, but, this logic has been around for quite a while and this is the first report I've received of a case where the download resumption logic ends up in an infinite loop. I'd need to do some investigation into how we can support this.

**Comment by tritone** [comment] 2024-02-06 21:53
There is a workaround and the internal issue was closed due to lack of response from customer, so I'm going to close this out.

**Closed by tritone** 2024-02-06 21:53 UTC
Labels: type: bug, api: storage, priority: p2
