### ISSUE TITLE
storage: signing URLs slower than other google SDKs

### ISSUE THREAD

**Issue by Aedalus** [googleapis/google-cloud-go#4538] opened 2021-08-01 15:14 UTC
**Client**

Storage

**Environment**

Ubuntu 20.04.1 LTS

**Go Environment**

go version go1.16.2 linux/amd64

**Code**

e.g.
```go
bucketName := "my-bucket"
key := "my-key"
jsonKey, err := ioutil.ReadFile("../../service-account-file.json")
	if err != nil {
		return "", fmt.Errorf("ioutil.ReadFile: %v", err)
	}
	conf, err := google.JWTConfigFromJSON(jsonKey)
	if err != nil {
		return "", fmt.Errorf("google.JWTConfigFromJSON: %v", err)
	}
	opts := &storage.SignedURLOptions{
		Scheme:         storage.SigningSchemeV4,
		Method:         "GET",
		GoogleAccessID: conf.Email,
		PrivateKey:     conf.PrivateKey,
		Expires:        time.Now().Add(15 * time.Minute),
	}

	start := time.Now()
	var u string
	for i := 0; i < 10; i++ {
		u, err = storage.SignedURL(bucketName, key, opts)
		if err != nil {
			return "", fmt.Errorf("storage.SignedURL: %v", err)
		}
	}
	end := time.Since(start)
	fmt.Printf("took %v\n", end)
```

```js
// ran on node 14.7
const {Storage} = require('@google-cloud/storage');

// Creates a client
const storage = new Storage();

async function generateV4ReadSignedUrl() {
  // These options will allow temporary read access to the file
  const options = {
    version: 'v4',
    action: 'read',
    expires: Date.now() + 15 * 60 * 1000, // 15 minutes
  };

  // Get a v4 signed URL for reading the file
  const start = new Date()
  for(let i = 0; i < 10; i++){
    const [url] = await storage
        .bucket("my-bucket")
        .file("my-key")
        .getSignedUrl(options);
  }

  const end = new Date() - start
  console.info('Execution time: %dms', end)

  console.log('Generated GET signed URL:');
}

generateV4ReadSignedUrl().catch(console.error);
```

**Expected behavior**

Go SDK should perform within the same order of magnitude of other SDKs, all else being equal.

**Actual behavior**

From some basic benchmarks run on the above code, I can tell it's taking roughly 10x as long to sign URLs using go as node. After running some benchmarks using the above, and averaging over 100 runs, it looks like the time it takes to sign 10 urls on my local machine averages to

go: 296.042242ms
node: 33ms

**Screenshots**

**Additional context**

Potential related issue: https://github.com/googleapis/google-cloud-go/issues/114

An average of ~30ms/URL for go seems incredibly slow compared to ~3ms/URL for the node SDK. I realize in a real world scenario signing these URLs should be done concurrently, and that is an option to help mitigate. However I don't believe there are any additional clients being instantiated etc that is slowing this down, it seems like the majority of time spent is within the `storage.SignedURL` function itself for even a single URL.

For additional comparison, I wrote an analogous test for AWS's signed URL feature, and their go sdk was averaging < 1 ms/url, compared to 29ms/url for gcp. This is definitely an apples to oranges comparison, likely different signing algorithms etc, but again makes me think that the ~30ms/URL for GCP storage seems strangely high.

Even if there's not a simple fix, hoping this issue might be useful in seeing if others are having similar problems.

**Comment by BrennaEpp** [comment] 2021-11-02 01:11
Hi @Aedalus, are you still having this issue? If so, which version of the Storage library are you using?

I'm unable to reproduce these results - average around ~17ms to sign 10 urls using the code provided above.

**Comment by BrennaEpp** [comment] 2021-11-09 01:53
Closing this issue for now as we cannot reproduce. Please re-open if you still experience this issue.

**Closed by BrennaEpp** 2021-11-09 01:53 UTC
Labels: type: bug, api: storage, priority: p2
