### ISSUE TITLE
datastore: concurrent transactions aren't being locked

### ISSUE THREAD

**Issue by andypwarren** [googleapis/google-cloud-go#3117] opened 2020-10-30 10:59 UTC
**Client**
Datastore v.1.3.0

**Environment**
MacOS 10.15.7 & Alpine Docker on GKE

**Go Environment**
1.15.3

**Code**
Please see this [repo](https://github.com/thisissoon/datastore-tx-issue) for a small reproducible example 

```go
package main

import (
	"context"
	"fmt"
	"log"
	"sync"

	"cloud.google.com/go/datastore"
)

const ItemKind = "item"

type Item struct {
	ID    string `datastore:"id"`
	Title string `datastore:"title"`
}

type Store struct {
	client *datastore.Client
}

// PutTx creates or updates a single item in datastore using a transaction.
// This is a simple example just to demonstrate the issue.
func (s *Store) PutTx(ctx context.Context, item *Item) error {
	tx, err := s.client.NewTransaction(ctx)
	if err != nil {
		return fmt.Errorf("error creating transaction: %v", err)
	}
	k := datastore.NameKey(ItemKind, item.ID, nil)
	_, err = tx.Put(k, item)
	if err != nil {
		return err
	}
	_, err = tx.Commit()
	if err != nil {
		rbErr := tx.Rollback()
		if rbErr != nil {
			return fmt.Errorf("error rolling back transaction: %v", rbErr)
		}
		return fmt.Errorf("error committing transaction: %v", err)
	}
	return nil
}

func main() {
	ctx := context.Background()
	client, err := datastore.NewClient(ctx, "")
	if err != nil {
		log.Fatal(err)
	}
	defer client.Close()
	s := &Store{
		client: client,
	}
	concurrentUpdates := []*Item{
		&Item{ID: "a", Title: "1"},
		&Item{ID: "a", Title: "2"},
	}
	var wg sync.WaitGroup
	var errors []error
	for i, item := range concurrentUpdates {
		wg.Add(1)
		go func(index int, item *Item) {
			defer wg.Done()
			err := s.PutTx(ctx, item)
			if err != nil {
				errors = append(errors, fmt.Errorf("error updating item %d: %v", index, err))
				return
			}
		}(i, item)
	}
	wg.Wait()
	for _, err := range errors {
		log.Fatal(err)
	}
}
```

**Expected behavior**
Concurrent transactions commit without erroring

**Actual behavior**
According to the datastore [docs](https://cloud.google.com/datastore/docs/concepts/transactions) 

> When two concurrent read-write transactions read or write the same data, the lock held by one transaction can delay the other transaction." 

This suggests that concurrent transactions should delay execution until previous transactions have completed, but instead we see this error `datastore: concurrent transaction`. I have tried this with different methods in a transactions e.g. `Upsert` and the same error occurs. Am I misunderstanding the documentation?

**Comment by tritone** [comment] 2020-11-10 20:06
I believe this is expected behavior. See the docs for `client.RunInTransaction` [here](https://pkg.go.dev/cloud.google.com/go/datastore#Client.RunInTransaction): 

`If f returns nil, RunInTransaction commits the transaction, returning the Commit and a nil error if it succeeds. If the commit fails due to a conflicting transaction, RunInTransaction retries f with a new Transaction. It gives up and returns ErrConcurrentTransaction after three failed attempts (or as configured with MaxAttempts).`

The retry logic occurs in `RunInTransaction`; it looks like just calling commit directly doesn't include any retries. See logic here and below: https://github.com/googleapis/google-cloud-go/blob/5e6c350b2ac94787934380e930af2cb2094fa8f1/datastore/transaction.go#L145

FYI @benwhitehead if you have other thoughts on this.

**Comment by BenWhitehead** [comment] 2020-11-16 20:55
What @tritone notes is accurate to the best of my knowledge. The server does not retry transactions, instead the status of the attempted commit will be in a non-success state and the client is expected to retry after evaluating the failure.

`RunInTransaction` takes care of this logic (including carrying forward the previously attempted transaction id so the server knows it is a reattempt), but removes the ability to call commit directly.

//cc @crwilcox

**Comment by tritone** [comment] 2020-11-16 21:01
Thanks @benwhitehead. Closing this; @andypwarren feel free to reopen if you have further issues.

**Closed by tritone** 2020-11-16 21:01 UTC
Labels: api: datastore, type: question

**Comment by andypwarren** [comment] 2020-11-17 09:15
@BenWhitehead @tritone Thanks for the help guys. I've tried this with `RunInTransaction` and it's working nicely.
