### ISSUE TITLE
resourcemanagerpb: SearchProjects() locally given a collection of *resourcemanagerpb.Project

### ISSUE THREAD

**Issue by kosmas-valianos** [googleapis/google-cloud-go#8071] opened 2023-06-09 13:15 UTC
**Is your feature request related to a problem? Please describe.**
The `SearchProjectsRequest` has a `Query` string for searching for projects according to the given filter. While this works fine it comes with the expense of an API call. Applications that serve requests to do something according to a project filter, end up making huge amount of API calls. At  each and every request at the application, it has to do an API call to filter the projects. The API calls for projects can be very problematic as the quota is low and is global across all projects. The application ends up getting rate limited. You could cache the result of each request but still this won't help so much as the requests can be different and anyhow at every X interval you will have to update all those which means again huge amount of API calls.

**Describe the solution you'd like**
Instead of making all these API calls the application can simply download all projects at every X interval, cache them and then do the filtering locally without the need of an API call. Basically the code that is already used and is running in the cloud side to be exposed in the SDK so that the applications can do the filtering by themselves, saving million of useless API calls and more critically to not get rate limited. It is just 1 API call at every X interval.

**Describe alternatives you've considered**
Implementing the whole project filter parsing yourself is doable but silly considering that this code is already implemented and running, just on the cloud side instead of the "client" SDK. It's a matter of exposing it.

**Additional context**

**Comment by quartzmo** [comment] 2023-06-09 15:44
@kosmas-valianos Thanks for opening this issue. We have a feature request template (pasted below), which may help to organize your suggestions. Keep in mind however that the `resourcemanagerpb` types (and the `resourcemanager` client code) in this repo are entirely generated from the protobuf definitions in [googleapis/googleapis/google/cloud/resourcemanager](https://github.com/googleapis/googleapis/tree/master/google/cloud/resourcemanager). Customizing the existing types is not easy since regeneration may entirely overwrite the files in this repo.


**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen. What should the API be? How would you use it?

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by quartzmo** [comment] 2023-06-09 19:53
> Is that code publicly available somewhere so that until and if it is integrated to the "client" SDK, we can see what the compute engine is doing?

I assume it is not. But if by some chance you find out how to do this, please link (or copy) it here for the benefit of others who later find and read this issue. From your description of the rate-limit problem, it seems very likely that others will seek this solution.

> I see it as a method of a new type ...

If the solution can exist outside of the current files in this client library, would it be possible to distribute it via a new module?

**Comment by kosmas-valianos** [comment] 2023-06-12 07:51
>I assume it is not

Yes, I cannot seem to find anywhere in the open source google code any parts of the compute engine ("server" side). It would be great if google people with awareness of the compute engine code can see this feature request, comment and give their input

>But if by some chance you find out how to do this

As we need a solution right away I am forced to re-invent the wheel 😢 and write a parser/interpreter for the project queries in order to achieve that local filtering. I will post it when it is done. Hopefully it won't be necessary...

>would it be possible to distribute it via a new module?

It can be thought of as meta utilities so from that perspective it can work nicely as a distinct module with the generic purpose of implementing the [GCP filter "language"](https://cloud.google.com/sdk/gcloud/reference/topic/filters ). But again, the people that have **already** implemented that code will know better where their "interpreter" would fit in the client SDK

**Comment by quartzmo** [comment] 2023-06-21 22:39
> As we need a solution right away I am forced to re-invent the wheel 😢 and write a parser/interpreter for the project queries in order to achieve that local filtering. I will post it when it is done. 

I will close this issue now, but please link to your solution if you publish it, thank you!

**Closed by quartzmo** 2023-06-21 22:39 UTC
Labels: type: feature request, api: cloudresourcemanager

**Comment by kosmas-valianos** [comment] 2023-06-22 07:03
Yeap I am working with it. Will post a link when I make the github repository public

**Comment by kosmas-valianos** [comment] 2023-06-27 15:39
So here is it: https://github.com/kosmas-valianos/gcloudfilter

Full support of [gcloud topic filters](https://cloud.google.com/sdk/gcloud/reference/topic/filters) besides 2 temporary caveats
