### ISSUE TITLE
storage: memory leak on object creation

### ISSUE THREAD

**Issue by krisztiansala** [googleapis/google-cloud-go#8216] opened 2023-07-06 08:26 UTC
**Client**

Storage

**Environment**

Ubuntu 20.04.6 LTS, docker container on GKE

**Go Environment**

go version go1.20 linux/amd64

**Code**

https://gist.github.com/krisztiansala/fbb72ae6e8206c3d4682fc0c04cbcb7e

Running this example script, you can see that the total allocated memory can go from 1.7 MB to 16.8 MB (your results may differ, but it is clearly increasing). 

**Expected behavior**

Memory allocation stays constant

**Actual behavior**

The total allocated memory is continuously increasing

**Screenshots**

This screenshot shows the memory increase in kubernetes pods, until they are restarted:
![image](https://github.com/googleapis/google-cloud-go/assets/23317859/3faf9851-3d8c-44f9-b8d2-6d9a422be5dd)

Here it can be seen from the profiling flame graph that the NewMediaBuffer takes up most of the allocated memory:
![image](https://github.com/googleapis/google-cloud-go/assets/23317859/d163dda9-b66b-4ed2-9eda-b9cf334c7c70)

**Additional context**

There is an io.Reader inside [this Media object](https://github.com/googleapis/google-cloud-go/blob/1fa4bb8b3f22aad0b97ccae610408720522a8b31/storage/http_client.go#L885C7-L885C7) that is not closed, I suspect the leak is coming from there.

**Comment by tritone** [comment] 2023-07-06 20:41
It's definitely the case that we expect buffer allocations inside each `Writer` and that would default to 16 MiB. If you're sending smaller objects, you can definitely optimize by setting `Writer.ChunkSize` to a smaller value, or to zero if you don't want the request to be buffered (if it's zero you will lose the ability for the request to restart if interrupted). See the Writer docs for more details.

I can take a look into running the repro and will let you know what I find there. But yeah having 16 MiB allocated would just be a single open Writer with default ChunkSize, so that should not be too surprising.

**Comment by krisztiansala** [comment] 2023-07-10 06:45
Thanks for the recommendation, I changed the ChunkSize to zero

**Comment by siddharthg** [comment] 2023-09-12 19:42
I am facing a similar issue, in my case the allocated heap for this goes upto 8Gbs, ends with a restart everytime. It is slow and takes time, but almost every time ends with restart. Smells like a memory leak. 

<img width="985" alt="Screenshot 2023-09-13 at 1 12 25 AM" src="https://github.com/googleapis/google-cloud-go/assets/5453903/def9db25-0c84-432c-ae1e-448d41f83204">


<img width="1885" alt="Screenshot 2023-09-13 at 1 08 53 AM" src="https://github.com/googleapis/google-cloud-go/assets/5453903/6b770f61-ce21-4d10-baa0-ed1fc805bee0">

**Comment by tritone** [comment] 2023-09-12 19:55
@siddharthg can you provide code of what you are doing? A minimal code snippet that reproduces the issue would be very helpful if possible.

**Comment by siddharthg** [comment] 2023-09-13 11:29
```go
func PutOnGCS(ctx context.Context, header map[string]string, objectName string, bucketName string, newImage []byte) error {
	if len(newImage) < 1 {
		return errors.New("invalid file to upload")
	}

	gcsObject := gcs.Bucket(bucketName).Object(objectName)
	_, err := getHeaders(ctx, gcsObject)
	if err == storage.ErrObjectNotExist {
		logging.Info(ctx).Msgf("File doesn't exist, uploading %v", objectName)
		objectWriter := gcs.Bucket(bucketName).Object(objectName).NewWriter(ctx)
		setAttributesFromHeaders(header, objectWriter)
		_, err := io.Copy(objectWriter, bytes.NewReader(newImage[:]))
		if err != nil {
			logging.Error(ctx).Msgf("Failed to upload file %v: %v", objectName, err)
		}
		if err := objectWriter.Close(); err != nil {
			logging.Error(ctx).Msgf("Failed to close writer %v: %v", objectName, err)
		}
		return nil
	}
	logging.Warn(ctx).Msgf("File already exist, skipping %v", objectName)
	return nil
}
```

I am also adding a chunksize to `googleapi.MinUploadChunkSize`, but even without that the 16MB chunks seems to be not getting removed from allocated heap.

**Comment by tritone** [comment] 2023-09-13 13:22
A couple further questions:
1. How large are the objects which you are uploading?
2. Are you calling this function sequentially in a loop, or from multiple goroutines at once? If so how many?
3. Have you tried using a smaller value for `Writer.Chunksize`? If so what happened?

I see that this code is not runnable as a standalone but I can try to make a proper repro when I have some time. If you have an internal support case for this issue you can ask the support engineer to tag me in that case (they can look me up by my github user name).

**Comment by siddharthg** [comment] 2023-09-13 18:41
1. The average size is few kBs (10-100), some might go at a scale of 1-2MBs. 
2. Its being called in the http handler, sequentially, the server usually handles 100 requests per second. 
3. Have deployed the changes, monitoring it.

Would create a ticket, once I have more details.

**Comment by tritone** [comment] 2023-09-13 20:30
Okay, so to start, you should definitely choose a smaller value for `Writer.ChunkSize`. See docs https://pkg.go.dev/cloud.google.com/go/storage#Writer.ChunkSize. Set this property after creating the writer but before writing any bytes. I think you can definitely reduce memory use significantly by setting ChunkSize to the minimum (256 KiB) or just larger than the file size.

If you get bursts of requests, you might want to consider using a set number of workers and queueing in order to avoid blowing up resource usage.

We're also working on an upload method which will not use buffers, if the entire object is available on disk or in memory. I'll update the issue when we have a PR for that.

**Comment by taylorchu** [comment] 2023-09-13 21:09
Concurrency plays a huge role in this. From testing, the memory used is at least (16MB * concurrent uploads). so if you have 100 concurrent upload http requests, you could be using about 2~3GB just for the buffer.

googleapi default buffer size (8MB; now 16MB) is definitely aggressive; for comparison, s3 uses 3-4MB buffer.

**Comment by tritone** [comment] 2023-09-18 19:08
@taylorchu yes indeed. 16MiB is ideal for performance on larger objects, but if you are uploading smaller objects we highly recommend reducing this value.

**Comment by tritone** [comment] 2024-02-06 21:50
Closing this out since I answered the questions and there hasn't been further activity since sept. Feel free to open a new issue if you have further questions.

**Closed by tritone** 2024-02-06 21:50 UTC
Labels: api: storage, status: investigating
