### ISSUE TITLE
Unable to set a pubsub Subscription Expiration Policy

### ISSUE THREAD

**Issue by ByteFlinger** [googleapis/google-cloud-go#1363] opened 2019-03-15 01:10 UTC
## Client

PubSub

## Issue

The subscription API allows one to set how long a subscription will exist if idle (See [documentation](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.Subscription))

I have not been able to find anyway to set the [ExpirationPolicy](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#google.pubsub.v1.ExpirationPolicy) using the SDK for creating a subscription.

Is this not supported for some reason?

**Comment by jadekler** [comment] 2019-03-15 03:50
Dupe of https://github.com/googleapis/google-cloud-go/issues/1361. We'll track it there.

**Closed by jadekler** 2019-03-15 03:50 UTC
