### ISSUE TITLE
bigtable: concurrent mutations not applied

### ISSUE THREAD

**Issue by bshafiee** [googleapis/google-cloud-go#1826] opened 2020-03-13 20:34 UTC
Info:
* Go version: `1.14`
* Using the latest api:  `"cloud.google.com/go"   version = "0.54.0"`
* Test was performed on a single Bigtable production cluster, hence no replication and expecting immediate consistency (reads after write should see the latest version).

I was able to reproduce an issue where the go client does not apply concurrent mutations (writes) to the same key (when there is no GC in place). 
```
package main

import (
	"context"
	"fmt"
	"log"
	"strconv"
	"sync"
	"time"

	"cloud.google.com/go/bigtable"
)

func main() {
	rowKey := "rowkey"
	projectName := "my_project_name"
	instanceName := "my_instance"
	tableName := "my_table"
	columnFamily := "cf"

	printGCPolicy(projectName, tableName, instanceName)
	fmt.Printf("Deleting all existing history: ")
	doDelete(rowKey, tableName, projectName, instanceName)
	fmt.Println("✔")
	fmt.Println("Applying mutations:")
	doWrite(rowKey, tableName, columnFamily, projectName, instanceName)
	time.Sleep(time.Millisecond * 500)
	fmt.Printf("\nReading Table:\n")
	dumpTable(rowKey, tableName, columnFamily, projectName, instanceName)
}

func printGCPolicy(projectName, tableName, instanceName string) {
	adminClient, err := bigtable.NewAdminClient(context.Background(), projectName, instanceName)
	if err != nil {
		log.Fatal(err)
	}
	tableInfo, err := adminClient.TableInfo(context.Background(), tableName)
	if err != nil {
		log.Fatal()
	}
	fmt.Println("FamilyName | Policy")
	fmt.Println("-------------------")
	for _, finfo := range tableInfo.FamilyInfos {
		fmt.Println("GC:", finfo.Name, " : ", finfo.GCPolicy)
	}
	fmt.Println()
}

func doWrite(rowKey, tableName, columnFamily, projectName, instanceName string) {
	client, err := bigtable.NewClient(
		context.Background(),
		projectName,
		instanceName)
	if err != nil {
		log.Fatal(err)
	}
	defer client.Close()
	affnTb := client.Open(tableName)

	wg := sync.WaitGroup{}
	totalWrites := 9
	for i := 1; i <= totalWrites; i++ {
		wg.Add(1)
		go func(index int) {
			mut := bigtable.NewMutation()
			mut.Set(columnFamily, "", bigtable.ServerTime, []byte("token"+strconv.Itoa(index)))
			err = affnTb.Apply(context.Background(), rowKey, mut)
			if err != nil {
				log.Fatal(err)
			}
			fmt.Println("Successfully wrote:", index, " err:", err)
			wg.Done()
		}(i)
	}
	wg.Wait()
	fmt.Println("Finished applying all mutations (history) for key:", rowKey, ", ", totalWrites, " times")
}

func dumpTable(rowKey, tableName, columnFamily, projectName, instanceName string) {
	client, err := bigtable.NewClient(
		context.Background(),
		projectName,
		instanceName)
	if err != nil {
		log.Fatal(err)
	}
	defer client.Close()
	affnTb := client.Open(tableName)
	r, err := affnTb.ReadRow(context.Background(), rowKey, bigtable.RowFilter(bigtable.FamilyFilter(columnFamily)))
	if err != nil {
		log.Fatal(err)
	}

	tokenCols := r[columnFamily]
	fmt.Println("total:", len(tokenCols))
	for i, item := range tokenCols {
		fmt.Println("index:", i, "  ", string(item.Value))
	}
}

func doDelete(rowKey, tableName, projectName, instanceName string) {
	client, err := bigtable.NewClient(
		context.Background(),
		projectName,
		instanceName)
	if err != nil {
		log.Fatal(err)
	}
	defer client.Close()

	affnTb := client.Open(tableName)
	mut := bigtable.NewMutation()
	mut.DeleteRow()
	err = affnTb.Apply(context.Background(), rowKey, mut)
	if err != nil {
		log.Fatal(err)
	}
}
```

Running this code, I see the following output:
<img width="620" alt="output" src="https://user-images.githubusercontent.com/4823205/76657024-1f860800-652e-11ea-9396-52e55e5dc8f1.png">

You can see in the output that the column family for the desired table doesnt have any GC policy (hence should retain infinite history). Next we apply 9 mutations concurrently with the same key and *wait* until all of them return with no error. 
Then we read the same table for the same key and you can see only 4 items were stored. I verified this with cbt too and they never show up. This was run on a production Bigtable cluster and the behaviour is the same with the emulator too. 
FWIW, if I simply remove the concurrent go routines and perform the mutations one after another, there wont be any issue and the histroy is complete. I mean like this in the `doWrite` function:
```
	totalWrites := 9
	for i := 1; i <= totalWrites; i++ {
		mut := bigtable.NewMutation()
		mut.Set(columnFamily, "", bigtable.ServerTime, []byte("token"+strconv.Itoa(index)))
		err = affnTb.Apply(context.Background(), rowKey, mut)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println("Successfully wrote:", index, " err:", err)
	}
```

**Comment by igorbernstein2** [comment] 2020-03-24 14:30
This is working as intended. Bigtable is a 4 dimensional map that can be roughly visualized as:
```json
"rowKey" : {
  "columFamily": {
     "qualifier": {
        timestampAs64BitInteger: "value"
    }
  }
}
```

Currently Bigtable only allows millisecond granularity. In your example you are reusing the same row/family/qualifier and using  server side  timestamps. You are also writing more than 1 value per millisecond, so you will have collisions of your compound key of key/family/qualifier/timestamp, which will cause values to be overwritten.

**Comment by igorbernstein2** [comment] 2020-03-24 14:31
@tritone or @kolea2 I don't have permissions to close this issue, can you do it?

**Comment by tritone** [comment] 2020-03-25 16:22
Yes; thanks very much for the explanation @igorbernstein2 !

**Closed by tritone** 2020-03-25 16:22 UTC
Labels: api: bigtable, priority: p2, type: bug
