### ISSUE TITLE
pubSub: infinite loop (or deadlock) when pulling subscription

### ISSUE THREAD

**Issue by guillaumeblaquiere** [googleapis/google-cloud-go#1444] opened 2019-06-01 15:52 UTC
Hello

I experience the same issue as the #1156 with the lib version: cloud.google.com/go v0.39.0
It occurs randomly on Cloud Run and Cloud Function (alpha Go 1.12).

The received function doesn't exist even if the cancel context is triggered

I release a version (of cloud function package) of my code (but it shouldn't be useful, the problem is exactly this one described)
https://github.com/guillaumeblaquiere/pubsubToBq

I speak about infinite loop, maybe memory leak, because I have this kind of memory graph on Cloud Run:
![image](https://user-images.githubusercontent.com/1756715/58750689-e0526300-8495-11e9-875b-90f81786a960.png)

**Comment by hongalex** [comment] 2019-06-03 20:48
Hi @guillaumeblaquiere,

Could you provide some more information on the code that is being executed during the periods of increased memory alloc? I want to make sure the issue is indeed related to #1156 as opposed to another issue. Thanks!

**Comment by guillaumeblaquiere** [comment] 2019-06-04 09:44
Hi @hongalex 

The problem occur in this part of the code:
https://github.com/guillaumeblaquiere/pubsubToBq/blob/master/services/PubSubService.go#L53

For me, the memory leak isn't in my part of code. I think, it's in the library, but I'm too beginner in Go to investigate myself (I learnt go 5 weeks ago).

In my log trace, I see the "Cancel by Timeout" (line 73) then nothing util the 300s default timeout of Cloud Run.

In addition, there is no message consumed in the PubSub, as the communication can't be established. I also don't know GRPC protocol to find the issue...

Hope this help. Don't hesitate to ask me more if needed.

**Comment by hongalex** [comment] 2019-06-05 18:51
Thanks for the information! That should help us look into this further. We're currently in the middle of fixing other triaged issues, but if we'll post updates here as we learn more.

**Comment by hongalex** [comment] 2019-06-06 22:26
@guillaumeblaquiere 

Following up a bit further: would you mind also attaching some steps for reproducing the issue? For example, can you detail the steps and settings you used to setup Cloud Run and what kind of test data you published to Pub/Sub? Thanks!

**Comment by guillaumeblaquiere** [comment] 2019-06-07 09:21
@hongalex 

For simplifying the test on your side and the replay of this issue, I extract and simplify my code in a simple main file. I set static values instead of using env var and I don't ACK the message for not disturbing my current process.

I ran about 10 times the program before having this random issue. On normal execution, the log show 
* Cancel by Timeout
* Number of message processed

When the issue occur, only the cancel by Timeout is displayed.

Cloud run param (memory and others, like concurrency) don't matter. The issue also occurs on Cloud Function and on my Chromebook (Linux VM). The data on PubSub have this structure:
* 3 "small" attributes, each one about 10 characters
* body is a JSON message with a size between 1kb and 5kb

But the message format shouldn't also matter, because there is no message read/ack when the issue occur. I think it's a connexion init/handshake deadlock.  

Let me know if you need more!
Thanks

```
package main

import (
	"cloud.google.com/go/pubsub"
	"context"
	"flag"
	"fmt"
	joonix "github.com/joonix/log"
	log "github.com/sirupsen/logrus"
	"os"
	"time"
)

func main() {
	log.SetFormatter(joonix.NewFormatter())
	//Set the debug level or not
	lvl := flag.String("level", log.DebugLevel.String(), "log level")
	flag.Parse()

	level, err := log.ParseLevel(*lvl)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	log.SetLevel(level)

	Received()
}

func Received() (msgArray []*pubsub.Message, err error) {


	projectId := "bdz-shd-nohrendpoint-dev"
	subscriptionName := "raw-message-subscription"

	//Connect the client to PubSub
	ctx := context.Background()
	client, err := pubsub.NewClient(ctx, projectId)
	if err != nil {
		log.Fatalf("Impossible to connect to pubsub client for project %s", projectId)
	}

	cctx, cancel := context.WithCancel(ctx)
	msgArray = []*pubsub.Message{}

	var receivedMessage = make(chan *pubsub.Message)

	go func() {
		//Initial timeout because the first received is longer than this others.
		timeOut := time.Duration(3000)
		for {
			select {
			case msg := <-receivedMessage:
				//After the first receive, the timeout is changed
				timeOut = 200
				msgArray = append(msgArray, msg)
			case <-time.After(timeOut * time.Millisecond):
				log.Debug("Cancel by timeout")
				cancel()
				return
			}
		}
	}()

	err = client.Subscription(subscriptionName).Receive(cctx, func(ctx context.Context, msg *pubsub.Message) {
		receivedMessage <- msg
		//msg.Ack()
	})
	if err != nil {
		log.Errorf("Error raised %v", err)
		return
	}
	log.Infof("%v messages processed", len(msgArray))
	return
}
```

**Comment by guillaumeblaquiere** [comment] 2019-06-13 12:58
Hello @hongalex 

I found a work arround. I force the client to close after the cancel call. Here my 3 lines after the cancel(). I let 2 secondes the chance to the lib to exit gracefully, and then I call always the client.Close(). This breaks the deadlock.
```
				time.After(2000 * time.Millisecond)
				log.Debug("To prevent deadlock. Force the client to close")
				client.Close()
```

**Comment by hongalex** [comment] 2019-06-14 01:32
Glad you were able to find a workaround in the meantime. Nonetheless, the behavior your reported is still strange so we'll keep looking into it. Also, thanks for the sample code. I haven't been able to reproduce the error yet on a local machine or Cloud Functions yet, but I'll do a more thorough test soon.

**Comment by guillaumeblaquiere** [comment] 2019-06-15 19:36
Hi @hongalex 

My workaround is great, but not perfect. On cloud run, here the graph of memory usage the last 7 days. (Remainder: my Cloud Run is called every 10 minutes by a Cloud Scheduler -> 144 call per day)
![image](https://user-images.githubusercontent.com/1756715/59555568-cdbb4c00-8fb4-11e9-858f-1763881babc6.png)

You can see on the left, a high memory usage (because the peak/infinite loop/memory leaks occur very often). On the right, it's far more rare, but not null (2 times the last 24H).
FYI, the blank between both is a Python test. Sadly, the is also some unexpected behavior in Python (and I don't like no type safe language). Thus, I go back to Go and try the current workaround.

**Comment by hongalex** [comment] 2019-06-21 20:47
It looks like the peaks are a lot lower, so it seems like the issue is mostly contained.

As for why there's increased usage at all, the root cause seems similar to #1460. It was related to the fact that not all messages were properly ack'd, which will cause the timeout. The `cancel` function doesn't force pending messages to be deleted, and thus will hang indefinitely until they are properly `ack` or `nack`d. I'm going to close this issue for now, but if you see similar metrics between number of messages published vs number of messaged `ack`d, go ahead and comment below.

**Closed by hongalex** 2019-06-21 20:47 UTC
Labels: api: pubsub, type: question
