### ISSUE TITLE
storage: size attribute is incorrect for gzipped files

### ISSUE THREAD

**Issue by gWOLF3** [googleapis/google-cloud-go#1766] opened 2020-01-31 02:11 UTC
**Client**
Storage

**Environment**
Local

I noticed this bug when setting the Content-Length for my proxy based on the Size attribute. It works fine with regular files, but when files are gzipped, the Size is incorrect. 

probably related to #1734

**Comment by gWOLF3** [comment] 2020-01-31 04:49
more info: 

when getting NewReader(ctx).Attrs(ctx) for a gzip file, I get size = -1.  The regular storage client.bucket.attr.size DOES return a size, but its wrong. 

On the other hand, when I use NewReader(ctx) with a non gzip file, I get the correct size. The regular (old) Client.Bucket(ctx).Object(ctx).Attrs(ctx) also works.

**Comment by tbpg** [comment] 2020-01-31 12:33
Possibly related to #1743 and #1734.

**Comment by frankyn** [comment] 2020-02-04 01:18
Good question to call out. I didn't see anything in Cloud Storage documentation and will follow-up on that. 

Current understanding:
Transcoding is performed on request hence the Content-Length of the decompressed file is not available until you've received all the bytes. 

This is working as intended and is the behavior of the service.

**Comment by frankyn** [comment] 2020-02-05 18:32
This is WAI, confirmed with the team. We are addressing this in documentation. I'm closing this question, thank you for raising it!

> Yes, this is expected and WAI, because transfer-encoding header is "chunked". See for instance https://en.wikipedia.org/wiki/Chunked_transfer_encoding: "In this case, the HTTP Content-Length header cannot be used to delimit the content and the next HTTP request/response, as the content size is not yet known"

**Closed by frankyn** 2020-02-05 18:32 UTC
Labels: api: storage, type: question
