### ISSUE TITLE
datastore: datastore.Mutate seems not to be atomic

### ISSUE THREAD

**Issue by apstndb** [googleapis/google-cloud-go#1742] opened 2020-01-23 04:00 UTC
In godoc, `datastore.Mutate` says it is atomic.
https://github.com/googleapis/google-cloud-go/blob/v0.52.0/datastore/datastore.go#L633
but it uses `NON_TRANSACTIONAL` commit mode same as `datastore.PutMulti`.
https://github.com/googleapis/google-cloud-go/blob/v0.52.0/datastore/datastore.go#L650
`NON_TRANSACTIONAL` seems not to be atomic at least Cloud Datastore(I don't know Cloud Firestore Datastore mode ignores the mode).
https://cloud.google.com/datastore/docs/reference/data/rpc/google.datastore.v1?hl=en#google.datastore.v1.CommitRequest.Mode
https://cloud.google.com/datastore/docs/concepts/entities?hl=en#batch_operations

IMO, it should be treated as documentation bug.
`NON_TRANSACTIONAL` is preferred because entity group limitation of Cloud Datastore is still real.

It is better to add reference to `Transaction.Mutate()` for situation that atomicity is important.

**Comment by tbpg** [comment] 2020-01-23 15:44
Marking as a P1 bug since this could cause problems if the docs are trusted (as they should be). Haven't confirmed the issue.

**Comment by apstndb** [comment] 2020-01-24 10:12
I am confirmed it is not atomic even Cloud Firestore Datastore mode.
https://gist.github.com/apstndb/5ffab4b7f90ad7ddb29ed8c529f6052c

**Comment by BenWhitehead** [comment] 2020-02-05 20:03
@apstndb You are correct, the only time atomicity is guaranteed is when run inside a transaction. We'll need to get the godocs update to be accurate. Thank you for raising this issue.

**Closed** 2020-02-12 18:36 UTC
Labels: :rotating_light:, api: datastore, priority: p1, type: bug
