### ISSUE TITLE
spanner: unflake TestTakeWriteSessionFromIdleList

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1303] opened 2019-02-04 20:22 UTC
https://sponge.corp.google.com/target?id=4c79f62f-abf3-4cac-8f94-4ea36a4aae0c&target=cloud-go-libraries%2Fgoogle-cloud-go%2Fpresubmit%2Fgo110&searchFor=

```
--- FAIL: TestTakeWriteSessionFromIdleList (0.01s)
	session_test.go:203: got sessions: map[mockdb-1549310490327002109:true mockdb-1549310490327099188:true mockdb-1549310490327202700:true mockdb-1549310490327291412:true mockdb-1549310490328561325:true mockdb-1549310490329610100:true mockdb-1549310490327379703:true mockdb-1549310490327572888:true mockdb-1549310490331464037:true mockdb-1549310490331597045:true], want map[mockdb-1549310490327572888:true mockdb-1549310490327202700:true mockdb-1549310490327291412:true mockdb-1549310490327496412:true mockdb-1549310490327002109:true mockdb-1549310490328561325:true mockdb-1549310490327099188:true mockdb-1549310490327379703:true mockdb-1549310490328308450:true mockdb-1549310490328436387:true]
```

**Comment by olavloite** [comment] 2019-04-21 18:32
This is caused by the SessionPool maintainer that sometimes deletes (some of) the sessions that have been created in the time between that they are returned to the pool and before they are checked out from the pool again. This can be prevented by manually setting the minimum number of sessions to 10 before the sessions are returned to the pool.
Fixed by https://code-review.googlesource.com/c/gocloud/+/40170

**Comment by olavloite** [comment] 2019-05-07 07:59
The above will also be fixed by https://code-review.googlesource.com/c/gocloud/+/40150.
Fix https://code-review.googlesource.com/c/gocloud/+/40170 is only working around the problem and is not needed.

**Closed** 2019-10-28 08:15 UTC
Labels: api: spanner, help wanted, type: cleanup
