### ISSUE TITLE
all: add static analysis presubmit

### ISSUE THREAD

**Issue by tritone** [googleapis/google-cloud-go#6378] opened 2022-07-20 02:23 UTC
When I recently re-imported the storage module into third_party, static analysis presubmits there caught a number of minor bugs such as unused err values, use of deprecated types, and nil dereferences.

Not all of these checks are available in OSS world, but we should at least consider running [staticcheck](https://staticcheck.io/) as a presubmit on all PRs, using a github action potentially.

In the future, we could also add additional checks via writing our own analyzer using https://pkg.go.dev/golang.org/x/tools/go/analysis as well, if we feel it's worthwhile.

**Comment by codyoss** [comment] 2022-07-22 14:37
We actually do user staticcheck today, but we have manually disabled some of the rules, with grep filtering, and have outright skipped some of the packages it processes. Maybe it is time to walk these back a bit: https://github.com/googleapis/google-cloud-go/blob/8a8ba85311f85701c97fd7c10f1d88b738ce423f/internal/kokoro/vet.sh#L82

**Comment by codyoss** [comment] 2022-08-01 19:37
Closing this as a dupe of https://github.com/googleapis/google-cloud-go/issues/6135. Might not be exactly the same but I think this effort can be rolled up to that issue.

**Closed by codyoss** 2022-08-01 19:37 UTC
Labels: type: process
