### ISSUE TITLE
spanner/spansql: parse error upper (general request: Make spansql case-insensitive)

### ISSUE THREAD

**Issue by geerttouquet** [googleapis/google-cloud-go#4027] opened 2021-04-29 20:09 UTC
EDIT based on information below:

More in general: spansql is currently case sensitive and expects all keywords and function names to be written in upper case. Although it is documented as a TODO, it sometimes causes unexpected errors as Cloud Spanner itself is not case sensitive for keywords and function names. It would therefore be beneficial to make the parsing of all keywords in spansql case insensitive.

We are using golang spansql 1.17.0

if we parse the following sql (that is generate by google)

CREATE TABLE resourceWorkschedule (
resourceWorkscheduleId STRING(MAX) NOT NULL,
labelUpper STRING(MAX) NOT NULL AS (upper(label)) STORED,
send_userRoleId STRING(MAX) NOT NULL,
send_version TIMESTAMP NOT NULL OPTIONS (
allow_commit_timestamp = true
),
) PRIMARY KEY(resourceWorkscheduleId);

we got following error / got "(" while expecting ")"
the problem is related by AS (upper(label)) STORED , I believe

is this possible to solve this ?

**Comment by hengfengli** [comment] 2021-04-30 05:07
@olavloite Can you please take a look at this? Thanks.

**Comment by olavloite** [comment] 2021-04-30 10:03
@geerttouquet Are you sure that this snippet is the entire snippet?

```sql
CREATE TABLE resourceWorkschedule (
resourceWorkscheduleId STRING(MAX) NOT NULL,
labelUpper STRING(MAX) NOT NULL AS (upper(label)) STORED,
send_userRoleId STRING(MAX) NOT NULL,
send_version TIMESTAMP NOT NULL OPTIONS (
allow_commit_timestamp = true
),
) PRIMARY KEY(resourceWorkscheduleId);
```

It seems to be missing the `label` column definition. A computed column can only be created based on other existing columns on the table, so I would expect the `(upper(label))` expression to fail.

**Comment by olavloite** [comment] 2021-04-30 11:27
The error itself is caused by the fact that `spansql` is case sensitive and expects all keywords and function names in UPPER case. See https://github.com/googleapis/google-cloud-go/blob/3e8390013e729d44f8a9ebc24ccf20f4982f4648/spanner/spansql/parser.go#L2569

So in this specific case changing the function name from `upper` to `UPPER` will fix that.

More in general: Case insensitivity is an open feature request for spansql, and I don't think it is wise to start fixing it on a case by case basis (e.g. changing function names specifically to being case insensitive). Instead it would be better to introduce case insensitivity for all keywords, function names, etc. in one go.

**Comment by geerttouquet** [comment] 2021-04-30 11:48
The complete definition is 

CREATE TABLE resourceWorkschedule (
  resourceWorkscheduleId STRING(MAX) NOT NULL,
  resourceName STRING(MAX) NOT NULL,
  resourceType STRING(MAX) NOT NULL,
  label STRING(MAX) NOT NULL,
  comment STRING(MAX) NOT NULL,
  labelUpper STRING(MAX) NOT NULL AS (upper(label)) STORED,
  send_clientId STRING(MAX) NOT NULL,
  send_clientVersion STRING(MAX) NOT NULL,
  send_middleTierId STRING(MAX) NOT NULL,
  send_middleTierVersion STRING(MAX) NOT NULL,
  send_sessionId STRING(MAX) NOT NULL,
  send_tenantId STRING(MAX) NOT NULL,
  send_entityId STRING(MAX),
  send_userId STRING(MAX) NOT NULL,
  send_userRoleId STRING(MAX) NOT NULL,
  send_version TIMESTAMP NOT NULL OPTIONS (
    allow_commit_timestamp = true
  ),
) PRIMARY KEY(resourceWorkscheduleId);

**Comment by olavloite** [comment] 2021-04-30 11:48
@geerttouquet I 'hijacked' this issue and transformed it into a more general request for case-insensitive parsing of keywords and function names. I hope you're ok with that. I'm not saying that this will get very high priority, but at least we have it documented along with an actual issue that there is a request for it.

**Comment by geerttouquet** [comment] 2021-04-30 11:53
remark : the upper(label) is genenareted by the adminClient.GetDatabaseDdl(ctx, &adminpb.GetDatabaseDdlRequest

**Comment by olavloite** [comment] 2021-04-30 13:41
Good to see the confirmation that it works for you too with `UPPER`.

> remark : the upper(label) is genenareted by the adminClient.GetDatabaseDdl(ctx, &adminpb.GetDatabaseDdlRequest

Yeah, that function will call this RPC: https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.admin.database.v1#google.spanner.admin.database.v1.DatabaseAdmin.GetDatabaseDdl

So the actual DDL in this case is coming from the backend. This has to do with the fact that Spanner stores the expression for a computed column exactly as it was during the creation of the column. You can also see this if you do a select on INFORMATION_SCHEMA.COLUMN. So if you execute the following query on your database:

```sql
SELECT COLUMN_NAME, GENERATION_EXPRESSION 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE IS_GENERATED = 'ALWAYS'
```

you should also see the same `upper` statement that is also returned by the method in the Go client.

**Comment by geerttouquet** [comment] 2021-04-30 13:52
Thanks , this is very good information.  For me the issue is solved

**Comment by olavloite** [comment] 2021-04-30 13:54
> Thanks , this is very good information. For me the issue is solved

I'll close this one and create a more general feature request for case insensitivity.

**Closed by olavloite** 2021-04-30 13:54 UTC
Labels: api: spanner, type: feature request
