### ISSUE TITLE
spanner: unflake TestApply_Single

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1382] opened 2019-04-05 15:04 UTC
```
--- FAIL: TestApply_Single (0.01s)
	transaction_test.go:166: got 3 requests, want 2 requests:
		got:
		*spanner.CreateSessionRequest: database:"mockdb" session:<> ]
		*spanner.CommitRequest: session:"mockdb-1554407750233904319" single_use_transaction:<read_write:<> > mutations:<insert:<table:"Accounts" columns:"AccountId" columns:"Nickname" columns:"Balance" values:<values:<string_value:"1" > values:<string_value:"Foo" > values:<string_value:"50" > > > > mutations:<insert:<table:"Accounts" columns:"AccountId" columns:"Nickname" columns:"Balance" values:<values:<string_value:"2" > values:<string_value:"Bar" > values:<string_value:"1" > > > > ]
		*spanner.DeleteSessionRequest: name:"mockdb-1554407750233904319" ]
		
		want:
		*spanner.CreateSessionRequest: ]
		*spanner.CommitRequest: ]
```

https://sponge.corp.google.com/target?id=fbe21f45-4e7e-4903-853d-e2db42123ab2&target=cloud-go-libraries/google-cloud-go/presubmit/go19&searchFor=&show=ALL&sortBy=STATUS

**Comment by olavloite** [comment] 2019-04-21 13:14
This seems to be caused by the SessionPool maintainer that aggressively deletes sessions on its first iteration that is started directly after the creation of the SessionPool. This should be solved by https://code-review.googlesource.com/c/gocloud/+/40150.

**Comment by olavloite** [comment] 2019-10-28 08:49
Fixed by https://github.com/googleapis/google-cloud-go/commit/80979225afc76a1e08783859dc578ff0c0cffabd

**Closed by olavloite** 2019-10-28 08:49 UTC
Labels: api: spanner, help wanted, type: cleanup
