### ISSUE TITLE
logging: library doesn't allow to set logname on entry level

### ISSUE THREAD

**Issue by loburm** [googleapis/google-cloud-go#3714] opened 2021-02-19 09:33 UTC
**Client**

Logging

**Expected behavior**

In the official API documentation I haven't found any restrictions on [log_name](https://cloud.google.com/logging/docs/reference/v2/rpc/google.logging.v2#logentry) field. Also it seems that other libraries don't have such requirement (for example [ruby](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-logging/lib/google/cloud/logging/entry.rb#L114))

**Actual behavior**

Whenever you try to set LogName field and then create a request next error will be received:

> logging: Entry.LogName should be not be set when writing

Error comes from: https://github.com/googleapis/google-cloud-go/blob/master/logging/logging.go#L899

**Comment by loburm** [comment] 2021-02-22 10:10
I have tried to remove that check from the client library and added one line of code that sets a value in final LogEntry and everything seems to be working (of course logName should have a correct format).

If you want, then I can send a PR to fix it?

**Comment by nicoleczhu** [comment] 2021-02-22 17:51
Hi @loburm ,  

1. LogName does have restrictions: see LogName field [here](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry). ` [LOG_ID] must be less than 512 characters long and can only include the following characters: upper and lower case alphanumeric characters, forward-slash, underscore, hyphen, and period.` This is implemented [here](https://github.com/googleapis/google-cloud-go/blob/43314b8a54eed1a5d50fa2b571a331b7b2c33c59/logging/logging.go#L439).

2. If you mean that users should be able to change the LogName while writing logs with the same logger instance, then that is not intended behavior. Users shouldn't be able to change LogName within entries written with the same logger. If this is the intended effect, we recommend you create a new logger instance. 

3. Thanks for pointing out that gap in Ruby. It's not maintained by any teams right now, and should probably be updated to patch that gap.

**Comment by nicoleczhu** [comment] 2021-02-22 23:24
I just saw your follow up question in #3720 . I'll close this one, since the other ticket seems to be the root cause.

**Closed by nicoleczhu** 2021-02-22 23:24 UTC
Labels: api: logging, priority: p2, type: question

**Comment by loburm** [comment] 2021-02-23 10:53
@nicoleczhu 
There is a huge difference in between setting logName on Entry level and on Logger level:

1. That's an artificial limitation of provided API. I have checked a few other client libraries and they allow to set logName on entry level: [c#](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/master/logging/api/QuickStart/QuickStart.cs#L41), [java](https://github.com/googleapis/java-logging/blob/master/samples/snippets/src/main/java/com/example/logging/QuickstartSample.java#L53).
2. For me logName seems to be similar to commonLabels and commonResource. We can set it on request level and/or entry level.
3. Using separate logger for each log name, means that we are going to use more CPU and bigger amount of logging quota.

> This was an intentional design decision at the client library level since additional features will build on assuming logger instances have 1 logName.

Could you share this data. I wonder what was the tradeoff

> This is the case in Node as well.

Do you mean NodeJs here or something else?

> Thanks for pointing out that gap in Ruby. It's not maintained by any teams right now, and should probably be updated to patch that gap.

I'm afraid that it can break existing customers of Ruby library.

**Comment by loburm** [comment] 2021-02-23 10:56
> I just saw your follow up question in #3720 . I'll close this one, since the other ticket seems to be the root cause.

I think this is unrelated. I just used this limitation to easily reproduce a problem. But in overall it can happen with any other error returned from the code.

**Comment by nicoleczhu** [comment] 2021-02-23 17:58
It looks to be an intentional design decision by the library creator, in this case [here](https://github.com/googleapis/google-cloud-go/blob/43314b8a54eed1a5d50fa2b571a331b7b2c33c59/logging/logging.go#L621) by @jba. Thoughts?

Here's [Nodejs-logging's](https://github.com/googleapis/nodejs-logging/blob/74704b12f63edf2da51026fa57537f6e8ae6f191/src/log.ts#L867) similar behavior. afaik [Python](https://github.com/googleapis/python-logging) is the same. Node has additional logger methods like `getEntries` that actually rely on a single, consistent LogName. 

In terms of tradeoffs, I can see args for both sides: 
- `Allow Foo loggers to write Bar entries`: this to your point, gives users flexibility in a gray area that backend/product specs haven't defined. 
- `Foo loggers to only write Foo entries`: `log`, `logSync` is just a veneer layer introduced to give users helpful defaults, i.e. LogName. If users don't want it, they can always just call the underlying GAPIC function [here](https://github.com/googleapis/google-cloud-go/blob/66046da2a4be5971ce2655dc6a5e1fadb08c3d1f/logging/logging.go#L810) and achieve (2) and (3) of your points above.

Note: either way, our team needs to standardize behavior across the library languages. So other libraries will need to be updated.
