### ISSUE TITLE
pubsub: Expired ACKs for most of the time - wasting resources and time

### ISSUE THREAD

**Issue by marrrcin** [googleapis/google-cloud-go#1584] opened 2019-09-17 17:02 UTC
(delete this for feature requests)

## Client

PubSub, latest version in Go.
From Gopkg.lock:
```
[[projects]]
  digest = "1:cab4bd3c2a4dfa2a4a04c72db04fb47dfcffdd55e131fcf0a81ff5379b07d181"
  name = "cloud.google.com/go"
  packages = [
    ".",
    "compute/metadata",
    "iam",
    "internal",
    "internal/optional",
    "internal/trace",
    "internal/version",
    "pubsub",
    "pubsub/apiv1",
    "pubsub/internal/distribution",
    "storage",
  ]
  pruneopts = "UT"
  revision = "264def2dd949cdb8a803bb9f50fa29a67b798a6a"
  version = "v0.46.3"
```

## Describe Your Environment

Docker container based on `golang:1.12.6-alpine3.10` running in GKE.

## Setup
I have published ~500k messages to PubSub, each message is JSON of size ~ 400-500 bytes. Subscription deadline is 10min.

Now, I launch go pubsub client with the configuration as follows:

```go
ctx := context.Background()
pubsubClient, err := pubsub.NewClient(ctx, settings.ProjectId)
subscriber := pubsubClient.Subscription("not-relevant")
maxWorkers := 4
subscriber.ReceiveSettings.NumGoroutines = maxWorkers
subscriber.ReceiveSettings.MaxOutstandingMessages = maxWorkers
subscriber.ReceiveSettings.MaxOutstandingBytes = maxWorkers * 512

err = subscriber.Receive(ctx, func(ctx context.Context, m *pubsub.Message) {
	defer m.Ack()
         // do something, on average it takes 500ms, never more than 5 seconds
})
```

## Expected Behavior
At most 4 parallel go routines are processing the messages, **pulling at most 4 messages at a time from PubSub**. OR **keeping only 4 * 512B stand-by messages in memory** All messages are processed properly with ACKs in-time.

## Actual Behavior
I suspected that my callback will be called in at most 4 parallel go routines and it actually is. The problem is that messages are processed in inconsistent rate and after 10min (coincidence? I don't think so! ), metrics show that most of messages that are processed result with **expired ACK** and the processing is stuck in a loop with old messages, yielding my processing a waste of time and resources.
Moreover, you can see spikes in the _StreamingPull Operations_. Those spikes happend when my container was deployed to the cluster (with the exact configuration showed above). How do the `MaxOutstandingBytes` and `MaxOutstandingBytes` parameters influence processing? The documentation for those parameters leaves much to be desired.

**GREEN** is expired ACK, ORANGE is valid ACK
<img width="687" alt="Screenshot 2019-09-17 at 18 52 39" src="https://user-images.githubusercontent.com/6958772/65062885-544d4400-d97d-11e9-92ad-8ec5980531f1.png">

**This is such a trivial case, why the go library makes it so difficult to implement?**

**Comment by hongalex** [comment] 2019-09-17 22:39
Thanks for bringing this to our attention! Definitely, the documentation around `MaxOutstandingMessages` and `MaxOutstandingBytes` require work. It sounds like what you are experiencing is actually "intended" behavior, albeit confusing. With streaming pull (using the default `ReceiveSettings.Synchronous=false`), `MaxOutstandingMessages` tells the client to stop pulling after that many messages (or more) are received. If your publish batch is too high (in this case 500k) messages, the client will pull a large number of those all at once, and then pause. Since your numGoroutines will only handle 4 at a time, a large number of messages will inevitably expire.

If you're processing a large number of messages at once, you will need to use `ReceiveSettings.Synchronous = true`. This uses a different RPC that can actually specify how many messages to pull, such that you only pull `MaxOutstandingMessages` at a time. Can you try that to see if that fixes it?

**Comment by hongalex** [comment] 2019-09-23 20:16
Closing for now. Feel free to reopen if the issue isn't solved after setting `ReceiveSettings.Synchronous = true`.

**Closed by hongalex** 2019-09-23 20:16 UTC
Labels: api: pubsub, type: docs

**Comment by marrrcin** [comment] 2019-09-24 07:02
OK, so I've tested the approach with `Synchronous=true` and it seems to work. Now I just spawn a few goroutines with `Synchronous=true` and `MaxOutstandingMessages=1` and the behaviour is predictable, ACKs are not timing out. Thanks!

**Comment by hongalex** [comment] 2019-09-24 22:49
Glad that worked. You can probably set `MaxOutstandingMessages` to a higher value without worrying about messages expiring. In synchronous mode, the client will pause once `MaxOutstandingMessage` are in memory (aka waiting to be processed).

**Comment by marrrcin** [comment] 2019-09-25 06:52
OK, will do!

**Comment by epsniff** [comment] 2020-05-06 20:10
@hongalex regarding your comment:
```
the client will pull a large number of those all at once and then stop. Since your numGoroutines is set to 4, a large number of messages will inevitably expire.
```
Will the iterator's keep-alive process keep these messages alive until `ReceiveSettings.MaxExtension` is reached?   That is, would an alternative be to increase the `MaxExtension` time?

**Comment by hongalex** [comment] 2020-05-06 23:17
@epsniff Yeah, we actually call that "automatic lease extension", aka managing messages that have been pulled by the client library. While increasing `MaxExtension` will help alleviate the issue to a certain extent, if you are consistently pulling a large number of messages, it's likely your subscribers might get overwhelmed. In that case, it is recommended to increase the number of subscriber clients processing messages.

Alternatively, if you expect spikes in message publishing, it is also recommended to break up publish batches (by decreasing the publish settings thresholds), so that the messages can be distributed across subscriber clients more efficiently.

**Comment by ajroetker** [comment] 2020-05-07 16:42
@hongalex we (@epsniff and I) also seem to see much bigger spikes in this issue when the subscription has a significant backlog, are the the sizes of batches affected by backlogs on the server side?

**Comment by ajroetker** [comment] 2020-05-07 16:49
@hongalex Also we let the go client do the batching for us, is their a way to set the publish threshholds in the publisher client?

**Comment by hongalex** [comment] 2020-05-07 21:29
> are the the sizes of batches affected by backlogs on the server side?

Generally, the size of a batch is the same as the way it is published. So if you are publishing in batches of 1k, you will receive batches of 1k with Streaming Pull.

> ideally we should see much more than 5000 messages locally in our clients correct?

If MaxOutstandingMessages is 3000 and your publish batches are smaller in size, you should only have 3000 messages across subscriber clients. Could you explain why you think you need more than 5000 messages?
