### ISSUE TITLE
compute/apiv1: Protobuf file is too big

### ISSUE THREAD

**Issue by PumpkinSeed** [googleapis/google-cloud-go#7845] opened 2023-04-27 10:05 UTC
I started to work with the compute apiv1 package, but it's really hard to develop on top of it, because the [computepb](https://github.com/googleapis/google-cloud-go/blob/main/compute/apiv1/computepb/compute.pb.go) file is huge. Most of the IDEs or even the pkg.dev itself can't index it. 

It would be way more easy to work with this package if this file would be broken into smaller spices so these tools can index it.

**Comment by quartzmo** [comment] 2023-04-27 19:15
@PumpkinSeed Thank you for posting this issue. I'll investigate whether there is any way to improve this.

**Comment by noahdietz** [comment] 2023-05-01 18:57
Unfortunately, this is code generated by protobuf-go, and the practice is one `.proto` file -> one `.go` file. I'm fully aware that the `compute.proto` is massive, GitHub can't open it without locking your browser. But if we break this proto file up, a difficult task in and of itself, that would be a breaking change for some of the other languages we generate stubs for.

I'm not sure that there is anything we can do here outside of bespoke post-processing of the generated code (separating it into files somehow). This would be a pretty precarious process, that would likely result in more bugs.

**Comment by PumpkinSeed** [comment] 2023-05-04 13:59
Yes, I could imagine that is hard. The only one thing what comes into my mind to have a specific extension for a forked version of the Go's proto generator where you can define destination files. But it's a bit overhead.

What do you think, will this be solved in the future (at any time), or is it too big change so it will remain as it is?

**Comment by noahdietz** [comment] 2023-05-04 17:49
The problem is definitely one that is worth fixing, but I don't think there will be a one-shot solution, because the various ways the problem manifests are based on different aspects of the "it's too big" issue. For example, GoDoc represents the entire package so splitting up `.go` files doesn't help, whereas GitHub/code editors refusing to open such a large file would be resolved by splitting up files.

Splitting up the _package_ is obviously a breaking change, so we'd need to do some aliasing, release coordination magic, and then everyone has to fix their code at some point. And this adds to the complexity of the code generation/maintenance (but I'd rather pay that price if it means folks can actually consume compute in all of these different venues). 

All this to say, I don't think this will be solved soon, but it is something we can endeavor to start chipping away at. I think the first thing to do is enumerate each of the places where "it's too big" causes usability problems, and identify the root cause of that (file size vs. package size).

**Closed** 2023-05-05 18:15 UTC
Labels: type: feature request, api: compute

**Comment by quartzmo** [comment] 2023-05-05 18:21
Please re-open if there is anything actionable for the maintainers of this project. As explained above, however, I believe any possibility for a solution rests with the compute product team.
