### ISSUE TITLE
pubsub: so slow when publish message

### ISSUE THREAD

**Issue by okisetiawan0101** [googleapis/google-cloud-go#1961] opened 2020-04-29 04:09 UTC
Hi I am new with google pubsub, why so slow when publish message to topic? Sometime it only takes 20-30ms, but sometimes can takes 200 ms - 1 second. I am using docker on GKE.
There is something wrong in my code?
I don't know how to solve it. Please help me

**Environment**
golang:1.13.1 Docker on GKE
cloud.google.com/go/pubsub v1.3.1

**Code**

```go
package publisher

import (
        "google.golang.org/api/option"
	"cloud.google.com/go/pubsub"
	"context"
	"errors"
	"google.golang.org/api/option"
	"fmt"
	"time"
)

type Publisher struct {
	Client *pubsub.Client
	Topic  *pubsub.Topic
	config Config
}

func (pub *Publisher) initClient(ctx context.Context, project string, opts ...option.ClientOption) error {
	pubSubClient, err := pubsub.NewClient(ctx, project, opts...)

	if err != nil {
		return err
	}
	pub.Client = pubSubClient

	return nil
}

func (pub *Publisher) initTopic(ctx context.Context, topic string) error {
	pubTopic := pub.Client.Topic(topic)

	if isExist, err := pubTopic.Exists(ctx); err != nil {
		return err
	} else if !isExist {
		return errors.New("Topic " + topic+ " is not exists in this project")
	}

	pub.Topic = pubTopic

	return nil
}

func InitializeWithConfig(project string, topic string, opts ...option.ClientOption) (*Publisher, error) {
	var ctx = context.Background()
	pub := Publisher{
		config: config,
	}

	if err := pub.initClient(ctx, project, opts...)); err != nil {
		return nil, err
	}

	if err := pub.initTopic(ctx, topic); err != nil {
		return nil, err
	}

	return &pub, nil
}

func (pub *Publisher) Publish(msg string, eventAttr map[string]string) (*string, error) {
	var ctx = context.Background()

	result := pub.Topic.Publish(ctx, &pubsub.Message{
		Data:       []byte(msg),
		Attributes: eventAttr,
	})

	id, err := result.Get(ctx)
	if err != nil {
		return nil, err
	}

	return &id, nil
}

func main() {
       pub, err := InitializeWithConfig("project-name","topic-name",option.WithGRPCConnectionPool(10))

	if err != nil {
		return err
	}
      
       startAt := time.Now()
       _, err := pub.Publish("testing", nil)

	duration := time.Now().Sub(startAt).Milliseconds()
	fmt.Printf("%vms", duration)

}

```

**Comment by hongalex** [comment] 2020-04-29 22:24
I think the main thing is that you're measuring individual publish latencies without batching. If your `Publish` method is not called from a goroutine, the `result.Get` method blocks until that message has successfully published, and therefore message batching is not happening. Each individual publish RPC has latency involved, so batching together should help with latency.

With that said, Pub/Sub was designed for high volumes of messages, and guaranteeing low latency is on a best-effort basis. I would look at the 99th percentile of publish latencies to see if you're consistently getting >200ms latency. To do so, look at the opencensus metrics we expose: https://github.com/googleapis/google-cloud-go/blob/25803d86c6f5d3a315388d369bf6ddecfadfbfb5/pubsub/trace.go#L59

Since I don't think there is a regression of the client library, I'll close this issue but feel free to comment if you disagree and I'll reopen.

**Closed by hongalex** 2020-04-29 22:24 UTC
Labels: api: pubsub, type: question

**Comment by winjeg** [comment] 2023-01-03 11:33
Same problem. And didn't get solved.
