### ISSUE TITLE
pubsub: native OpenTelemetry support

### ISSUE THREAD

**Issue by ianonavy** [googleapis/google-cloud-go#4665] opened 2021-08-24 01:18 UTC
cc @aabmass

**Is your feature request related to a problem? Please describe.**
As developer using PubSub via the Golang client lib, I would like to propagate OpenTelemetry span contexts via messages so that I can better understand the entire lifecycle of a message.

**Describe the solution you'd like**
I would expect a working solution to look similar to the [NodeJS implementation](https://github.com/googleapis/nodejs-pubsub/pull/1078).

Maybe something like this?

```golang
client, _ := pubsub.NewClientWithConfig(ctx, PROJECT_ID, pubsub.ClientConfig{
    OpenTelemetryEnabled: true,
})
```

Then I would expect the result to look something like this when configured with a Cloud Trace exporter:

![Screenshot of trace waterfall showing spans across publisher and consumer](https://miro.medium.com/max/688/1*QDbHoSvE7xrtd-nnWErsew.png)

Image is from [this article](https://medium.com/google-cloud/integrating-opentelemetry-into-cloud-pub-sub-19aacd83692a) by the former intern who implemented the NodeJS and Python versions of this request.

**Describe alternatives you've considered**
[OpenTelemetry-OpenCensus Bridge](https://pkg.go.dev/go.opentelemetry.io/otel/bridge/opencensus) would be great if PubSub were already instrumented to propagate OpenCensus spans through messages like this, but unfortunately the behavior I describe is orthogonal to the [existing issue](https://github.com/googleapis/google-cloud-go/issues/4237) to port the existing tracing from OpenCensus to OpenTelemetry.

**Comment by hongalex** [comment] 2021-08-24 04:29
Hiya,

Thanks for filing this issue. OT tracing support is definitely something that's on our roadmap and we're actively planning to support this. At the moment, it's mostly blocked on standardization across Pub/Sub client library languages and [waiting on the Go implementation for 1.0](https://github.com/orgs/open-telemetry/projects/15). I'll post here for updates.

Also appreciate the detail info. If you have specific asks or features you want, I'd be happy to relay them to the rest of the client library maintainers while we work on this.

**Comment by hongalex** [comment] 2021-09-22 19:29
Hey! Yeah we (myself and the Node library maintainer) are in contact with @aabmass. Yeah, that's one of the few things that we're trying to standardize though we're not 100% sure how we're going to fix that for Node since it's already released. We're discussing the merits of making a breaking change/major version bump or just supporting both attributes.

Among the other things is what parts of the publishing/subscribing we want to trace (and what the end result should look like). We kind of have an idea about this from the Node implementation, but it seems like [it might have issues](https://github.com/googleapis/nodejs-pubsub/issues/1389). I'll start hacking away at draft PR in Go and ask for feedback there if you're willing to help with that!

**Comment by Mistic92** [comment] 2022-09-01 12:58
Hi, what is the current status of that feature?

**Comment by jjmengze** [comment] 2022-10-13 09:23
Ho folks , is there any news?
very Very excited to google support otel

**Comment by billinghamj** [comment] 2023-02-10 17:20
What is the situ here, given https://github.com/googleapis/google-cloud-go/pull/5034#issuecomment-1142720342? If we want to keep a consistent trace across all messages, is GCP going to prevent that?

**Comment by jjmengze** [comment] 2023-04-04 09:32
is there any updated?

**Comment by quzhi1** [comment] 2023-04-04 17:46
I wrote a blog about how to enable tracing in Google PubSub. Basically you need to wrap tracing information inside message attribute. This is the link to my blog: https://www.nylas.com/blog/distributed-tracing-with-opentelemetry/. Search for "Tracing PubSub" and you will find my helper functions.

**Comment by zwolsman** [comment] 2023-09-01 12:58
Is there any update as of when this will be picked up again/available? 😄

**Comment by swordli-dev** [comment] 2023-10-20 06:53
Any update here? Seems this requirement is strong.

**Comment by mhv666** [comment] 2024-02-13 14:51
Same question here, any plans to implement it? 🙇🏽 Thanks

**Comment by hongalex** [comment] 2024-03-13 23:59
Thanks for the patience on this. We're still working out a few kinks, but if you would be interested in trying out this, it is available to try out as a beta release. This can be done by running `go get cloud.google.com/go/pubsub@v1.37.0-beta.otel.trace`.

Official documentation is still pending, but you should be able to see traces once you do the following

1) Instantiate an exporter + tracer provider ([Cloud Trace exporter example](https://cloud.google.com/trace/docs/setup/go-ot))
2) On Pub/Sub client instantiation, set the client config [`EnableOpenTelemetryTracing`](https://pkg.go.dev/cloud.google.com/go/pubsub@v1.37.0-beta.otel.trace#ClientConfig) to true.

Each message is given its own trace, from publish to subscribe. Batch RPC spans (publish, ack, modack) will live in their own traces, but durations can be viewed on the message trace via span events.

<img width="1130" alt="image" src="https://github.com/googleapis/google-cloud-go/assets/9397363/8430a811-6db5-4b50-9d51-e96823fb42ac">

While we are close to launching this feature, we welcome any feedback.

**Comment by billinghamj** [comment] 2024-03-15 12:18
@hongalex Could you clarify how the new support connects with this? https://github.com/googleapis/google-cloud-go/pull/5034#issuecomment-1142720342

Has your thinking changed? Are there best practices or suggested options you have in mind?

**Comment by hongalex** [comment] 2024-03-15 17:58
The main change is that we are now relying more heavily on links. The design at the time of the previous comment duplicated batch RPC spans to every single message trace. So if you make a publish RPC call with 10 messages in it, then each message trace will contain a copy of the publish RPC span. Now, that span exists in its own trace, and is linked to each message trace it is affiliated with. In addition, in each message trace, we added span events to say how long the RPC took.

There were some span name changes and attribute changes that were made with updated [messaging semantic conventions](https://opentelemetry.io/docs/specs/semconv/messaging/messaging-spans/) in mind. This is still an evolving standard so we reserve the right to make breaking changes to things like spans, span names, attribute names, and links.

**Comment by jameshartig** [comment] 2024-04-09 14:52
One issue I noticed is that the parent's context is not being used in the `ack` spans so you send up missing some of the `ack` spans if you are sampling. We use `trace.ParentBased` as a sampler so if the parent is sampled all of the children are sampled but the problem is that when `startSpan` is called for the `ack` spans it uses a new context rather than using the context from the parent span.

**Comment by jameshartig** [comment] 2024-04-09 15:04
I left a few comments on the PR, we ran this in production for a while but quickly noticed memory leaks, I believe from the `activeSpans` map.

**Comment by hongalex** [comment] 2024-04-10 00:54
> One issue I noticed is that the parent's context is not being used in the ack spans so you send up missing some of the ack spans if you are sampling

This is unfortunately intentional. The short story is that batched spans (like ack) have multiple parents, so it cannot solely rely on parent/child relationships and why I gave it a new context. Instead, batched spans live in their own trace and are linked to the main message trace. I plan to add a new option to link back from message trace -> batched ops traces.

> I left a few comments on the PR, we ran this in production for a while but quickly noticed memory leaks, I believe from the `activeSpans` map.

Thanks for the comments. Fixed the memory leak issues (and others) and cut another release under `cloud.google.com/go/pubsub@v1.37.0-beta.otel.trace2`

**Comment by tcnghia** [comment] 2024-06-04 16:35
@hongalex do you have an estimated timeline for the launch of this feature? 

Also, do you plan to cut regular releases following the main versions (1.38.0 now)?

Thanks a lot!

**Comment by hongalex** [comment] 2024-08-19 23:15
Thanks all for your patience. This feature is now released as part of `cloud.google.com/go/pubsub@v1.42.0`

Please use the issue tracker for any problems you may notice while enabling tracing.

As a reminder, tracing is GA, but span names, attributes, links, and other parts of the trace are subject to change as we align with OpenTelemetry semantic conventions messaging standards.

**Closed by hongalex** 2024-08-19 23:15 UTC
Labels: type: feature request, api: pubsub
