### ISSUE TITLE
pubsub: excessive connection open events 

### ISSUE THREAD

**Issue by nsf** [googleapis/google-cloud-go#1671] opened 2019-11-19 15:48 UTC
## Client

pubsub (valid for master at the moment of a report)

## Describe Your Environment

Doesn't matter much in this case but it's a GKE container, debian based.

## Expected Behavior

Google Pubsub API has harsh quotas on establishing connections, on our project it's 900 open connections per minute, I believe the default is even less? Don't remember. Okay, what happens is this. With growing amount of subscriptions we started to observe quota limit violations (causing ResourceExhausted errors). In case I wasn't clear about the quota I'm talking about here's the image:

![image](https://user-images.githubusercontent.com/12567/69161023-4f874680-0b0c-11ea-898a-a829f478c9d2.png)

So, after that I registered stackdriver views from google's pubsub client and quickly noticed something:

![image](https://user-images.githubusercontent.com/12567/69161146-7e9db800-0b0c-11ea-8d42-95f91d1b89ef.png)

The stream_open_count pretty much matches stream_request_count. Which implies there is absolutely no connection reuse. Further investigation confirmed that. I added printf logging to the pubsub client lib and it showed that in this particular case we have a client listening for 100-200 subscriptions, however most of them do not spawn messages and what I saw is excessive amount of "Unavailable" errors happening every 2 minutes or so on Recv calls. Quick glance at other client libs such as nodejs one showed that they send "keepalive" empty requests unconditionally every 30 seconds, while Go client does this:
https://github.com/googleapis/google-cloud-go/blob/5300cb932852d14c4abc256b2ae31fefb5f56b6e/pubsub/iterator.go#L318

And this indeed was confirmed by custom logging mentioned above in the client lib, I saw no "Send" requests whatsoever. Not sure exactly when `len(it.keepAliveDeadlines) > 0` is true, maybe when given subscription is under some load and actively processing pubsub messages, but in our case messages come very rarely, but there is a lot of subs. Anyways, long story short, removing second part of the condition above, e.g.

```go
sendPing = !it.po.synchronous // && (len(it.keepAliveDeadlines) > 0)
```

Changes the picture to this:

![image](https://user-images.githubusercontent.com/12567/69161680-58c4e300-0b0d-11ea-8c43-7f73349d59ad.png)

Which is expected. Sure there is keepalive send requests now, but the amount of connection open events is down to zero as it should be.

## Actual Behavior

Excessive connection opens in the pubsub client.

## Thoughts

I believe Go client should always send keepalive requests or maybe there should at least be an option to do so.

**Comment by nsf** [comment] 2019-11-20 12:21
I also want to add some additional info here. I tried to run this hack I mentioned above on all of our Go pubsub clients. And this changes the quota picture to this (we also increased quota from 900 to 10k):
![image](https://user-images.githubusercontent.com/12567/69238033-cf6aea80-0bb8-11ea-8c93-07985b036287.png)
Which is a bit surprising to me. As if the graph shows total open connections instead of open connections per minute. Could this be a bug too? With the hack however you can see that the graph becomes very stable, because reconnects almost never happen it's a straight line there.

And this is how stackdriver views look like:
![image](https://user-images.githubusercontent.com/12567/69238185-2f619100-0bb9-11ea-93d7-d38e083e5a11.png)

I thought the graph in API quotas roughly displays stream_open_count, but apparently it's something else. Well in the header it says "StreamingPull number of open connections" without (per minute) and there is another graph which is "StreamingPull open requests" which looks like this now:

![image](https://user-images.githubusercontent.com/12567/69238395-b0b92380-0bb9-11ea-8662-cca272391694.png)

So I'm a bit confused about it all. In any case the issue is still valid. Is too many reconnects a bad thing? Do these graphs represent what they should represent? If "open requests" is the open connection events, but "number of open connections" is the total number of connections, then quotas look weird. Bigger quota on first and smaller quota on second?

![image](https://user-images.githubusercontent.com/12567/69238515-0988bc00-0bba-11ea-8beb-e271f8b5a57a.png)

Hm, ok, sorry, I guess I misunderstood the quota graphs a bit, but never the less the issue is valid.

**Comment by hongalex** [comment] 2019-12-17 06:49
Thanks for opening this issue.

`len(it.keepAliveDeadlines) > 0` when the `keepAliveDeadlines` map isn't empty. Your hack means that we will always send a ping per tick, but I think we only really want to keep those streams open if there are active messages.

> Is too many reconnects a bad thing? 

Not necessarily. Closing a stream and reconnecting might be better than keeping an idle stream open while waiting for resources. This differs in Go compared to other libraries such as Node (as you mentioned) which prefers [keeping a certain number of streams open at once](https://github.com/googleapis/nodejs-pubsub/blob/master/src/message-stream.ts#L205-L215)

> Do these graphs represent what they should represent? If "open requests" is the open connection events, but "number of open connections" is the total number of connections, then quotas look weird. Bigger quota on first and smaller quota on second?

This is a bit strange. I believe the graphics are correct, but I agree the wording on the quotas are a bit confusing. I'll investigate into this a bit more and get back to you.

Overall, it seems like the problem is specific to your use case where you have a lot of subscriptions without a lot of activity on each subscription. With that said, we can look into the possibility of modifying the client library behavior such that the frequency of the keepalive pings are exposed to the user. cc @kamalaboulhosn

**Comment by hongalex** [comment] 2020-01-15 00:12
Thanks for your patience. After some discussion with the maintainers of the other pub/sub client libraries, we agreed to keep the streams alive in Go as well (with a ping every 30 seconds). I'll be sending out a patch for this later this week.

**Comment by hongalex** [comment] 2020-01-25 01:22
[Sent out the change for this](https://code-review.googlesource.com/c/gocloud/+/50890), pending approval.

Regarding your second point, our quotas have been updated and now `Number of open StreamingPull connections` is the only limitation. The original limit of `Rate of StreamingPull connections` was an artifact of limitations we had before and has recently been removed.

**Closed** 2020-01-28 22:27 UTC
Labels: :rotating_light:, api: pubsub, priority: p1, type: bug
