### ISSUE TITLE
storage: ReadCompressed(true) doesn't work with NewReader

### ISSUE THREAD

**Issue by ihuh0** [googleapis/google-cloud-go#1743] opened 2020-01-23 04:17 UTC
**Client**

storage

**Expected behavior**

obj.ReadCompressed(true).NewReader(ctx) should return a reader of the compressed file with reader.Attrs.ContentEncoding = gzip.

**Actual behavior**

It returns a reader that reads the uncompressed data (same as just obj.NewReader(ctx)). On the contrary, obj.ReadCompressed(true).NewRangeReader(ctx, <some negative number>, -1) works in returning a reader for the entire compressed file with ContentEncoding=gzip.

**Comment by maruel** [comment] 2020-01-23 17:43
It was added in https://github.com/googleapis/google-cloud-go/commit/657767d66680dbb53f5e6bf677e37d88b221c31b.

It was moved in https://github.com/googleapis/google-cloud-go/commit/f2174aa3

and now lives in https://github.com/googleapis/google-cloud-go/blob/master/storage/reader.go#L122

Ref: https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L824

At first glance it should work (?)

**Comment by IlyaFaer** [comment] 2020-01-31 14:36
Could you provide a code snippet of how you're writing and reading the object?

I've tried a minimal write-read sample, and looks like it works fine:

![image](https://user-images.githubusercontent.com/26030071/73547040-43dec700-444f-11ea-8402-43578c3bdff3.png)

Is your file uploaded with `ContentEncoding` parameter? Omiting it will cause missing `Reader.Attrs.ContentEncoding`, no matter was uploaded file actually compressed or not.

Take a look at [the docs](https://cloud.google.com/storage/docs/transcoding#transcoding_and_gzip) for more details

**Comment by ihuh0** [comment] 2020-01-31 16:29
I have something like this:

`obj := bucket.Object(name)
w := obj.If(storage.Conditions{DoesNotExist: true}).NewWriter(ctx)
w.ContentEncoding = "gzip"
gz := gzip.NewWriter(w)
r := os.Open(path)
defer r.Close()
io.Copy(gz, r)
gz.Close()
w.Close()
...

r, err := obj.ReadCompressed(true).NewReader(ctx)`

One thing I notice that is different is that I don't set the Content Type, but it shows up as application/x-gzip. Does that matter?
Also, can you check the size of the reader (see how many total bytes it reads)? I was mainly checking the size and saw that it was matching the size of the uncompressed data, not the compressed size.

**Comment by gWOLF3** [comment] 2020-01-31 19:35
^^^ Yes. I am also noticing this! The size returned is the size of uncompressed file, not compressed. This is why my proxy is breaking and my browser is unable to lead files with 'content-type: gzip'.  

On further investigation, it appears the file is actually being unzipped when it is read. This explains why the size returned is the uncompressed size! I also tested this to confirm.

**Comment by gWOLF3** [comment] 2020-01-31 19:58
BTW - I also made sure I have 'readCompressed' set to true. It is still getting uncompressed somewhere.

**Comment by gWOLF3** [comment] 2020-01-31 20:02
Also, when I remove the content-encoding 'gzip' from the metadata in my storage bucket, it no longer gets decompressed. I have looked into the auto transcoding docs - here https://cloud.google.com/storage/docs/transcoding - however, I have tried forcing the cache control and so it appears the decompression is happening on the google-cloud-go storage client itself, rather than being transcoded by the server.

**Comment by gWOLF3** [comment] 2020-01-31 20:22
Alright, final comment, after setting the readCompressed to true - it actually appears to be working. 
With one caveat - the size attribute is still showing the original file size, rather than compressed, this causes problems with transferring to browser/curl client. To get it to work, I had to strip the content-length header.  This still not optimal, since content length header still important for viewing and loading videos.

**Comment by IlyaFaer** [comment] 2020-02-03 08:11
> One thing I notice that is different is that I don't set the Content Type, but it shows up as application/x-gzip. Does that matter?

Well, according to the docs, both `Content-Type` and `Content-Encoding` should be included. See [Discouraged practices](https://cloud.google.com/storage/docs/transcoding#discouraged_practices), it explaines why

**Comment by frankyn** [comment] 2020-02-03 21:59
Hi folks,

Providing additional context on what's happening here. In short, it's an issue with the GCS API and following-up with the team. 

## Case (contentEncoding: gzip):

As both of you have noticed `contentEncoding: gzip` will cause GCS to decompress on download even when `ReadCompressed(true)`.
The reason for this is due to the contentType determined by the [Go GCS Client](https://github.com/googleapis/google-api-go-client/blob/ea23fcfb64502314af81a20f741b74b246e4197b/internal/gensupport/media.go#L58-L74) being `contentType: application/x-gzip`. 

When `ReadCompressed(true)` is set, the client will send HTTP Header `Accept-Encoding: gzip` to notify GCS API that the client will decompress the contents. However, GCS API is ignoring this and still decompressing the contents due to the ContentType. I believe this is a bug and will follow-up.

## Failure Reproduction Example Code

```golang
package main

import (
	"context"
	"io"
	"io/ioutil"
	"log"
	"os"

	"cloud.google.com/go/storage"
      "compress/gzip"

)

func main() {
	ctx := context.Background()

	// Creates a client.
	client, err := storage.NewClient(ctx)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}

	// Sets the name for the new bucket.
	bucketName := "bucket-name"
	objectName := "small.txt"

	obj := client.Bucket(bucketName).Object(objectName)
	w := obj.NewWriter(ctx)
	w.ContentEncoding = "gzip"
	gz := gzip.NewWriter(w)

	r, _ := os.Open("small.txt")
	defer r.Close()
	io.Copy(gz, r)

	gz.Close()
	w.Close()

	reader, _ := obj.ReadCompressed(true).NewReader(ctx)
        defer reader.Close()
	contents, _ := ioutil.ReadAll(reader)
	ioutil.WriteFile("small.txt_downloaded.gz", contents, 0644)
}
```

As noted by @IlyaFaer, you should instead provide the ContentType when uploading the gzip object with the decompressed ContentType or default content type `application/octet-stream` to stop the Go Client from auto-detecting the contentType. ([Discourage practices](https://cloud.google.com/storage/docs/transcoding#discouraged_practices))

## Workaround 1

```golang
package main

import (
	"context"
	"io"
	"io/ioutil"
	"log"
	"os"

	"cloud.google.com/go/storage"
      "compress/gzip"

)

func main() {
	ctx := context.Background()

	// Creates a client.
	client, err := storage.NewClient(ctx)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}

	// Sets the name for the new bucket.
	bucketName := "bucket-name"
	objectName := "small.txt"

	obj := client.Bucket(bucketName).Object(objectName)
	w := obj.NewWriter(ctx)
	w.ContentEncoding = "gzip"
        w.ContentType = "text/plain"
	gz := gzip.NewWriter(w)

	r, _ := os.Open("small.txt")
	defer r.Close()
	io.Copy(gz, r)

	gz.Close()
	w.Close()

	reader, _ := obj.ReadCompressed(true).NewReader(ctx)
        defer reader.Close()
	contents, _ := ioutil.ReadAll(reader)
	ioutil.WriteFile("small.txt_downloaded.gz", contents, 0644)
}
```

## Workaround 2
If you're dealing with many files and want to use a similar approach to auto-detect the content type of the decompressed data, you can do something similar to the following:

```golang
package main

import (
	"context"
	"io"
	"io/ioutil"
	"net/http"
	"log"
	"os"

	"cloud.google.com/go/storage"
  "compress/gzip"

)

func main() {
	ctx := context.Background()

	// Creates a client.
	client, err := storage.NewClient(ctx)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}

	// Sets the name for the new bucket.
	bucketName := "anima-frank"
	objectName := "small.txt"
	localFileName := "./small.txt"

	obj := client.Bucket(bucketName).Object(objectName)
	w := obj.NewWriter(ctx)

	// Read the first 512 bytes
        // This can be improved.
	r, _ := os.Open(localFileName)
	start, _ := ioutil.ReadAll(io.LimitReader(r, 512))
        r.Close()

        w.ContentType = http.DetectContentType(start)
	w.ContentEncoding = "gzip"

        // Reopen file for upload.
	r, _ = os.Open(localFileName)
	gz := gzip.NewWriter(w)

	defer r.Close()
	io.Copy(gz, r)

	gz.Close()
	w.Close()

	reader, _ := obj.ReadCompressed(true).NewReader(ctx)
	contents, _ := ioutil.ReadAll(reader)
	ioutil.WriteFile("small.txt.gz", contents, 0644)
}
```

**Comment by ihuh0** [comment] 2020-02-04 20:16
Got it, thank you for the clarification! I added the ContentType and it works as expected.

**Comment by frankyn** [comment] 2020-02-05 18:37
Great, I'll close this issue for now. Please reopen if things change. 

We are tracking this internally to clarify documentation around this edge case.

Thank you for filing this issue @ihuh0.

**Closed by frankyn** 2020-02-05 18:37 UTC
Labels: api: storage, priority: p2, type: bug
