### ISSUE TITLE
`civil`: unsuitable for use with BigQuery ingestion

### ISSUE THREAD

**Issue by mattmoor** [googleapis/google-cloud-go#6409] opened 2022-07-24 17:31 UTC
**Client**

The `civil.DateTime` type is unsuitable for use with BigQuery `DATETIME`.

These types are advertised for use with BigQuery, e.g.
https://github.com/googleapis/google-cloud-go/blob/a2ec33b1badb27a7ca139a9b4d90ebf86b588f11/civil/civil.go#L134-L136

**Environment**

BigQuery data transfer service ingesting newline-delimited JSON in GCS into BigQuery.

**Go Environment**

Go 1.18

**Code**

The relevant code is where we want to use `civil.DateTime` for a field type so that we get the appropriate JSON encoding for BigQuery to ingest the field as `DATETIME`:

```go
type Record struct {
   ...
	StartedAt          *civil.DateTime `json:"startedAt,omitempty"`
	FinishedAt         *civil.DateTime `json:"finishedAt,omitempty"`
   ...
}
```

**Expected behavior**

I would expect this type to serialize into a form compatible with `DATETIME` as described [here](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#timestamp_type), in particular:
> [.F]: Up to six fractional digits (microsecond precision)

**Actual behavior**

Instead of microsecond precision, the types are encoded with nanosecond precision here: https://github.com/googleapis/google-cloud-go/blob/a2ec33b1badb27a7ca139a9b4d90ebf86b588f11/civil/civil.go#L173

This results in errors like this when BigQuery attempts to ingest these as `DATETIME`:
```
Invalid datetime string "2022-07-23T02:37:52.032499000"
Field: start_time; Value: 2022-07-23T02:37:52.032499000
```

**Comment by mattmoor** [comment] 2022-07-24 17:32
I'd be happy to send a PR, but wanted to start with an issue describing the problem.

**Comment by mattmoor** [comment] 2022-07-24 17:50
Ok, I optimistically sent a PR, but I'd be happy to change things if there's an alternate approach folks would rather see here.

**Comment by quartzmo** [comment] 2022-07-25 18:15
Unfortunately, `civil.Time` is also used in [cloud.google.com/go/datastore](https://pkg.go.dev/cloud.google.com/go/datastore) and [https://pkg.go.dev/cloud.google.com/go/spanner](https://pkg.go.dev/cloud.google.com/go/spanner).

**Comment by quartzmo** [comment] 2022-07-25 18:25
Correction, it appears that only `civil.Date` is used in the spanner library, but `civil.Time` is used in Datastore here in [load.go](https://github.com/googleapis/google-cloud-go/blob/main/datastore/load.go#L393).

I suppose it's possible that the nanosecond precision could also be a bug for Datastore, but if not, truncating it might be a breaking change for users, right?

**Comment by shollyman** [comment] 2022-07-25 21:08
Truncating the default representation seems a bit dodgy here, given the differing precision expectations of various consumers.  Possibly a formatter method on the type that specifies the truncation precision as an option?

It's not immediately clear how your interaction pattern works here, and whether this can be addressed elsewhere (such as within the bigquery package).  You mention ingesting GCS files via data transfer service, so I don't yet grok how you end up having to format values.  Are you reading the files from GCS in your code and then streaming them, rather than using DTS?  Or is this from reading values after ingestion via query?

**Comment by mattmoor** [comment] 2022-07-25 22:09
We have code that JSON serializes the Go structs and writes them into newline delimited files in GCS.  The BigQuery data transfer service goes from newline delimited JSON records in GCS -> BigQuery dataset with none of our code invoked.

We need a Go type that we can use for the initial JSON serialization that works with this, and TBH it's been a PITA.  I found this type and it seemed purpose built for this (as evidence by the comments), but it sadly doesn't work.

This PR is potentially breaking to certain cases due to loss of precision round-tripping through JSON, but that JSON is also fundamentally incompatible with BigQuery, which is an advertised use case.  I'd defer to y'all on how best to proceed here, but I think that you should either stop advertising this as compatible with BigQuery, or drop the precision so that it is.

**Comment by alvarowolfx** [comment] 2022-10-24 21:42
@mattmoor I was taking a look on this issue and indeed changing the `civil.DateTime` struct would break other packages here and I was looking for alternatives. There are two cases in which you can have a `DATETIME` fields, one for an optional field and another one for a required field. I'll give some solutions so you can still serialize data to GCS and read data from BQ using the same struct.

For the example here I'll use the `table.LoaderFrom` method to simulate how the DTS service consumes data.

Option 1: `DATETIME` field is optional. For this one, we have the type `bigquery.NullDateTime` that works perfectly for this case, as it already serialize the field to make it work with Bigquery ( with microsecond resolution )

```
type Record struct {
	Name       string       `json:"name"`
	StartedAt  bigquery.NullDateTime `json:"startedAt,omitempty"`
	FinishedAt bigquery.NullDateTime `json:"finishedAt,omitempty"`
}

func LoadTimestamps() {
	ctx := context.Background()	
        client, err := bigquery.NewClient(ctx, "project-id")
	if err != nil {
		log.Fatal(err)
	}
	schema, err := bigquery.InferSchema(&Record{})
	if err != nil {
		log.Fatal(err)
	}
	table := newTable(t, schema)
	defer table.Delete(ctx)

	wantRows := []Record{}
	buf = bytes.Buffer{}
	testDate       = civil.Date{Year: 2016, Month: 11, Day: 5}
	testTime       = civil.Time{Hour: 7, Minute: 50, Second: 22, Nanosecond: 8}
	optionalDateTime := bigquery.NullDateTime{
		DateTime: civil.DateTime{Date: testDate, Time: testTime},
		Valid:    true,
	}
	for i := 0; i < 3; i++ {
		rec := &Record{StartedAt: optionalDateTime, FinishedAt: optionalDateTime}
		wantRows = append(wantRows, *rec)
		content, err := json.Marshal(rec)
		if err != nil {
			log.Fatal(err)
		}
		buf.Write(content)
		buf.WriteString("\n")
	}
	// Load the table from a reader.
	r := bytes.NewReader(buf.Bytes())
	rs = NewReaderSource(r)
	rs.SourceFormat = bigquery.JSON
	loader = table.LoaderFrom(rs)
	loader.WriteDisposition = WriteTruncate
	job, err = loader.Run(ctx)
	if err != nil {
		log.Fatalf("loader.Run: %v", err)
	}
	if job.LastStatus() == nil {
		log.Fatal("no LastStatus")
	}
	if err := wait(ctx, job); err != nil {
		log.Fatalf("wait: %v", err)
	}
	it := table.Read(ctx)
	i := 0
	for {
		var r Record
		err = it.Next(&r)
		if err == iterator.Done {
			break
		}
		if err != nil {
			log.Fatalf("it.Next: %v", err)
		}
		if !testutil.Equal(r, wantRows[i]) {
			log.Fatalf("#%d: got %#v, want %#v", i, r, wantRows[i])
		}
		i++
	}
}

// wait polls the job until it is complete or an error is returned.
func wait(ctx context.Context, job *Job) error {
	status, err := job.Wait(ctx)
	if err != nil {
		return fmt.Errorf("job %q error: %v", job.ID(), err)
	}
	if status.Err() != nil {		
		return fmt.Errorf("job %q status error: %#v", job.ID(), status.Err())
	}
	if status.Statistics == nil {
		return fmt.Errorf("job %q nil Statistics", job.ID())
	}
	if status.Statistics.EndTime.IsZero() {
		return fmt.Errorf("job %q EndTime is zero", job.ID())
	}
	return nil
}
```

Option 2: For a required `DATETIME`. In this case indeed the `civil.DateTime` would not fit for serializing data, but we can override the `MarshalJSON` method and use the helper method `bigquery.CivilDateTimeString` to serialize it with the proper resolution. 

```
type Record struct {
	Name       string         `json:"name"`
	StartedAt  civil.DateTime `json:"startedAt,omitempty"`
	FinishedAt civil.DateTime `json:"finishedAt,omitempty"`
}

func (r Record) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		Name       string `json:"name"`
		StartedAt  string `json:"startedAt"`
		FinishedAt string `json:"finishedAt"`
	}{
		Name:       r.Name,
		StartedAt:  CivilDateTimeString(r.StartedAt),
		FinishedAt: CivilDateTimeString(r.FinishedAt),
	})
}

func LoadTimestamps(t *testing.T) {
	ctx := context.Background()
	schema := Schema{
		{Name: "name", Repeated: false, Required: true, Type: StringFieldType},
		{Name: "startedAt", Repeated: false, Required: true, Type: DateTimeFieldType},
		{Name: "finishedAt", Repeated: false, Required: true, Type: DateTimeFieldType},
	}
	table := newTable(t, schema)
	defer table.Delete(ctx)

	wantRows := []Record{}
	buf := bytes.Buffer{}
	estDate       = civil.Date{Year: 2016, Month: 11, Day: 5}
	testTime       = civil.Time{Hour: 7, Minute: 50, Second: 22}
	testDateTime := civil.DateTime{Date: testDate, Time: testTime}
	for i := 0; i < 3; i++ {
		rec := &Record{StartedAt: testDateTime, FinishedAt: testDateTime}
		wantRows = append(wantRows, *rec)
		content, err := json.Marshal(rec)
		if err != nil {
			log.Fatal(err)
		}
		buf.Write(content)
		buf.WriteString("\n")
	}
	// Load the table from a reader.
	r := bytes.NewReader(buf.Bytes())
	rs := NewReaderSource(r)
	rs.SourceFormat = JSON
	loader := table.LoaderFrom(rs)
	loader.WriteDisposition = WriteTruncate
	loader.Labels = map[string]string{"test": "go"}
	job, err := loader.Run(ctx)
	if err != nil {
		log.Fatalf("loader.Run: %v", err)
	}
	if job.LastStatus() == nil {
		t.Error("no LastStatus")
	}
	if err := wait(ctx, job); err != nil {
		log.Fatalf("wait: %v", err)
	}
	it := table.Read(ctx)
	i := 0
	for {
		var r Record
		err = it.Next(&r)
		if err == iterator.Done {
			break
		}
		if err != nil {
			log.Fatalf("it.Next: %v", err)
		}
		if !testutil.Equal(r, wantRows[i]) {
			log.Fatalf("#%d: got %#v, want %#v", i, r, wantRows[i])
		}
		i++
	}
}
```

With both option, you can use the same struct for writing data to GCS like you need and read data from BigQuery directly. Let me know if that works for you.

**Comment by mattmoor** [comment] 2022-10-24 22:49
I understand y'all not wanting to take a breaking change here, so I closed my PR.  I don't need a solution here because I forked this code ~months ago to carry my patch, and it's been working great.

However, you folks still need a solution for the fact that you advertise `civil.DateTime` as suitable for use with BigQuery, when in fact is not suitable for use with BigQuery.  Needing to override `MarshalJSON` at the parent type because the field type does the wrong thing kinda sucks.  It would be better to create a type for the field with the appropriate `UnmarshalJSON` implementation and just use that, but at that point the user has ~reimplemented `civil.DateTime`.

See my original comment, but this line is going to continue to mislead users:
```
// This type exists to represent the TIME type in storage-based APIs like BigQuery.
```

**Comment by alvarowolfx** [comment] 2022-10-24 23:30
I understand your frustration and was trying to help with some solutions for your use case. The `bigquery` package has multiple working use cases for the `civil.DateTime` struct like:

* Inserting data using user defined structs with `table.Inserter`
* Inferring table schema with `bigquery.InferSchema`
* Reading/Unmarshall data from BQ into a user define struct directly with `table.Read`, `jobRead` and `query.Read`
* Typed parameters for a query with the `QueryParameters` type.

The problem that we are trying to solve here is when marshaling data to JSON to be consumed by another service ( in this case DTS and BigQuery ) and at the same time reuse the same struct later to read from BigQuery, which is a fair issue to be solved. 

From the code that you sent, as you're using a pointer to `civil.DateTime`, you can replace that with `bigquery.NullDateTime` and it should work as intended like I sent in the first example, without having to override `MarshalJSON`.  

If is not a pointer and the `MarshalJSON` on the second example is not a solution for your case, we would need define our own `DateTime` type and maintain both `civil.DateTime` and the new `bigquery.DateTime`, but that can be even more confusing to users which will not be sure which type to use. 

Having a new datatype with the `UnmarshalJSON` implementation is not a solution as the issue for parsing timestamps with nanosecond precision happens on the server side, not on the client side.

In any case, I'm checking internally if BigQuery has any timelines on supporting nanosecond precision timestamps or even receiving such data and dropping the resolution.

**Comment by mattmoor** [comment] 2022-10-24 23:39
LOL, I'm not frustrated, like I said I've been unblocked for months now.

I was simply highlighting that there's still a latent issue with the docs, which will burn folks like it burned me if taken at face value. The pointer trick is useful, but we have non-pointer versions as well, so as long as we have to keep our fork we may as well use it consistently.

**Comment by alvarowolfx** [comment] 2023-01-25 21:55
This is blocked by internal issue 143553831, which tracks support for nanosecond precision.

**Comment by alvarowolfx** [comment] 2024-05-15 19:32
Closing this issue as we provided options for marshalling datetimes within the BigQuery SDK context and we created issue #10183 to track nanosecond precision support.

**Closed by alvarowolfx** 2024-05-15 19:32 UTC
Labels: api: bigquery, priority: p3
