### ISSUE TITLE
all: switch from OpenCensus to OpenTelemetry

### ISSUE THREAD

**Issue by NeoCN** [googleapis/google-cloud-go#4638] opened 2021-08-18 10:39 UTC
Is there any plan to switch from OpenCensus to OpenTelemetry?

**Comment by codyoss** [comment] 2021-08-18 14:38
This seems like a dupe of #4237 so I will close out this issue. The implementations for most OpenTelemetry services are not yet stable. This is especially true in Go where tracing is currently still in RC, metrics are alpha, and logging does not exist. As the project matures over time we will continue to evaluate if it is right to integrate with it.

Source: https://opentelemetry.io/docs/go/

**Closed by codyoss** 2021-08-18 14:38 UTC
Labels: triage me

**Comment by mujtaba-ahmed12** [comment] 2022-12-16 10:15
@codyoss Is there any update on moving forward with this.
