### ISSUE TITLE
Client/server MD5 mismatch reported on retry of a canceled write

### ISSUE THREAD

**Issue by joshuaseaton** [googleapis/google-cloud-go#1625] opened 2019-10-17 21:44 UTC
Storage write logic is effectively as below.
Suppose we put a small timeout (e.g., say, 1s) on context and pass that to NewWriter(). The write is cancelled, and we retry the write: this errors out saying that the checksum is a mismatch. However, when I navigate to the cloud console (or verify on the commandline via gsutil), I see that
(1) the object did actually succeed in its upload (though I don't know if this was on the first write or the second); and
(2) the MD5 checksum is as expected!
Per (2) and the error reported on the retry, the client had an invalid view of the MD5 of the associated object and reported a spurious error.

Write logic:
```
w := bucket.Object(name).If(storage.Conditions{DoesNotExist: true}).NewWriter(ctx)
w.ChunkSize = chunkSize
w.MD5 = expectedChecksum
var err error
for {
  if _, err = io.CopyN(w, r, chunkSize); err != nil {
    break
  }
}
// EOFs and 412s are okay. 412s are okay as this routine might have
// lost a race with another routine that uploaded the associated
// object first, thus failing the above precondition.
if err != nil && err != io.EOF && !string.Contains(err.Error(), "Error 412") {  {
  w.Close()
  return err
}
return w.Close()
```

## Client

Storage

## Describe Your Environment

GCE instance
*cores*: 16
*cpu*: x64 | x86 | x86-64-Haswell_GCE | x86-64-avx2
*gpu*: none
*kvm*: true
*machine_type*: n1-standard-16
*os*: Debian | Debian-9.5 | Linux
*ssd*: true

**Comment by joshuaseaton** [comment] 2019-10-17 21:44
CC: @frankyn

**Comment by frankyn** [comment] 2019-12-13 22:39
Hi @joshuaseaton,

I attempted to reproduce this error but wasn't able to. I did the following and want to confirm that I'm following the pattern you described. Given a timeout of 1 second the request will exceed timeout.

Thank you for your patience.

```golang
package main

import (
	"context"
	"io"
	"strings"
	"bytes"
	"fmt"
	"time"
	"encoding/base64"
	"cloud.google.com/go/storage"
)

func write_test_file(ctx context.Context) {
	// Creates a client.
	client, err := storage.NewClient(bctx)
	if err != nil {
		fmt.Errorf("Error: %v", err)
	}
	bucketName := "anima-frank"
	objectName := "anima-frank-new-object-does-not-exist-1gb"


	bucket := client.Bucket(bucketName)
	file_size := 1024 * 1024 * 1024 // 1GiB
	w := bucket.Object(objectName).If(storage.Conditions{DoesNotExist: true}).NewWriter(ctx)
	w.ChunkSize = 1024*1024

	// Hashes [base64] for test-go-file-1gb.txt:iB/s
	// Hash (crc32c):          HAl3Mg==
	// Hash (md5):             rbWij9puwqAQdbmUWIeggw==
	md5Bytes, _ := base64.StdEncoding.DecodeString("rbWij9puwqAQdbmUWIeggw==")
	w.MD5 = []byte(md5Bytes)
	r := strings.NewReader(string(bytes.Repeat([]byte("a"), file_size)))

	for {
		if _, err = io.CopyN(w, r, 1024*1024); err != nil {
			fmt.Errorf("Error: %v", err)
			break
		}
	}
	// EOFs and 412s are okay. 412s are okay as this routine might have
	// lost a race with another routine that uploaded the associated
	// object first, thus failing the above precondition.
	if err != nil && err != io.EOF && !strings.Contains(err.Error(), "Error 412") {
		w.Close()
		fmt.Errorf("Error: %v", err)
	}
	w.Close()
}

func main() {
	ctx := context.Background()
	tctx, cancel := context.WithTimeout(time.Second)
	defer cancel() // Cancel when done, whether we time out or not.
	write_test_file(tctx)
}
```

**Comment by tritone** [comment] 2020-01-08 21:48
This is currently out of SLO and waiting for a response, so I'm going to downgrade this to p2 for now pending a response from @joshuaseaton .

**Comment by codyoss** [comment] 2020-04-03 17:02
@joshuaseaton any update on this?

**Comment by tritone** [comment] 2020-04-16 04:03
I'm going to close this for now since we are still waiting on a response, but feel free to re-open if you'd like to come back to it @joshuaseaton .

**Closed by tritone** 2020-04-16 04:03 UTC
Labels: api: storage, needs more info, priority: p2, type: bug
