### ISSUE TITLE
SpanSql fails to parse "allow_commit_timestamp" OPTIONS

### ISSUE THREAD

**Issue by ranveerfingo** [googleapis/google-cloud-go#1697] opened 2019-12-09 21:10 UTC
The following column def does not get parsed.
time_added TIMESTAMP NOT NULL OPTIONS (
    allow_commit_timestamp = true
  ),

**Comment by olavloite** [comment] 2019-12-10 10:45
Duplicate of #1693

**Closed** 2019-12-10 10:46 UTC
Labels: api: spanner, duplicate
