### ISSUE TITLE
pubsub: batch processing instead of 1 goroutine per message

### ISSUE THREAD

**Issue by kokizzu** [googleapis/google-cloud-go#10912] opened 2024-09-24 15:54 UTC
## Is your feature request related to a problem? Please describe.
currently I'm trying to do batch fetch from pubsub, transform, then insert to bigquery.
but the pubsub library spawns a goroutine for each message, this causes bunch of memory consumption and inefficient processing
```
func (s *Subscription) Receive(ctx context.Context, f func(context.Context, *Message)) error {
```

## Describe the solution you'd like
I need batch processing something like this
```
func (s *Subscription) ReceiveN(ctx context.Context, n items, f func(context.Context, []*Message)) error {
```

## Describe alternatives you've considered
taking out the pubsub library and write own proper batch processing

## Additional context
by doing this, it would be super efficient to do batch processing

**Comment by hongalex** [comment] 2024-09-24 22:26
Thanks for filing an issue.

This is a duplicate of https://issuetracker.google.com/288595422, please +1 that issue if this is affecting you.

**Closed by hongalex** 2024-09-24 22:26 UTC
Labels: api: pubsub, triage me
