### ISSUE TITLE
firestore: add BeginTx and Commit

### ISSUE THREAD

**Issue by tomasweigenast** [googleapis/google-cloud-go#5519] opened 2022-02-11 20:10 UTC
When working on large projects, its common to have different data sources. Currently, im working on a project which has sql, firestore, and others data sources, to simplify, i implemented the repository pattern, but i have a problem with transactions and firestore. 

**database/sql** package provides `BeginTx` and `Commit` methods to handle the transaction in different methods, this gave me the posibility to create useful methods for Get, Insert, Update, Delete entities using a `sql.Tx` object. On the other hand, Firestore only provides the **RunTransaction** which isolates the call to a function passed as a parameter. This makes impossible to pass the `firestore.Transaction` object to other methods.

**Comment by telpirion** [comment] 2022-02-15 17:57
Thank you for the feature request, @tomasweigenast. Just to clarify: you're asking us to add a `BeginTransaction()` and a `Commit()` method to the Firestore client?

**Comment by tomasweigenast** [comment] 2022-02-16 12:35
Yes, that is. @telpirion

**Comment by tomasweigenast** [comment] 2022-02-26 20:25
Any update on this? @telpirion

**Comment by telpirion** [comment] 2022-09-23 17:50
I'm going to close this issue for now.

The original issue states:

>  On the other hand, Firestore only provides the RunTransaction which isolates the call to a function passed as a parameter. This makes impossible to pass the firestore.Transaction object to other methods.

Have you tried calling another function from within the `RunTransaction` function? It seems to me that you could pass a pointer to the `firestore.Transaction` object to another function from within the RunTransaction function.

**Closed by telpirion** 2022-09-23 17:50 UTC
Labels: type: feature request, api: firestore

**Comment by sebastiangon11** [comment] 2024-03-19 07:31
Hey there! I’m experiencing the same issue as @tomasweigenast 

The problem is not solved by passing the transaction object via parameter to other functions. The fact that firebase only provides the `runTransaction()` api is very limiting for architecturing an app.

In my case for example I am implementing a service/repository pattern, where the service handles all the business logic and the repositories encapsulates all the database queries.

The issue raises when I need to start a transaction from the service and call multiple repositories involved in the operation. 

Now I'm forced to:
* Create a new layer of abstraction for sharing the `transaction` object between the service and the repositories.
* Inject this new layer in all my services for initializing transactions.
* Inject this new layer in all my repositories for accessing the `transaction` object in each operation.
* Duplicate the code in each operation for checking if I'm inside a transaction or not.
  * This is because the code is different depending if there is a transaction or not, and the repositories should still work event if they are not inside a transaction.
  * For example `setDoc` vs `transaction.set`

### Example

```typescript
  // TransactionManager

  import { runTransaction as fsRunTransaction } from 'firebase/firestore'

  let openTransaction: Transaction | null = null

  const transactionManager = {
  const db = getFirestore(getFirebaseApp())

  const runTransaction = (updateFn) => {
    return fsRunTransaction(
      db,
      async (transaction) => {
        // Keep a reference to the open transaction so I can make different operations across different repositories.
        openTransaction = transaction
        await updateFn(transaction)
        openTransaction = null
      }
    )
  }

  return { transaction: openTransaction, runTransaction }

```

```typescript
     // Service

      transactionManager.runTransaction(async () => {
        const account = await accountsRepository.get(snapshot.accountId)
        await snapshotsRepository.create(snapshot)
        await accountsRepository.update({ ...account, balance: snapshot.balance })
      })
```

```typescript
      // Repository

      const snapshotsRef = collection(db, 'accounts', snapshot.accountId, 'snapshots')
      const snapshotRef = doc(snapshotsRef)

      if (transactionManager.transaction) {
        transactionManager.transaction.set(snapshotRef, snapshot)
      } else {
        await setDoc(snapshotRef, snapshot)
      }
```

## Feature request

Following up on @tomasweigenast request and think this issue wouldn't exist if firestore provided an API for `BeginTransaction` and `Commit` for example. Without changing the way in which queries are done depending if there is an open transaction or not.
