### ISSUE TITLE
Fails to build on arm64, ppc64el, armhf and i386 arches

### ISSUE THREAD

**Issue by daissi** [googleapis/google-cloud-go#4249] opened 2021-06-11 13:45 UTC
Forward a Debian bug https://bugs.debian.org/976507

**Environment**

A clean and fresh Debian unstable env with go 1.15

**Expected behavior**

google-cloud-go should be buildable on these different arches.

**Actual behavior**

It fails to build because of failing tests.

The full build log is available from:
   http://qa-logs.debian.net/2020/12/05/golang-google-cloud_0.56.0-1_unstable.log

**Comment by codyoss** [comment] 2021-06-11 14:44
From log:
```text
=== RUN   TestSetFromProtoValueErrors
    from_value_test.go:259: #22: 0x40005102f0, integer_value:9223372036854775807 : got nil, want error
--- FAIL: TestSetFromProtoValueErrors (0.00s)
```

Given this failure and looking more closely at the log it appears this a referencing a quite old version (last April) of google-cloud-go. @daissi is that true? Is this built off of https://github.com/googleapis/google-cloud-go/releases/tag/v0.56.0? If do does this reproduce one the latest version?

**Comment by daissi** [comment] 2021-06-11 15:34
I will test with a newest version, but it will take time. In the meantime, it looks like a similar issue happen in Fedora with 0.82.0 
https://src.fedoraproject.org/rpms/golang-cloud-google/c/9011e0b020?branch=rawhide

**Comment by codyoss** [comment] 2021-07-28 16:58
I am going to close this issue for now as I am unable to reproduce this without more information. If you have updates please share them and I will reopen. Thanks.

**Closed by codyoss** 2021-07-28 16:58 UTC
Labels: status: investigating

**Comment by vigneshraman** [comment] 2021-09-21 03:20
@codyoss these are the recent build failures on arm64/armhf with version 0.56.0-1

https://tests.reproducible-builds.org/debian/rb-pkg/bullseye/arm64/golang-google-cloud.html
https://tests.reproducible-builds.org/debian/rb-pkg/bullseye/armhf/golang-google-cloud.html
