### ISSUE TITLE
storage: NewReader does not use Endpoint override

### ISSUE THREAD

**Issue by cgeisser** [googleapis/google-cloud-go#1619] opened 2019-10-16 13:28 UTC
I'm running a test environment using https://github.com/fsouza/fake-gcs-server . The client uses a `WithEndpoint` override on client creation. API calls work and reach the fake server, except for `NewReader` which attempts to call the real Google Cloud Service.

Using the [`STORAGE_EMULATOR_HOST`](https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L115) environment variable to intercept the read path doesn't work because it forces an http connection and the fake GCS server runs with TLS.
 
## Client
The client is https://github.com/fsouza/fake-gcs-server/blob/master/examples/go/main.go
with a read call added to the end of main.

```
	rc, err := client.Bucket("sample-bucket").Object("some_file.txt").NewReader(context.TODO())
	if err != nil {
		log.Fatal(err)
	}
	defer rc.Close()

	data, err := ioutil.ReadAll(rc)
	fmt.Printf("data: %v", data)
}
```

## Describe Your Environment

OSX running a fake GCS in a docker container. Client is run directly on the host.

## Expected Behavior

Storage client uses my fake GCS endpoint to do reads as well as other API calls.

## Actual Behavior
Test program fetches from a real GCS bucket, which happens to be disabled.

```
got HTTP response code 403 with body: <?xml version='1.0' encoding='UTF-8'?><Error><Code>UserProjectAccountProblem</Code><Message>User project billing account not in good standing.</Message><Details>The billing account for project 700617496677 is disabled in state closed</Details></Error>
```

## Workaround

Give up on `WithEndpoint` and the environment variable and inject a new `Transport` like this one:
```
type Rewriter struct {
	baseTransport *http.Transport
}

func (r Rewriter) RoundTrip(req *http.Request) (*http.Response, error) {
	if req.URL.Host != "0.0.0.0:4443" {
		req.URL.Host = "0.0.0.0:4443"
		fmt.Printf("rewrite to %v", req.URL)
	}
	return r.baseTransport.RoundTrip(req)
}
```

**Comment by IlyaFaer** [comment] 2019-11-28 13:37
We've been in a middle of a search for the solution, when I caught my eye on [that comment](https://github.com/googleapis/google-cloud-go/issues/1680#issuecomment-558767958). Such a way of connecting worked in my case (I've reproduced your error and workaround), so I think this is it. Let's close the issue, but feel free to reopen if it doesn't work for you.

**Comment by evanj** [comment] 2019-12-05 02:07
Isn't this still a bug in the client library, even if there is a workaround? It is weird that WithEndpoint works for writers, but not for readers. Should NewClient return an error if someone has specified a different endpoint, since it doesn't work as intended?

The problem is that storage.Client has a separate `readHost` field that is not overridden by `WithEndpoint`: https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L99

Issue #1515 mentions the `STORAGE_EMULATOR_HOST` environment variable as an alternative, which does also work, although is a bit uglier to invoke from code.

**Comment by tritone** [comment] 2019-12-05 19:15
I think it would make sense to have WithEndpoint override the readHost as well-- @jadekler , @broady , thoughts on whether this approach would work?

**Comment by jadekler** [comment] 2019-12-05 23:38
Yes, this should work for _all_ endpoints. It is very much a bug in the client libraries. @tritone would be good to investigate refactoring out the manual-layer URLs and just using the underlying apiary's URL. If we can't do that, we'll have to figure out a way to snoop `WithEndpoint` in the manual layer and use the passed-in endpoint, or something like that. (non-ideal...)

**Comment by IlyaFaer** [comment] 2019-12-06 13:25
> it would make sense to have WithEndpoint override the readHost as well

I don't think this will work. I've tried to override `readHost` with `STORAGE_EMULATOR_HOST` and used emulator address as a value for it. PTAL at [this Cl](https://code-review.googlesource.com/c/gocloud/+/47931).

Things will work properly, if we'll override `req.URL.Host` with endpoint after this line:
https://github.com/googleapis/google-cloud-go/blob/6be194bcd87d12736af218daaffd1d3eaf350324/storage/reader.go#L113
And only this one. Even if we'll set `Host` in here:
https://github.com/googleapis/google-cloud-go/blob/6be194bcd87d12736af218daaffd1d3eaf350324/storage/reader.go#L104-L108
to endpoint it won't work, I've checked it many times

For now the only way that I found is to make this injection. But it looks ugly.

**Comment by IlyaFaer** [comment] 2019-12-10 20:18
@tritone, I've already pushed [an example](https://code-review.googlesource.com/c/google-api-go-client/+/49032) with workaround (we had a word about it with Jean), but looks like we're gonna fix this in client libraries, so I'll hold the Cl on pause for now

**Comment by broady** [comment] 2019-12-10 20:30
I talked briefly last week with @shinfan about this and we're both +1 on having endpoint override work for reads.

The endpoint returned by htransport.NewClient will need to be used and probably have the host extracted.

On support for the emulator... can we move that to a separate bug, please? We should properly support emulators via environment variables. Emulators is not an intended use case for endpoint override - it's really for pointing to specific regions or zones for a service and also for sandbox/test instances.

**Comment by tritone** [comment] 2019-12-13 18:13
I posted https://code-review.googlesource.com/c/gocloud/+/49550 to attempt to fix this as suggested by @broady , but I realized I'm making an assumption in my fix. The reason for separating out readHost here is that raw.BasePath needs a valid JSON API endpoint (e.g. storage.googleapis.com/storage/v1/ ) while readHost requires a valid XML API endpoint (e.g. storage.googleapis.com ). I'm wondering if we can assume the same relationship between XML/JSON endpoints holds for those attempting to use the WithEndpoint option, or if it's even clear to them that they would need to have an XML endpoint working as well in order to use the client.

**Closed** 2019-12-17 23:04 UTC
Labels: :rotating_light:, api: storage, priority: p1, type: bug

**Comment by tritone** [comment] 2019-12-17 23:16
After conferring with @broady we ended up going ahead with the PR above. Users of WithEndpoint should note that if they attempt to set a JSON endpoint e.g. https://storage.googleapis.com/storage/v1/, then the hostname (storage.googleapis.com in this example) must be a valid XML endpoint in order for reads to work as expected.

**Comment by vikstrous** [comment] 2020-01-19 23:00
I'm running into an issue with 95bbb7d.
u.Hostname() is used rather than u.Host. This drops custom ports. https://github.com/googleapis/google-cloud-go/commit/95bbb7d728ee6b3f6c1873cfee71b0cb87a0f60d#diff-efc763a7d18657aa44c013131823cfc9R131

Also, I'm very surprised by "Emulators is not an intended use case for endpoint override - it's really for pointing to specific regions or zones for a service and also for sandbox/test instances.". Does that mean that there's no official way to use an emulator without setting the env var?

As much as I hate it, I tried using
```
	os.Setenv("STORAGE_EMULATOR_HOST", url)
```
but that failed to connect to the emulator for multiple reasons. The first one was that the emulator was using https rather than http. From what I can tell, there's no reliable way to connect to an emulator in the latest version of this library. https://github.com/googleapis/google-cloud-go/issues/1680#issuecomment-559135642 at least worked. I'll have to use the old workaround and old version for now.

**Comment by tbpg** [comment] 2020-01-21 18:00
Thanks. I filed #1737 for the port issue.

And yes, as I understand it, the env var is the correct way to enable the emulator (I might be wrong).

**Comment by tritone** [comment] 2020-01-25 21:42
I posted a fix to retain the port; hopefully that should resolve the issue. Sorry for the bug!

**Comment by tritone** [comment] 2020-01-27 18:01
@vikstrous I pushed a fix for the port issue; please let me know if this resolves what you are seeing.
