### ISSUE TITLE
storage: NewRangeReader doesn't work for gzip compressed files.

### ISSUE THREAD

**Issue by ihuh0** [googleapis/google-cloud-go#1734] opened 2020-01-17 16:59 UTC
**Client**

storage

**Expected behavior**

For gzip compressed files, obj.NewRangeReader(ctx, offset, length) should return a partial reader for that range that starts at offset for the uncompressed file.

**Actual behavior**

If length < 0, it returns a NewReader for the entire file with offset=0 instead of the requested range (though it does read it uncompressed as desired). If length > 0 but offset != 0, it returns a "partial request not satisfied" error.

**Comment by frankyn** [comment] 2020-02-03 22:04
Hi @ihuh0,

When doing a ranged request, the object is expected not to be compressed per [documentation](https://cloud.google.com/storage/docs/transcoding#discouraged_practices).

> When transcoding occurs, if the request for the object includes a Range header, that header is silently ignored. This means that requests for partial content are not fulfilled, and the response instead serves the entire requested object. For example, if you have a 10 GB object that is eligible for transcoding, but include the header Range: bytes=0-10000 in the request, you still receive the entire 10 GB object.

This is working as intended in this case. Please feel free to reopen. Closing for now.

**Closed by frankyn** 2020-02-03 22:04 UTC
Labels: api: storage, type: question
