### ISSUE TITLE
storage: dramatic increase in goroutines after 1.10 version upgrade

### ISSUE THREAD

**Issue by ouyangz314** [googleapis/google-cloud-go#2688] opened 2020-08-05 18:20 UTC
**Description**: 
I am opening this case because one of my customers experienced dramatic increase in Go routine after upgrading the Go library version from 1.9 to 1.10. This is causing dramatic increase in CPU utilization 

**Environment**
GKE cluster with 1.14.10-gke hosting Go application. The application interacts with GCS bucket with Go client libraries

**Go Environment**
1.10

**Code**
func (s *GCSModel) Put...(ctx, rClient, ...) {
  bkt := rClient.bucket(bucketname)
  obj := bkt.Object(signame)

   w := obj.NewWriter(ctx)
   w.ChunkSize = 0
   
    if _, err := w.Write(data); err !=nil {
        return err
    }
    if err := w.Close(); err!=nil {
         return err
    }
}

**Expected behavior**
After the upgrade, the number of Go routines should increase for a short period of time and go back to normal. 

**Actual behavior**
However, it increased from ~250 to 5-6k and spiked up to this value multiple times. GCS did not show higher traffic nor error rate (compared to before upgrade)

**Additional context**
Customer upgraded 1.10

**Comment by tritone** [comment] 2020-08-05 19:04
Hi, thanks for your report.

Are you referring to upgrading cloud.google.com/go/storage from v1.9.0 to v1.10.0? Or something else?

I'm also not clear from the report where the go routines in question are being created. Could you add some more detail there?

**Comment by ouyangz314** [comment] 2020-08-05 19:06
Yes, I am referring to upgrading cloud.google.com/go/storage from v1.9.0 to v1.10.0

I can ask my client if they are comfortable with me attaching the screenshot of the go routine metrics they collected

**Comment by tritone** [comment] 2020-08-05 19:19
Sounds good. I think I would have to see more of your code to offer advice or diagnosis here. The storage client is safe to use across multiple goroutines, but Writer calls will not create additional goroutines when you call them. So it's not really possible to diagnose what might be going on without seeing how the goroutines are created and used.

If you could make a minimal repro of code that shows the difference in behavior, that would be very helpful.

**Comment by ouyangz314** [comment] 2020-08-07 23:14
The customer has provided the code and the instruction on reproducing the error is in "Instructions to run code to reproduce issue.txt". Please remove all ".txt" to run the scripts because I had to change all the format to txt in order to upload.

[Instructions to run code to reproduce issue.txt](https://github.com/googleapis/google-cloud-go/files/5044171/Instructions.to.run.code.to.reproduce.issue.txt)
[run1_14.sh.txt](https://github.com/googleapis/google-cloud-go/files/5044176/run1_14.sh.txt)
[run1_12.sh.txt](https://github.com/googleapis/google-cloud-go/files/5044177/run1_12.sh.txt)
[main.go.txt](https://github.com/googleapis/google-cloud-go/files/5044178/main.go.txt)
[go.sum.txt](https://github.com/googleapis/google-cloud-go/files/5044179/go.sum.txt)
[go.mod.txt](https://github.com/googleapis/google-cloud-go/files/5044180/go.mod.txt)
[Dockerfile.txt](https://github.com/googleapis/google-cloud-go/files/5044181/Dockerfile.txt)
[build.sh.txt](https://github.com/googleapis/google-cloud-go/files/5044182/build.sh.txt)

**Comment by ouyangz314** [comment] 2020-08-07 23:16
This is the screenshot of the high Go Routine:
![goroutine_increase](https://user-images.githubusercontent.com/68121492/89695566-4d972a80-d8c9-11ea-9548-00c0653b2a0c.png)

**Comment by ouyangz314** [comment] 2020-08-07 23:19
There were multiple combinations of configurations  that caused this problem:
cloud.google.com/go/storage 1.9.0
GO 1.14.7
golang.org/x/net v0.0.0-20200602114024-627f9648deb9

cloud.google.com/go/storage 1.10.0
GO 1.12.3
golang.org/x/net v0.0.0-20200707034311-ab3426394381

The one that works is: 
cloud.google.com/go/storage 1.9.0
GO 1.12.3
golang.org/x/net v0.0.0-20200602114024-627f9648deb9

**Comment by yuanyuan-gl** [comment] 2020-08-11 18:09
Hi Chris, just curious that if there is any update on this issue, are you able to reproduce it? Thanks.

**Comment by tritone** [comment] 2020-08-17 01:34
Thanks for your patience. I was able to reproduce the issue (thanks for the repro!) and do a little digging.

I believe that what you're experiencing is caused by two changes that we made over the past few months in the underlying google-api-go-client library:
* googleapis/google-api-go-client#496
* googleapis/google-api-go-client#532

Basically, what happened here is that we made some changes in the underlying http.Transport to improve client performance on reads at high load. In order to avoid race conditions and/or having side effects on other callers of net/http, instead of using the singleton http.DefaultTransport, each new `storage.Client` object now has its own cloned transport. Creating many transports without closing idle connections will cause leaked goroutines (see golang/go#25759 for an example).

I think we didn't think of this as being a problem because the storage client is thread-safe and intended to be created once and used across goroutines, rather than being recreated (see https://pkg.go.dev/cloud.google.com/go/storage?tab=doc#Client ). In that sense your repro is something of a pathological example because it constantly creates instances of storage.Client in a loop, which is not the recommended approach.

I tried modifying your repro to instantiate the client once, outside the loop. When run with go 1.14, this cut down on goroutines even below your baseline (total number never exceeded 20 for me in several runs). Here's my modified main.go:

```
package main

import (
	"context"
	"fmt"
	"log"
	"math/rand"
	"runtime"
	"time"

	"cloud.google.com/go/storage"
)

func main() {
	start := time.Now()

	s1 := rand.NewSource(time.Now().UnixNano())
	r1 := rand.New(s1)

	dump := make([]byte, 10000)

	go func() {
		for {
			fmt.Printf("Routines: %d \n", runtime.NumGoroutine())
			time.Sleep(2 * time.Second)
		}
	}()

	// Instantiate the storage client once, outside the loop.
	ctx := context.Background()
	client, err := storage.NewClient(ctx)
	if err != nil {
		log.Println(err)
	}

	for {
		elapsed := time.Since(start)

		// 120s
		if elapsed > 120000000000 {
			 log.Println("done")
				break
		}


		go func() {

			ctx := context.Background()

			tctx, cancel := context.WithTimeout(ctx, 30*time.Second)
			defer cancel()

			wc := client.Bucket(os.Getenv("BUCKET_NAME")).Object(fmt.Sprintf("%d", r1.Intn(10000000))).NewWriter(tctx)
			wc.ChunkSize=0

			if _, err := wc.Write(dump); err != nil {
				log.Println(err)
			}

			if err := wc.Close(); err != nil {
				log.Println(err)
			}

		}()

		time.Sleep(50 * time.Millisecond)
	}

}
```

The change above is my recommended workaround here. Failing that, another possible workaround is to create a single `http.Client` in your application and then pass that into the storage client using the `WithHTTPClient` option. This would also remove the transport duplication. I can write up a sample for how to do that if you like.

I need to follow up with teammates about whether we should revisit the decision to use a cloned transport, but it would probably take some time to figure out that change and roll it out if we did.

Let me know if this workaround will be viable for you, or if you have any further questions.

**Closed** 2020-08-18 22:08 UTC
Labels: api: storage, type: question
