### ISSUE TITLE
pubsub: bundle size does not include request overhead

### ISSUE THREAD

**Issue by evanj** [googleapis/google-cloud-go#1453] opened 2019-06-07 15:29 UTC
## Expected Behavior

Publishing a message containing 1 byte immediately followed by publishing a message with 9999935 byte should work. Publishing them individually *does* work.

## Actual Behavior

`rpc error: code = InvalidArgument desc = The value for 10000004 is too large. You passed request_size in the request, but the maximum value is 10000000`

## Root cause

The bundler code does not account for the request overhead, so it creates bundles that are too large. To correct this the code should either do the correct calculation, or just decrease the maximum threshold, e.g. maybe down to 900000.

## Example code

```go
package main

import (
	"context"
	"fmt"

	"cloud.google.com/go/pubsub"
)

func main() {
	ctx := context.Background()
	pubsubClient, err := pubsub.NewClient(ctx, "project")
	if err != nil {
		panic(err)
	}
	topic := pubsubClient.Topic("topic")

	publishResults := []*pubsub.PublishResult{}
	lengths := []int{1, 9999930}
	for _, length := range lengths {
		msg := &pubsub.Message{
			Data: make([]byte, length),
		}
		r := topic.Publish(ctx, msg)

		// Uncomment: the program will work
		// id, err := r.Get(ctx)
		// if err != nil {
		// 	panic(err)
		// }
		// fmt.Println(id)
		publishResults = append(publishResults, r)
	}

	for i, r := range publishResults {
		id, err := r.Get(ctx)
		if err != nil {
			panic(err)
		}
		fmt.Println(i, id)
	}
}
```

## Output (with some additional logging added)

```
Publish size:3
Publish size:9999935
Bundler bytes exceeded: 9999938 > 1000000 
publishMessageBundle messages:2 size:10000004
panic: rpc error: code = InvalidArgument desc = The value for 10000004 is too large. You passed request_size in the request, but the maximum value is 10000000.
```

**Comment by sduskis** [comment] 2019-06-07 15:43
Another person brought up this issue here: https://github.com/googleapis/google-cloud-python/issues/7108.  It looks like we need to make a change across the board.

**Comment by evanj** [comment] 2019-06-07 15:50
I found this because I ran into the Python issue, and was checking if Go has the same one (it does). Its low default "batch threshold" of 1e6 makes it harder to hit, although this sequence is one way, and changing the PublishSettings is another.

I suspect Java has the same problem, since it uses similar code to calculate its batch sizes: https://github.com/googleapis/google-cloud-java/blob/67668c1411169338374b050eae50ed650e318c54/google-cloud-clients/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Publisher.java#L644

**Comment by jadekler** [comment] 2019-10-02 17:15
I believe this is fixed as of https://github.com/googleapis/google-cloud-go/commit/5bc02cbce48731bbb1617d830561bb61da810c1e#diff-040f8e6525bd0c62798afb41e6644f37. Closing, but @hongalex could you confirm?

**Comment by hongalex** [comment] 2019-10-02 18:14
This is actually related to another issue with publish bundles rather than Ack/Modack which was what I fixed in the issue you referenced. I should be able to get to this soon.

**Comment by hongalex** [comment] 2019-10-02 22:29
Apologies for the delay. The issue isn't actually related to any specific message in the bundle, but the fact that the bundler does not account for the overhead from the `topic` field in [ `PublishRequest`](https://cloud.google.com/pubsub/docs/reference/rpc/google.pubsub.v1#publishrequest). Sending out a CL and tests to address this shortly.

**Closed** 2019-10-03 17:33 UTC
Labels: :rotating_light:, api: pubsub, priority: p1, type: bug
