### ISSUE TITLE
orchestration/airflow: Unable to patch Cloud  environment using update mask

### ISSUE THREAD

**Issue by russellrc-keebo** [googleapis/google-cloud-go#7147] opened 2022-12-07 17:15 UTC
**Client**

e.g. Airflow / Cloud Composer

**Environment**

e.g. Cloud composer Composer

**Go Environment**

$ go version
`go version go1.19 darwin/arm64`

$ go env
```
GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/russell/Library/Caches/go-build"
GOENV="/Users/russell/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/russell/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/russell/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/Users/russell/.gobrew/versions/1.19/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/Users/russell/.gobrew/versions/1.19/go/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.19"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/russell/Workspace/keebo-server/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ry/v5ym74p96cj3m4hgtm2wpzk00000gn/T/go-build557306818=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Code**

e.g.
```go
package main

import (
	"context"
	"fmt"

	service "cloud.google.com/go/orchestration/airflow/service/apiv1"
	"cloud.google.com/go/orchestration/airflow/service/apiv1/servicepb"
	"google.golang.org/genproto/protobuf/field_mask"
)

func main() {
	ctx := context.Background()
	ec, err := service.NewEnvironmentsClient(ctx)
	if err != nil {
		panic(err)
	}
	defer ec.Close()

	envName := "projects/my-project/locations/us-central1/environments/my-env"
	environment, err := ec.GetEnvironment(ctx, &servicepb.GetEnvironmentRequest{Name: envName})
	if err != nil {
		panic(err)
	}
	fmt.Printf("%s", environment)

	keeboBatch := map[string]string{"my-package": "==0.1.2"}
	paths := []string{"config.softwareConfig.pypiPackages.my-package"}
	patchReq := servicepb.UpdateEnvironmentRequest{
		Name:       envName,
		UpdateMask: &field_mask.FieldMask{Paths: paths},
		Environment: &servicepb.Environment{
			Config: &servicepb.EnvironmentConfig{
				SoftwareConfig: &servicepb.SoftwareConfig{
					PypiPackages: keeboBatch,
				},
			},
		},
	}

	updateOp, err := ec.UpdateEnvironment(ctx, &patchReq)
	if err != nil {
		panic(err)
	}

	fmt.Printf("update operation: %s", updateOp.Name())
}
```

**Expected behavior**
Pypi Package should be updated

**Actual behavior**
Getting error `rpc error: code = InvalidArgument desc = config.softwareConfig.pypiPackages.my-package is not a supported FieldMask path`

e.g. Using cloud.google.com/go/orchestration/airflow/service/apiv1 `v1.4.0`

**Comment by russellrc-keebo** [comment] 2022-12-07 17:32
I clicked the submit button by mistake before filling out all the details.  Updated the ticket description with more info 🙂

**Comment by quartzmo** [comment] 2022-12-08 19:50
The docs for [UpdateEnvironmentRequest](https://cloud.google.com/composer/docs/reference/rpc/google.cloud.orchestration.airflow.service.v1#google.cloud.orchestration.airflow.service.v1.UpdateEnvironmentRequest) provide `config.softwareConfig.pypiPackages.scikit-learn` as an example. This value matches your key except for the final element. Is it possible that `my-package` isn't allowed?

**Comment by russellrc-keebo** [comment] 2022-12-08 21:00
@quartzmo `my-package` is just a replacement of my real pipy package name, like `scikit-learn`.

I tried the exact same request in the Google Cloud API explorer ([link](https://cloud.google.com/composer/docs/reference/rest/v1/projects.locations.environments/patch)) and it worked just fine.

I also tried the request with curl, and it also worked. Something like this:
```
curl -X PATCH "https://composer.googleapis.com/v1/projects/my-project/locations/us-central1/environments/my-env?updateMask=config.softwareConfig.pypiPackages.my-package" \
-H "Content-Type: application/json; charset=UTF-8" \
-H "X-Goog-User-Project: my-project" \
-H "Authorization: Bearer $(gcloud auth application-default print-access-token)" \
-d '{"config":{"softwareConfig":{"pypiPackages":{"my-package":"==0.1.2"}}}}'
```

Both of them are equivalent to the go code snippet I pasted in the issue description as far as I understand.

Even more, the documentation of the `UpdateMask` field in the client library code is the same ([link](https://pkg.go.dev/cloud.google.com/go/orchestration@v1.4.0/airflow/service/apiv1/servicepb#UpdateEnvironmentRequest)).

All of this leads me to believe that this is either some bug in the client library... or maybe I am missing some silly difference with the client usage that is not mentioned anywhere.

**Comment by quartzmo** [comment] 2022-12-09 20:46
@russellrc-keebo Thank you for clarifying about the package name and for the `curl` example.

I'll try to reproduce this myself.

**Comment by russellrc-keebo** [comment] 2022-12-21 00:57
Hi @quartzmo,
Have you had any chance to reproduce this issue?
I am almost sure this is a bug, most likely related to how the `UpdateMask` parameter is encoded and decoded by the client library.

**Comment by quartzmo** [comment] 2022-12-21 16:44
@russellrc-keebo I have reproduced the issue but not made further progress. Can you link to source that you believe is the cause of the bug?

**Comment by russellrc-keebo** [comment] 2022-12-22 01:30
@quartzmo 
I haven't gone that deep into debugging it due to lack of time, but judging from the evidence it's the best explanation I can think of.

**Comment by quartzmo** [comment] 2022-12-22 17:46
@russellrc-keebo Can you try snake-case for your path? `"config.software_config.pypi_packages.my-package"`

**Comment by quartzmo** [comment] 2022-12-22 18:17
The documentation for `FieldMask` really misses the opportunity to clarify whether snake or camel case is used. (The single-letter paths `a`, `b`, `c` are not helpful.) But I believe the section [JSON Encoding of Field Masks](https://pkg.go.dev/google.golang.org/protobuf/types/known/fieldmaskpb#hdr-JSON_Encoding_of_Field_Masks) suggests that snake case is the standard, and that camel is only used in JSON:

> Fields name in each path are converted to/from lower-camel naming conventions.

**Comment by russellrc-keebo** [comment] 2022-12-23 00:01
Thanks @quartzmo, I'll give that a try and let you know the result.

**Comment by quartzmo** [comment] 2023-01-03 23:33
@russellrc-keebo Did you get a chance to try snake-case for the update mask path?

**Comment by russellrc-keebo** [comment] 2023-01-04 02:06
@quartzmo not yet 😞 , will try to do it soon

**Comment by codyoss** [comment] 2023-01-06 17:10
Closing for now, please feel free to re-open if this did not work for you.

**Closed by codyoss** 2023-01-06 17:10 UTC
Labels: type: question, api: composer

**Comment by lepiaf** [comment] 2023-07-17 14:03
Hello,

I've encounter the same issue but with nodejs client. I've tried this value "config.software_config.pypi_packages" as path in updateMask and it works.

Thank you @quartzmo
