### ISSUE TITLE
profiler: unflake TestAgentIntegration

### ISSUE THREAD

**Issue by jadekler** [googleapis/google-cloud-go#1301] opened 2019-02-04 16:10 UTC
https://sponge.corp.google.com/target?id=3b07711b-0b94-456e-8069-3ec3fbad6e8b&target=cloud-go-libraries/google-cloud-go/continuous/go110&searchFor

```
Fri Feb  1 22:13:37 UTC 2019: + go run busybench.go --service=profiler-test-go110-2019-02-01-14-12-00-522960-0800-gce --mutex_profiling=true
Fri Feb  1 22:13:46 UTC 2019: 2019/02/01 22:13:46 profiler has started
Fri Feb  1 22:14:24 UTC 2019: 2019/02/01 22:14:24 successfully created profile HEAP
Fri Feb  1 22:14:24 UTC 2019: 2019/02/01 22:14:24 start uploading profile
Fri Feb  1 22:14:28 UTC 2019: 2019/02/01 22:14:28 successfully created profile THREADS
Fri Feb  1 22:14:28 UTC 2019: 2019/02/01 22:14:28 start uploading profile
Fri Feb  1 22:14:29 UTC 2019: 2019/02/01 22:14:29 successfully created profile CONTENTION
Fri Feb  1 22:14:39 UTC 2019: 2019/02/01 22:14:39 start uploading profile
Fri Feb  1 22:14:47 UTC 2019: 2019/02/01 22:14:47 successfully created profile CPU
Fri Feb  1 22:14:57 UTC 2019: 2019/02/01 22:14:57 start uploading profile
Fri Feb  1 22:14:58 UTC 2019: 2019/02/01 22:14:58 successfully created profile HEAP_ALLOC
Fri Feb  1 22:15:08 UTC 2019: 2019/02/01 22:15:08 start uploading profile
Fri Feb  1 22:15:09 UTC 2019: 2019/02/01 22:15:09 successfully created profile THREADS
Fri Feb  1 22:15:09 UTC 2019: 2019/02/01 22:15:09 start uploading profile
Fri Feb  1 22:15:09 UTC 2019: 2019/02/01 22:15:09 successfully created profile CONTENTION
Fri Feb  1 22:15:19 UTC 2019: 2019/02/01 22:15:19 start uploading profile
Fri Feb  1 22:15:36 UTC 2019: 2019/02/01 22:15:36 successfully created profile HEAP_ALLOC
Fri Feb  1 22:15:46 UTC 2019: 2019/02/01 22:15:46 start uploading profile
Fri Feb  1 22:15:48 UTC 2019: 2019/02/01 22:15:48 successfully created profile CPU
Fri Feb  1 22:15:58 UTC 2019: 2019/02/01 22:15:58 start uploading profile
Fri Feb  1 22:15:59 UTC 2019: 2019/02/01 22:15:59 successfully created profile HEAP
Fri Feb  1 22:15:59 UTC 2019: 2019/02/01 22:15:59 start uploading profile
Fri Feb  1 22:16:14 UTC 2019: 2019/02/01 22:16:14 successfully created profile THREADS
Fri Feb  1 22:16:14 UTC 2019: 2019/02/01 22:16:14 start uploading profile
Fri Feb  1 22:16:17 UTC 2019: 2019/02/01 22:16:17 busybench finished profiling.
Fri Feb  1 22:16:17 UTC 2019: ++ sleep 300
2019/02/01 22:16:34 Serial port output for profiler-test-go111-2019-02-01-14-12-00-522960-0800:
Fri Feb  1 22:12:26 UTC 2019: + retry apt-get update
Fri Feb  1 22:12:26 UTC 2019: + for i in {1..3}
Fri Feb  1 22:12:26 UTC 2019: + apt-get update
Fri Feb  1 22:12:30 UTC 2019: + return 0
Fri Feb  1 22:12:30 UTC 2019: + retry apt-get -y -q install git
Fri Feb  1 22:12:30 UTC 2019: + for i in {1..3}
Fri Feb  1 22:12:30 UTC 2019: + apt-get -y -q install git
Fri Feb  1 22:12:31 UTC 2019: debconf: unable to initialize frontend: Dialog
Fri Feb  1 22:12:31 UTC 2019: debconf: (TERM is not set, so the dialog frontend is not usable.)
Fri Feb  1 22:12:31 UTC 2019: debconf: falling back to frontend: Readline
Fri Feb  1 22:12:31 UTC 2019: debconf: unable to initialize frontend: Readline
Fri Feb  1 22:12:31 UTC 2019: debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7, <> line 11.)
Fri Feb  1 22:12:31 UTC 2019: debconf: falling back to frontend: Teletype
Fri Feb  1 22:12:31 UTC 2019: dpkg-preconfigure: unable to re-open stdin:
Fri Feb  1 22:12:39 UTC 2019: + return 0
Fri Feb  1 22:12:39 UTC 2019: + mkdir -p /tmp/bin
Fri Feb  1 22:12:39 UTC 2019: + retry curl -sL -o /tmp/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
Fri Feb  1 22:12:39 UTC 2019: + for i in {1..3}
Fri Feb  1 22:12:39 UTC 2019: + curl -sL -o /tmp/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
Fri Feb  1 22:12:39 UTC 2019: + return 0
Fri Feb  1 22:12:39 UTC 2019: + chmod +x /tmp/bin/gimme
Fri Feb  1 22:12:39 UTC 2019: + export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tmp/bin
Fri Feb  1 22:12:39 UTC 2019: + PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tmp/bin
Fri Feb  1 22:12:39 UTC 2019: ++ gimme 1.11
Fri Feb  1 22:12:47 UTC 2019: + retry eval '
Fri Feb  1 22:12:47 UTC 2019: unset GOOS;
Fri Feb  1 22:12:47 UTC 2019: unset GOARCH;
Fri Feb  1 22:12:47 UTC 2019: export GOROOT='''/.gimme/versions/go1.11.linux.amd64''';
Fri Feb  1 22:12:47 UTC 2019: export PATH="/.gimme/versions/go1.11.linux.amd64/bin:${PATH}";
Fri Feb  1 22:12:47 UTC 2019: go version >&2;
Fri Feb  1 22:12:47 UTC 2019: 
Fri Feb  1 22:12:47 UTC 2019: export GIMME_ENV="/.gimme/envs/go1.11.env"'
Fri Feb  1 22:12:47 UTC 2019: + for i in {1..3}
Fri Feb  1 22:12:47 UTC 2019: + eval '
Fri Feb  1 22:12:47 UTC 2019: unset GOOS;
Fri Feb  1 22:12:47 UTC 2019: unset GOARCH;
Fri Feb  1 22:12:47 UTC 2019: export GOROOT='''/.gimme/versions/go1.11.linux.amd64''';
Fri Feb  1 22:12:47 UTC 2019: export PATH="/.gimme/versions/go1.11.linux.amd64/bin:${PATH}";
Fri Feb  1 22:12:47 UTC 2019: go version >&2;
Fri Feb  1 22:12:47 UTC 2019: 
Fri Feb  1 22:12:47 UTC 2019: export GIMME_ENV="/.gimme/envs/go1.11.env"'
Fri Feb  1 22:12:47 UTC 2019: ++ unset GOOS
Fri Feb  1 22:12:47 UTC 2019: ++ unset GOARCH
Fri Feb  1 22:12:47 UTC 2019: ++ export GOROOT=/.gimme/versions/go1.11.linux.amd64
Fri Feb  1 22:12:47 UTC 2019: ++ GOROOT=/.gimme/versions/go1.11.linux.amd64
Fri Feb  1 22:12:47 UTC 2019: ++ export PATH=/.gimme/versions/go1.11.linux.amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tmp/bin
Fri Feb  1 22:12:47 UTC 2019: ++ PATH=/.gimme/versions/go1.11.linux.amd64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tmp/bin
Fri Feb  1 22:12:47 UTC 2019: ++ go version
Fri Feb  1 22:12:47 UTC 2019: go version go1.11 linux/amd64
Fri Feb  1 22:12:47 UTC 2019: ++ export GIMME_ENV=/.gimme/envs/go1.11.env
Fri Feb  1 22:12:47 UTC 2019: ++ GIMME_ENV=/.gimme/envs/go1.11.env
Fri Feb  1 22:12:47 UTC 2019: + return 0
Fri Feb  1 22:12:47 UTC 2019: + export GOPATH=/go
Fri Feb  1 22:12:47 UTC 2019: + GOPATH=/go
Fri Feb  1 22:12:47 UTC 2019: + export GOCLOUD_HOME=/go/src/cloud.google.com/go
Fri Feb  1 22:12:47 UTC 2019: + GOCLOUD_HOME=/go/src/cloud.google.com/go
Fri Feb  1 22:12:47 UTC 2019: + mkdir -p /go/src/cloud.google.com/go
Fri Feb  1 22:12:47 UTC 2019: + retry git clone https://code.googlesource.com/gocloud /go/src/cloud.google.com/go
Fri Feb  1 22:12:47 UTC 2019: + for i in {1..3}
Fri Feb  1 22:12:47 UTC 2019: + git clone https://code.googlesource.com/gocloud /go/src/cloud.google.com/go
Fri Feb  1 22:12:47 UTC 2019: Cloning into '/go/src/cloud.google.com/go'...
Fri Feb  1 22:12:50 UTC 2019: + return 0
Fri Feb  1 22:12:50 UTC 2019: + cd /go/src/cloud.google.com/go
Fri Feb  1 22:12:50 UTC 2019: + retry git fetch origin 756b0e0009e81a539e95b2821201b2bf1153a475
Fri Feb  1 22:12:50 UTC 2019: + for i in {1..3}
Fri Feb  1 22:12:50 UTC 2019: + git fetch origin 756b0e0009e81a539e95b2821201b2bf1153a475
Fri Feb  1 22:12:50 UTC 2019: From https://code.googlesource.com/gocloud
Fri Feb  1 22:12:50 UTC 2019: * branch              756b0e0009e81a539e95b2821201b2bf1153a475 -> FETCH_HEAD
Fri Feb  1 22:12:50 UTC 2019: + return 0
Fri Feb  1 22:12:50 UTC 2019: + git reset --hard 756b0e0009e81a539e95b2821201b2bf1153a475
Fri Feb  1 22:12:50 UTC 2019: HEAD is now at 756b0e00 irm: generate new irm v1alpha2 client
Fri Feb  1 22:12:50 UTC 2019: + cd /go/src/cloud.google.com/go/profiler/busybench
Fri Feb  1 22:12:50 UTC 2019: + retry go get
Fri Feb  1 22:12:50 UTC 2019: + for i in {1..3}
Fri Feb  1 22:12:50 UTC 2019: + go get
Fri Feb  1 22:12:50 UTC 2019: go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
Fri Feb  1 22:12:50 UTC 2019: ignoring ../../go.mod;
Fri Feb  1 22:12:51 UTC 2019: see 'go help modules'
Fri Feb  1 22:13:37 UTC 2019: + return 0
Fri Feb  1 22:13:37 UTC 2019: + go run busybench.go --service=profiler-test-go111-2019-02-01-14-12-00-522960-0800-gce --mutex_profiling=true
Fri Feb  1 22:13:47 UTC 2019: 2019/02/01 22:13:47 profiler has started
Fri Feb  1 22:14:27 UTC 2019: 2019/02/01 22:14:27 successfully created profile THREADS
Fri Feb  1 22:14:27 UTC 2019: 2019/02/01 22:14:27 start uploading profile
Fri Feb  1 22:14:43 UTC 2019: 2019/02/01 22:14:43 successfully created profile HEAP
Fri Feb  1 22:14:43 UTC 2019: 2019/02/01 22:14:43 start uploading profile
Fri Feb  1 22:15:02 UTC 2019: 2019/02/01 22:15:02 successfully created profile CPU
Fri Feb  1 22:15:12 UTC 2019: 2019/02/01 22:15:12 start uploading profile
Fri Feb  1 22:15:13 UTC 2019: 2019/02/01 22:15:13 successfully created profile HEAP_ALLOC
Fri Feb  1 22:15:23 UTC 2019: 2019/02/01 22:15:23 start uploading profile
Fri Feb  1 22:15:24 UTC 2019: 2019/02/01 22:15:24 successfully created profile THREADS
Fri Feb  1 22:15:24 UTC 2019: 2019/02/01 22:15:24 start uploading profile
Fri Feb  1 22:15:25 UTC 2019: 2019/02/01 22:15:25 successfully created profile CONTENTION
Fri Feb  1 22:15:35 UTC 2019: 2019/02/01 22:15:35 start uploading profile
Fri Feb  1 22:15:36 UTC 2019: 2019/02/01 22:15:36 successfully created profile HEAP
Fri Feb  1 22:15:36 UTC 2019: 2019/02/01 22:15:36 start uploading profile
Fri Feb  1 22:15:36 UTC 2019: 2019/02/01 22:15:36 successfully created profile HEAP_ALLOC
Fri Feb  1 22:15:46 UTC 2019: 2019/02/01 22:15:46 start uploading profile
Fri Feb  1 22:15:47 UTC 2019: 2019/02/01 22:15:47 successfully created profile CPU
Fri Feb  1 22:15:57 UTC 2019: 2019/02/01 22:15:57 start uploading profile
Fri Feb  1 22:16:02 UTC 2019: 2019/02/01 22:16:02 successfully created profile HEAP
Fri Feb  1 22:16:02 UTC 2019: 2019/02/01 22:16:02 start uploading profile
Fri Feb  1 22:16:08 UTC 2019: 2019/02/01 22:16:08 successfully created profile THREADS
Fri Feb  1 22:16:08 UTC 2019: 2019/02/01 22:16:08 start uploading profile
Fri Feb  1 22:16:17 UTC 2019: 2019/02/01 22:16:17 busybench finished profiling.
Fri Feb  1 22:16:17 UTC 2019: ++ sleep 300
--- FAIL: TestAgentIntegration (0.01s)
	integration_test.go:154: using Git commit "756b0e0009e81a539e95b2821201b2bf1153a475" for the profiler integration test
    --- FAIL: TestAgentIntegration/profiler-test-go19-2019-02-01-14-12-00-522960-0800-gce (259.76s)
    	integration_test.go:261: failed to find function name busywork in profile
    --- PASS: TestAgentIntegration/profiler-test-go110-2019-02-01-14-12-00-522960-0800-gce (270.64s)
    --- PASS: TestAgentIntegration/profiler-test-go111-2019-02-01-14-12-00-522960-0800-gce (275.85s)
```

**Comment by jadekler** [comment] 2019-02-04 16:10
cc @aalexand

**Comment by aalexand** [comment] 2019-03-15 15:22
Dupe of #1366

**Closed by aalexand** 2019-03-15 15:22 UTC
Labels: profiler, type: cleanup
