### ISSUE TITLE
profiler: flake in TestAgentWithServer

### ISSUE THREAD

**Issue by tritone** [googleapis/google-cloud-go#1982] opened 2020-05-13 18:25 UTC
Noticed a flake in this test when running presubmits: https://sponge.corp.google.com/target?id=f38a0ab0-bb97-4089-ac0d-a2ffb5899040&target=cloud-devrel%2Fclient-libraries%2Fgo%2Fgoogle-cloud-go%2Fpresubmit%2Fgo114&searchFor=

```
=== RUN   TestAgentWithServer
    TestAgentWithServer: profiler_test.go:983: validateProfile(HEAP) got error: profile contains zero samples: PeriodType: space bytes
        Period: 524288
        Time: 2020-05-13 17:17:00.995605287 +0000 UTC
        Samples:
        alloc_objects/count alloc_space/bytes inuse_objects/count inuse_space/bytes
        Locations
        Mappings
        1: 0x400000/0x112a000/0x0 /tmp/go-build552119550/b678/profiler.test  [FN]
--- FAIL: TestAgentWithServer (22.23s)
...
FAIL
FAIL	cloud.google.com/go/profiler	24.714s
```

The change being tested was unrelated to profiler, and the failure only happened for one go version. Re-running Kokoro resolved the failure.

**Comment by jqll** [comment] 2020-05-14 22:56
Sounds like the test starts profiling before starting the bench code: https://github.com/googleapis/google-cloud-go/blob/master/profiler/profiler_test.go#L958, so it's possible to get an empty HEAP profile. I'll send a PR to change the order.

**Comment by jqll** [comment] 2020-05-15 02:59
I ran TestAgentWithServer 500 times and couldn't reproduce the issue. But I sent https://code-review.googlesource.com/c/gocloud/+/56490 to remove some potential reasons that may cause flakiness in the test.

**Comment by jqll** [comment] 2020-05-15 21:13
I'm closing this as I can't reproduce the failure and https://code-review.googlesource.com/c/gocloud/+/56490 removed all potential causes for flakiness that I can think of.

**Closed by jqll** 2020-05-15 21:13 UTC
Labels: api: cloudprofiler, priority: p1, type: bug
