### ISSUE TITLE
storage: fails to deploy, missing functions

### ISSUE THREAD

**Issue by TomislavHorvat1** [googleapis/google-cloud-go#4992] opened 2021-10-18 12:03 UTC
**Client**

Storage

**Environment**

Cloud Functions

**Go Environment**

go version go1.16.7 linux/amd64

GO111MODULE="on"
GOARCH="amd64"
GOBIN="/home/bla/go/bin"
GOCACHE="/home/bla/.cache/go-build"
GOENV="/home/bla/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/bla/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/bla/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/bla/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/bla/go/src/bitbucket.org/project/project/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2110900464=/tmp/go-build -gno-record-gcc-switches"

**Code**

No code, fails on deploy with command 

```
functions deploy "foo" --entry-point Event --runtime go116 --trigger-topic "bar" --env-vars-file .env.yaml
```

**Expected behavior**

Should successfully deploy

**Actual behavior**

Fails to deploy with errors

```
(gcloud.functions.deploy) OperationError: code=3, message=Build failed: # cloud.google.com/go/storage
/layers/google.go.functions-framework/gopath/pkg/mod/cloud.google.com/go/storage@v1.18.1/storage.go:1447:53: o.GetCustomerEncryption().GetKeySha256 undefined (type *"google.golang.org/genproto/googleapis/storage/v2".Object_CustomerEncryption has no field or method GetKeySha256)
/layers/google.go.functions-framework/gopath/pkg/mod/cloud.google.com/go/storage@v1.18.1/writer.go:439:10: q.GetCommittedSize undefined (type *"google.golang.org/genproto/googleapis/storage/v2".QueryWriteStatusResponse has no field or method GetCommittedSize); Error ID: 975560ac
```

**Comment by codyoss** [comment] 2021-10-18 12:53
Closing as dupe of #4991

**Closed by codyoss** 2021-10-18 12:53 UTC
Labels: triage me
