### ISSUE TITLE
compute/metadata: `OnGCE` should check for `Google` prefix instead of exact string

### ISSUE THREAD

**Issue by easwars** [googleapis/google-cloud-go#6037] opened 2022-05-16 18:05 UTC
Please see https://github.com/grpc/grpc-go/issues/5343 for context.

Based on this [comment](https://github.com/grpc/grpc-go/issues/5343#issuecomment-1124392163)
```
In order to help client libraries know the runtime they are running on, Google wanted Google Cloud Run,
Google App Engine and Google Cloud Functions to return more accurate product names at
`/sys/class/dmi/id/product_name`. This change is now on hold due to downstream impact on `grpc-go` and `gax-java`.

My suggestion would be for grpc-go to relax this check and instead of looking for a hardcoded
list of values, to only check that the product_name string starts with Google. After some time (months? years?),
Google Cloud runtimes might be able to switch (carefully) to more accurate product names.
```
`grpc-go` is making the necessary changes in https://github.com/grpc/grpc-go/pull/5348

The `OnGCE` function in `compute/metadata` package should also consider making the corresponding changes here:
https://github.com/googleapis/google-cloud-go/blob/f37584ff8947b18332b214a958ac57010cb6df5b/compute/metadata/metadata.go#L200

**Comment by codyoss** [comment] 2022-05-16 18:25
I left a comment on the original issue. We should not make this sort of change as a one off. This kind of change should be driven from an AIP. Until we have some official guidance I don't believe we should make changes. Closing as by design for now. If we update an AIP or have official guidance to follow, we will update this logic.

**Closed by codyoss** 2022-05-16 18:25 UTC
Labels: api: compute, triage me
