### ISSUE TITLE
Duplicated protobuf dependencies in go.mod in BigTable, potentially cause higher memory consumption

### ISSUE THREAD

**Issue by cc4i** [googleapis/google-cloud-go#8623] opened 2023-09-28 03:54 UTC
There're two duplicated references from protobuf, 

cloud.google.com/go/bigtable v1.19.0 -> github.com/golang/protobuf v1.5.3
cloud.google.com/go/bigtable v1.19.0 -> google.golang.org/protobuf v1.31.0

the first one - v1.5.3, which was deprecated version. Actually it's not just impact library for Bigtable but most most of golang lib due to all included genproto. 

Do we have plane to update accordingly and eliminate deprecated version and improve overall code smell?

**Comment by codyoss** [comment] 2023-09-28 14:17
This is a dupe of https://github.com/googleapis/google-cloud-go/issues/4273. 

Please comment back on the other issue, but what is your justification for "potentially cause higher memory consumption".

> Do we have plane to update accordingly and eliminate deprecated version and improve overall code smell?

There was a push to get this done at one time and a lot of the uses if not all direct uses in this repo were driven down, but it there still are some references as you point out.

**Closed by codyoss** 2023-09-28 14:17 UTC
Labels: triage me
