### ISSUE TITLE
pubsublite: service has stopped or is stopping

### ISSUE THREAD

**Issue by bzon** [googleapis/google-cloud-go#6706] opened 2022-09-20 19:05 UTC
**Client**

PubSub Lite

**Environment**

- GKE
- The service is running the same in a pod in the same zone of the pubsub lite topic.

**Go Environment**

- go version go1.19
- cloud.google.com/go/pubsublite v1.3.2

**Code**

e.g.
```go
	settings := pscompat.DefaultPublishSettings
	publisher, err := pscompat.NewPublisherClientWithSettings(ctx, "ps lite topic path", settings)
	if err != nil {
		return nil, err
	}

	result := publisher.Publish(ctx, &m)
	_, err := result.Get(ctx)
	if err != nil {
		fmt.Println(err) // pubsublite: service has stopped or is stopping
		return
	}
```

**Comment by tmdiep** [comment] 2022-09-29 01:57
Hi @bzon. Thanks for reaching out.

This error message means that the message was published after the publisher has already stopped due to a fatal error.

`result.Get` for an earlier message would have contained details of the fatal error. Alternatively, you can also call [`publisher.Error`](https://pkg.go.dev/cloud.google.com/go/pubsublite/pscompat#PublisherClient.Error) to get the details.

More details are documented here: https://pkg.go.dev/cloud.google.com/go/pubsublite/pscompat#PublisherClient.Publish

I will close this issue. If you still have questions/concerns after determining the root cause, feel free to reopen.

**Closed** 2022-09-29 01:58 UTC
Labels: triage me, api: pubsublite
