### ISSUE TITLE
bigtable/cmd/cbt: support createtable with families with complex GC rules

### ISSUE THREAD

**Issue by billyjacobson** [googleapis/google-cloud-go#1578] opened 2019-09-13 14:10 UTC
This command creates a table, but not with the correct families:

```
cbt createtable mobile-time-series families=stats_summary:maxage=10d||maxversions=1,stats_detail:maxage=10d||maxversions=1
```

I believe this has to do with the CSV parsing, since it stops at the '|' character, but I'm not sure why 

actual:
```
cbt ls mobile-time-series
Family Name		GC Policy
-----------		---------
stats_summary		age() > 10d
```

expected:
```
cbt ls mobile-time-series
Family Name		GC Policy
-----------		---------
stats_summary	age() > 10d || versions = 1
stats_detail		age() > 10d || versions = 1
```

**Comment by jadekler** [comment] 2019-09-13 19:33
cc @odeke-em Any idea where this hiccup might be?

**Comment by odeke-em** [comment] 2019-09-14 00:25
Hello there @billyjacobson, thank you for filing this issue! Thank you @jadekler for pinging me.

So I've examined the source code and it is just that versions isn't supported as per
https://github.com/googleapis/google-cloud-go/blob/21ffce36814cf45a82d18162f815a7500e9acaaa/bigtable/cmd/cbt/cbt.go#L542-L562

in which the only supported keys are:
"family" and "splits" so in deed this is a feature request. I wonder though why we don't support the other attributes!

I'll mail a CL implementing this as well as for other fields.

**Comment by odeke-em** [comment] 2019-09-14 00:25
Or at least we should have log.Fatal'd to signify that we don't support that attribute/field instead of silently failing.

**Comment by odeke-em** [comment] 2019-09-14 00:29
Actually hold up, the issue here is that the Family's fields aren't iterated upon, pardon my initial fast reply.

**Comment by odeke-em** [comment] 2019-09-14 01:49
Hello @billyjacobson I think the issue here might just be that your shell is literally interpreting `||` for example in your query your shell will try to invoke `maxversions=1,stats_detail:maxage=10d` if the command fails for example the equivalent of running
```shell
ls foo || echo "Failed to find echo" && maxversions=1,stats_detail:maxage=10d
```

I examined all the data being sent on the wire and you quote your arguments with "<ARGS>" i.e. make them `"families=stats_summary:maxage=10d||maxversions=1,stats_detail:maxage=10d||maxversions=1"`
```shell
cbt createtable mobile-time-series 
"families=stats_summary:maxage=10d||maxversions=1,stats_detail:maxage=10d||maxversions=1"
```

```diff
--- before.txt	2019-09-13 18:44:23.000000000 -0700
+++ after.txt	2019-09-13 18:44:34.000000000 -0700
@@ -1 +1 @@
-cbt createtable mobile-time-series families=stats_summary:maxage=10d||maxversions=1,stats_detail:maxage=10d||maxversions=1
+cbt createtable mobile-time-series "families=stats_summary:maxage=10d||maxversions=1,stats_detail:maxage=10d||maxversions=1"
```

The results sent on the wire then properly become
```json
{
  "column_families": {
    "stats_summary": {
      "gc_rule": {
        "Rule": {
          "Union": {
            "rules": [
              {
                "Rule": {
                  "MaxNumVersions": 2
                }
              },
              {
                "Rule": {
                  "MaxAge": {
                    "seconds": 950400
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}
```

and then on doing ls

```shell
$ cbt  ls mobile-time-series
2019/09/13 18:42:03 -project flag unset, will use gcloud active project
2019/09/13 18:42:03 gcloud active project is "odeke-sandbox"
Family Name		GC Policy
-----------		---------
stats_summary		(versions() > 2 || age() > 11d)
```

the proper results are presented. To use the other operators, please make sure that you quote other operators in order to use "&&", "and", "or" for example
```shell
$ cbt createtable mobile-time-series "families=stats_summary:maxversions=2 and maxage=11d"
```
which will then send
```shell
{
  "column_families": {
    "stats_summary": {
      "gc_rule": {
        "Rule": {
          "Intersection": {
            "rules": [
              {
                "Rule": {
                  "MaxNumVersions": 2
                }
              },
              {
                "Rule": {
                  "MaxAge": {
                    "seconds": 950400
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}
```

It would be great for use to provide a guide with examples and a big red warning about quoting the arguments that have shell operators && and || and basically every other operator.

I am going to close this as working as intended.

**Closed by odeke-em** 2019-09-14 01:49 UTC
Labels: api: bigtable, type: feature request

**Comment by billyjacobson** [comment] 2019-09-16 14:55
Thank you! I'm adding examples to the docs now
