### ISSUE TITLE
storage: query.SetAttrSelection hide prefixes if a Delimiter is specified

### ISSUE THREAD

**Issue by drakkan** [googleapis/google-cloud-go#1763] opened 2020-01-30 14:26 UTC
**Client**

storage

**Environment**

Linux

**Code**

```go
package main

import (
	"context"
	"fmt"

	"cloud.google.com/go/storage"
	"google.golang.org/api/iterator"
)

const (
	bucketName = "set your bucket name here"
)

var (
	gcsFieldsSelection = []string{"Bucket", "Name", "ContentType", "ContentLanguage", "CacheControl", "EventBasedHold",
		"TemporaryHold", "RetentionExpirationTime", "ACL", "Owner", "ContentEncoding", "ContentDisposition", "Size", "MD5",
		"CRC32C", "MediaLink", "Metadata", "Generation", "Metageneration", "StorageClass", "CustomerKeySHA256", "KMSKeyName",
		"Created", "Deleted", "Updated", "Etag"}
)

func main() {
	ctx := context.Background()
	svc, err := storage.NewClient(ctx)
	if err != nil {
		fmt.Printf("error creating storage client: %v\n", err)
	}
	query := &storage.Query{Prefix: "", Delimiter: "/"}
	bkt := svc.Bucket(bucketName)
	it := bkt.Objects(ctx, query)
	for {
		attrs, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			fmt.Printf("error listing bucket contents with no attribute selection: %v\n", err)
			break
		}
		if len(attrs.Prefix) > 0 {
			fmt.Printf("attr prefix no attr selection: %v\n", attrs.Prefix)
		} else {
			fmt.Printf("attr name no attr selection: %v\n", attrs.Name)
		}
	}
	fmt.Println()
	fmt.Printf("now the same query with attr selection, the same results are expected\n")
	fmt.Println()
	query = &storage.Query{Prefix: "", Delimiter: "/"}
	err = query.SetAttrSelection(gcsFieldsSelection)
	if err != nil {
		fmt.Printf("error setting attribute selection: %v\n", err)
		return
	}
	it = bkt.Objects(ctx, query)
	for {
		attrs, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			fmt.Printf("error listing bucket contents with attribute selection: %v\n", err)
			break
		}
		if len(attrs.Prefix) > 0 {
			fmt.Printf("attrs prefix with attr selection: %v\n", attrs.Prefix)
		} else {
			fmt.Printf("attrs name with attr selection: %v\n", attrs.Name)
		}
	}
}
```

**Expected behavior**

`bkt.Objects` should return the same number or results with and without `SetAttrSelection`

**Actual behavior**

when setting `SetAttrSelection` the "folders" are not listed, here is the output of the provided test code for my bucket

```
attr name no attr selection: ros.txt
attr name no attr selection: sftpgo.log
attr prefix no attr selection: testdir/
attr prefix no attr selection: vdir/

now the same query with attr selection, the same results are expected

attrs name with attr selection: ros.txt
attrs name with attr selection: sftpgo.log
```

so the folders `testdir/` and `vdir/` are returned only without `SetAttrSelection`

**Comment by IlyaFaer** [comment] 2020-02-17 10:52
I've taken a look through several doc pages, and here is how I'm seeing the situation:

1. [There is no true folders](https://cloud.google.com/storage/docs/cloud-console#_creatingfolders) in Storage. Which means you don't have `testdir` and `vdir` instances, you just have objects with such a prefixes in their names.

2. When calling `list` method with `/` delimiter we're listing objects *just within specified "folder"*. And as [list method docs](https://cloud.google.com/storage/docs/json_api/v1/objects/list) says, it'll return objects and something called *prefixes*. *Prefixes* seems to be some kind of a fictive instances to show "folders" within "folder" we're listing.

3. If we'll print entire objects from your result, we'll see that *prefixes* are not actually objects - they only include prefix and `nil` in all other fields:

![image](https://user-images.githubusercontent.com/26030071/74645603-4cdad280-5189-11ea-9032-d183f122c86d.png)

4. So, my guess: when you're trying to read concrete object fields, you're not getting "folders" as they are not real objects, just a fictive instances, which doesn't have these fields. With 1st item of these comment, they shouldn't be read, 'cause real objects (which causes these *prefixes* to appear in our result) are located one level below, while you're requesting only objects within *this* "folder" - not the whole tree.

Thus, I don't think there is an error in the API, it's just a matter of low-level understanding of `list` method behavior and data model.

**Comment by drakkan** [comment] 2020-02-17 11:47
Hi thanks for your answer please read inline some comments

> I've taken a look through several doc pages, and here is how I'm seeing the situation:
> 
> 1. [There is no true folders](https://cloud.google.com/storage/docs/cloud-console#_creatingfolders) in Storage. Which means you don't have `testdir` and `vdir` instances, you just have objects with such a prefixes in their names.

correct

> 2. When calling `list` method with `/` delimiter we're listing objects _just within the specified "folder"_. And as [list method docs](https://cloud.google.com/storage/docs/json_api/v1/objects/list) says, it'll return objects and something called _prefixes_. _Prefixes_ seems to be some kind of a fictive instances to show "folders" within "folder" we're listing.

based on this docs:

https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L1126

`Delimiter` returns results in a directory-like fashion adding "folders"

and I use `Prefix` as the prefix filter to query objects

https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L1135

in the example above prefix is empty so I'm asking all the objects in the bucket in a directory-like fashion

> 3. If we'll print entire objects, we'll see that _prefixes_ are not actually objects - they only include `Prefix`, and `nil` in all other fields:
> 
> ![image](https://user-images.githubusercontent.com/26030071/74645603-4cdad280-5189-11ea-9032-d183f122c86d.png)
> 
> 1. So, my guess: when you're trying to read concrete object fields, you're not getting "folders" as they are not real objects, just a fictive JIT-instances, which doesn't have these fields/values. With 1st item of these comment, they shouldn't be read, 'cause real objects (which causes these _prefixes_ to appear in our result) are located one level below, while you're requesting only objects within _this_ "folder" - not the whole tree.

I only tested the go client library so I don't know if other client libraries work the same way, anyway if this is the intended behaviour you should at least document that `Delimiter` will not list "folders" if a filed selection is applyed, this means that if you want the results in a directory-like fashion you cannot have any performance optimization

**Comment by IlyaFaer** [comment] 2020-02-17 12:28
@drakkan, didn't you tried to add "Prefix" field into your `gcsFieldsSelection` var? I think, it's working

**Comment by IlyaFaer** [comment] 2020-02-17 13:19
> I only tested the go client library so I don't know if other client libraries work the same way

`list` method returns prefixes (list of strings) in a separate field, so it's gonna be actual for all clients. 

I believe, it's the right behavior: how can we read the name of the object, which doesn't actually exist? Still, I agree, it would be good to mention this in docs.

@frankyn, WDYT?

**Comment by odeke-em** [comment] 2020-04-14 18:28
Thank you @drakkan for filing this bug and @IlyaFaer for the diagnoses.

For posterity and to reproduce the reported behavior without cloud.google.com/go/storage i.e. using the underlying generated Go library `google.golang.org/api/storage/v1` library directly which will hopefully match all other libraries:
```go
package main

import (
	"context"
	"fmt"

	"golang.org/x/oauth2/google"

	"google.golang.org/api/googleapi"
	"google.golang.org/api/storage/v1"
)

func main() {
	ctx := context.Background()
	client, err := google.DefaultClient(ctx, storage.DevstorageReadOnlyScope)
	if err != nil {
		panic(err)
	}
	svc, err := storage.New(client)
	if err != nil {
		panic(err)
	}

	objsSvc := svc.Objects
	ol := objsSvc.List("YOUR_BUCKET_HERE)
	ol = ol.Prefix("").Delimiter("/")
	if false {
		ol = ol.Fields("nextPageToken", googleapi.Field("items(updated,name,bucket)"))
	}
	ol = ol.PageToken("").Context(nil).IfNoneMatch("").Projection("full").Versions(false)
	ol.Header().Set("X-Goog-Api-Client", "gl-go/6f3a9515b6 gccl/20200409")
	fmt.Printf("Req: %#v\n", ol)
	objs, err := ol.Do()
	if err != nil {
		panic(err)
	}

        fmt.Println("From .Items:")
	for _, item := range objs.Items {
		fmt.Printf("\t%s\n", item.Name)
	}
        fmt.Println("\nFrom .Prefixes:")
	for _, prefix := range objs.Prefixes {
		fmt.Printf("\t%s\n", prefix)
	}
}
```

## Without Fields  aka `if false`
```shell
From .Items:
	ros.txt
	sftpgo.log

From .Prefixes:
	testdir/
	vdir/
```

## With Fields aka `if true`
```shell
From .Items:
	ros.txt
	sftpgo.log

From .Prefixes:
```

@frankyn could you please provide a GCS advisory here and whether we should document this?
Thank you

**Comment by diggerk** [comment] 2020-05-21 06:15
@odeke-em, I am hitting the same problem with the go client. I saw your code that uses the API client and checked how similar functionality works in the Java client. Your code needs to be fixed in the following way to get prefixes when the fields parameter is set.

This is your code:
`ol = ol.Fields("nextPageToken", googleapi.Field("items(updated,name,bucket)"))`

This is the one that will work:
`ol = ol.Fields("nextPageToken", googleapi.Field("prefixes,items(updated,name,bucket)"))`

**Comment by diggerk** [comment] 2020-05-22 05:42
Hi @odeke-em , I submitted a fix for review at https://code-review.googlesource.com/c/gocloud/+/56712

**Comment by tritone** [comment] 2020-05-22 05:58
Hi @diggerk , thanks for your PR! I will take a look.

**Comment by tritone** [comment] 2020-07-29 22:00
Hi @diggerk , apologies for letting your PR fall off the radar. I discussed offline with @frankyn and we think your fix makes sense. Since we have moved to github, I re-opened it as #2661 . Let me know if you have further thoughts.

**Comment by diggerk** [comment] 2020-07-29 22:10
Hi @tritone , thanks a lot for following through with this!

**Closed** 2020-09-10 17:41 UTC
Labels: :rotating_light:, api: storage, priority: p2, type: bug

**Comment by tritone** [comment] 2020-09-10 18:23
Merged now and will go out in the next release.
