### ISSUE TITLE
spanner: Retry transaction if error is "Transaction outcome unknown."

### ISSUE THREAD

**Issue by limenote135** [googleapis/google-cloud-go#3883] opened 2021-04-02 06:19 UTC
**Client**

Spanner

**Environment**

debian docker on GKE

**Go Environment**

$ go version
```
go version go1.15.2 linux/amd64
```
<details>
<summary>$ go env</summary>
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/go/src/npln.nintendo.net/npln-practice/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build329281553=/tmp/go-build -gno-record-gcc-switches"
</details>

**Expected behavior**

Retry transaction

**Actual behavior**

Return `spanner: code = "Unknown", desc = "rpc error: code = Unknown desc = Transaction outcome unknown.` error.
This error is treated as retryable error in nodejs-spanner.
https://github.com/googleapis/nodejs-spanner/blob/master/src/transaction-runner.ts#L32
https://github.com/googleapis/nodejs-spanner/issues/202

**Comment by hengfengli** [comment] 2021-04-12 04:48
I don't think we should retry transaction outcome unknown error, right? This is not idempotent. If the transaction is ongoing and will be executed successfully, then retrying will lead to a duplicated effect. 

@olavloite Am I correct?

**Comment by limenote135** [comment] 2021-04-12 05:12
What is the cause of this error? How should I handle it?

**Comment by hengfengli** [comment] 2021-04-12 05:24
Hi @limenote135, if you look at the error handling section in v1.3.0 `https://github.com/googleapis/google-cloud-go/blob/b32bda9b6ad3017d031b80e1dbfcc0aa273af456/spanner/CHANGES.md#v130`, "Return TransactionOutcomeUnknownError if a DEADLINE_EXCEEDED or CANCELED error occurs while a COMMIT request is in flight."

Currently, I think you have to retry it on your end. Is it a very large transaction? I wonder why it takes so long to commit.

**Comment by olavloite** [comment] 2021-04-12 06:16
> I don't think we should retry transaction outcome unknown error, right? This is not idempotent. If the transaction is ongoing and will be executed successfully, then retrying will lead to a duplicated effect.
> 
> @olavloite Am I correct?

Correct, we should not be retrying a `Transaction outcome unknown` error automatically. As the error message indicates, the client does not know whether the transaction succeeded or not, and retrying it could have unwanted side effects.


@limenote135 
> What is the cause of this error? How should I handle it?

This error is returned if a `Cancelled` or `DeadlineExceeded` error occurs during the `Commit` of a transaction. The client does not know whether the `Commit` was cancelled / timed out before or after the commit was actually processed by the backend, and therefore does not know whether the transaction succeeded or not. Consider the following two examples:

Example 1:
1. The transaction is executed and a `Commit` request is sent by the client to the server.
2. There is a network hickup and the `Commit` request never reaches the backend.
3. While waiting for a response from the backend, the context deadline is exceeded and the `Unknown` error is returned.

Example 2:
1. The transaction is executed and a `Commit` request is sent by the client to the server.
2. The backend is busy and needs a little longer than normal to execute the commit request.
3. While waiting for a response from the backend, the context deadline is exceeded and the `Unknown` error is returned.

Retrying such an error automatically could therefore cause unwanted side effects, as the client does not know which of the above scenarios happened. Specifically, it could cause a transaction to be executed and committed twice. If such a transaction contained a statement like `UPDATE BankAccount SET Amount = Amount + 10 WHERE AccountHolder = 1`, then it is clearly something that you don't want to be executed twice.

This error should normally be handled by looking into the context deadline that you are using. Are you using a context with a relatively short deadline? Or is it being cancelled by something else in your code? If so, you should consider increasing the deadline and/or removing the part of the code that might cancel it while the transaction is still running. If that is not possible or desirable, for example because it is part of a time critical path of your application, you should probably look into adding some specific error handling to your application for these specific errors.
As mentioned above, the error indicates that the client does not know whether the transaction succeeded or not. The reason for that is that it does not keep track of which statements were executed during the transaction, and therefore cannot do any checks to see if the transaction was actually committed or not. Your application might know that, and could check whether any of the statements in the transaction succeeded. If the check determines that the transaction did succeed, you can return safely. If the check determines that it did not succeed, you should retry the transaction.

**Comment by limenote135** [comment] 2021-04-12 06:18
@hengfengli Thank you for the information.

I saw 2 cases of transaction outcome unknown error.
- `spanner: code = "Canceled", desc = "context canceled, transaction outcome unknown"`
- `spanner: code = "Unknown", desc = "rpc error: code = Unknown desc = Transaction outcome unknown."`

According to the following codes, if this is caused by a DeadlineExceeded or a Canceled, description to be `%s, %s` format, so I think the former is Canceled but the latter is actually an unknown error.
https://github.com/googleapis/google-cloud-go/blob/master/spanner/errors.go#L143-L152

**Comment by hengfengli** [comment] 2021-04-12 06:25
Yes, I also just realized that the error you got is not `TransactionOutcomeUnknownError` in which the desc is `transaction outcome unknown` https://github.com/googleapis/google-cloud-go/blob/1063c601a4c4a99217b45be0b25caa460e7157a1/spanner/errors.go#L58. 

The unknown error you got is `... Transaction outcome unknown`. The first letter is capitalized. I think this might be an unknown error from the backend. AFAIK, we don't retry unknown errors in go client lib. Then, you have to retry it on your end if this happens and you make sure the transaction has not been executed.

**Comment by limenote135** [comment] 2021-04-12 07:14
I understand why the client cannot retry automatically. However, I think it is inefficient that all users have to check and retry manually even if the transaction is idempotent.
Could you consider adding an option to retry automatically in go client?

**Comment by olavloite** [comment] 2021-04-13 07:09
> Could you consider adding an option to retry automatically in go client?

I'm not sure that is an option that we would want to support, as most transactions cannot be applied multiple times without possible side effects. So I don't think it is unreasonable to ask users to add their own check before retrying in such a case, as in by far the most cases an additional check would be needed to guarantee that the transaction can actually be executed once more.
I understand that it would be an option that users would have to turn on to get an automatic retry, but I worry that it would be something that is not always well understood, and might lead to someone turning it on without completely realizing what it means, especially as it might be confused with the automatic retries that we already do for aborted transactions. It is always safe to retry an aborted transaction, but it is not always safe to retry a transaction after this `Unknown` error.

The only exception to the above might be the `Apply` function in combination with the `ApplyAtLeastOnce` option. That function is specifically intended for [idem-potent write-only transactions](https://github.com/googleapis/google-cloud-go/blob/531fdd540203c7346d8a58f505a1291052f8d1c6/spanner/client.go#L510). Allowing an additional option for automatically retrying there could make sense (or even make it the default to retry in that specific case). The option also clearly states that there is a chance that the method fails with an unexpected `ALREADY_EXISTS` error if it is applied more than once.

**Comment by limenote135** [comment] 2021-04-17 11:18
The root problem is the Spanner returns the unknown error, so it should be done either fix the Spanner, or document and make it known that the Spanner randomly returns this error and the user has to handle it, right?

**Comment by olavloite** [comment] 2021-04-18 18:44
@limenote135 

> The root problem is the Spanner returns the unknown error, so it should be done either fix the Spanner, or document and make it known that the Spanner randomly returns this error and the user has to handle it, right?

Yes, I think you are right about that, __but__: I didn't realize when I wrote my initial comment that it was an error that was coming from the backend. I wrongly assumed that it was the error that is generated by the client when a `Commit` request times out or is cancelled. If this is something that is randomly returned by the backend, then I would like to investigate a little more. Do you have any additional information on:
1. How often do you receive this error? Is it like 1 in 100 transactions, or a lot more / less?
2. Does it seem to be truly random? Or can you reproduce it by following certain specific steps?
3. What are the settings that you are using for your client (or are you using the default settings)?

Any other additional information you have that might be relevant would also be highly appreciated.

**Comment by hengfengli** [comment] 2021-09-14 07:55
I will close this issue as no more info is provided. Welcome to reopen it with adding more info.

**Closed by hengfengli** 2021-09-14 07:55 UTC
Labels: type: feature request, priority: p2, api: spanner
