### ISSUE TITLE
storage: 0-conditions on object generation should work

### ISSUE THREAD

**Issue by bsidhom** [googleapis/google-cloud-go#1288] opened 2019-01-29 00:54 UTC
## Client

Storage

## Describe Your Environment

All

## Expected Behavior

The GCS object copy destination should support a value of 0 for expected generation. As per the [Storage API doc](https://cloud.google.com/storage/docs/json_api/v1/objects/copy#request_parameters), `ifGenerationMatch == 0` implies that operations should succeed _only if_ no live versions of the destination object exist.

The following code sample should fail on the second object copy (assuming that `tmp/foo` and `tmp/bar` already exist:

```go
package main

import (
	"context"
	"fmt"

	"cloud.google.com/go/storage"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	client, err := storage.NewClient(ctx)
	if err != nil {
		panic(err)
	}

	bucket := client.Bucket("my-bucket")
	foo := bucket.Object("tmp/foo")
	bar := bucket.Object("tmp/bar")
	result := bucket.Object("tmp/result")

	// First, copy foo.
	attrs, err := result.Generation(0).CopierFrom(foo).Run(ctx)
	if err != nil {
		panic(err)
	}
	fmt.Printf("attrs (foo -> result): %#v\n", attrs)

	// Then copy bar.
	attrs, err = result.Generation(0).CopierFrom(bar).Run(ctx)
	if err != nil {
		panic(err)
	}
	fmt.Printf("attrs (bar -> result): %#v\n", attrs)
}
```

## Actual Behavior

Running the sample results in `panic: storage: Copy destination: generation not supported`.

The git comment associated with the commit where this was introduced implies that this is working as intended: https://github.com/googleapis/google-cloud-go/commit/3837a85c63395efd4cc8ef7d20cf9ea8f18d9bd9. However, as is, there is no way to atomically enforce that the destination object does not already exist. If you remove the `.Generation(0)` bits from the object handles above, _both_ copy operations succeed. This means that the empty set of conditions is not semantically equal to `ifGenerationMatch == 0`.

**Comment by jadekler** [comment] 2019-01-29 17:36
@frankyn Could you speak to this?

**Comment by frankyn** [comment] 2019-02-01 00:15
Hi @bsidhom,

The code you provided is using [Generation()](https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L335-L344), which sets the Generation on an instance of an object. However, the way it's read is `copy tmp/foo to tmp/result of generation 0` which the API does not support and the library is trying to help by failing with: [`panic: storage: Copy destination: generation not supported`](https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L951).

You're trying to use a precondition of `IfGenerationMatch=0`, to do this you'll need to use `object.If({DoesNotExist: true}).CopierFrom(bar).Run(ctx)` instead per [Go GCS library documentation](https://github.com/googleapis/google-cloud-go/blob/master/storage/storage.go#L885-L889). An example is shown below. 

```go
package main

import (
	"context"
	"fmt"

	"cloud.google.com/go/storage"
)

func main() {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	client, err := storage.NewClient(ctx)
	if err != nil {
		panic(err)
	}

	bucket := client.Bucket("my-bucket")
	foo := bucket.Object("tmp/foo")
	bar := bucket.Object("tmp/bar")
	result := bucket.Object("tmp/result")

	// First, copy foo.
	attrs, err := result.If(storage.Conditions{DoesNotExist: true}).CopierFrom(foo).Run(ctx)
	if err != nil {
		panic(err)
	}
	fmt.Printf("attrs (foo -> result): %#v\n", attrs)

	// Then copy bar, this will now fail because result exists.
	attrs, err = result.If(storage.Conditions{DoesNotExist: true}).CopierFrom(bar).Run(ctx)
	if err != nil {
		panic(err)
	}
	fmt.Printf("attrs (bar -> result): %#v\n", attrs)
}
```

**Comment by odeke-em** [comment] 2019-08-15 21:53
Thank you for the response @frankyn! @bsidhom please take a look at @frankyn's response on using `Object.If(Conditions{DoesNotExist: true})`

In the Go doc we actually document this recommendation as per https://godoc.org/cloud.google.com/go/storage#Conditions.GenerationMatch
<img width="894" alt="Screen Shot 2019-08-15 at 3 30 50 PM" src="https://user-images.githubusercontent.com/4898263/63128259-ba573d80-bf71-11e9-9d34-8f53cb471b0c.png">

I shall close this issue as working as intended and answered, but please don't hesitate @bsidhom to report any bugs or ask questions and thank you for using these packages!

**Closed by odeke-em** 2019-08-15 21:53 UTC
Labels: api: storage, type: feature request
