### ISSUE TITLE
CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [googleapis/google-cloud-go#7364] opened 2023-02-05 08:06 UTC
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

We are maintaining an [GCP plugin](https://www.cloudquery.io/docs/plugins/sources/gcp/overview), which is widely used and users use it to sync their APIs to a database/datalake and create asset inventory, operational data lake and other use-cases.

As we have limited capacity to maintain all plugins, we are usually looking for the official vendor to help maintain it (similar to terraform provider).

I was curious if this would be an interesting collaboration, where we can help with the initial version (already implemented) and you will help maintain it?

This will give your users the ability to sync/ELT GCP APIs to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by codyoss** [comment] 2023-02-06 15:12
This looks like a dupe of https://github.com/googleapis/google-api-go-client/issues/1824. Closing as response is the same.

**Closed by codyoss** 2023-02-06 15:12 UTC

**Comment by yevgenypats** [comment] 2023-02-06 16:39
Hey @codyoss Thanks for the response and yes this is a duplicate wasn't sure where to ask. `google-cloud-go` is not in maintains mode, so is the answer is still the same? or who should I reach out to ask for a potential collaboration?

**Comment by codyoss** [comment] 2023-02-06 16:52
You are right this project is active. But I think the answer is still the same do to bandwidth. If you have Google cloud support contract that may be the a channel to bring this sort of thing up with. Other than that I am not sure of a Google channel unless you already have professional ties and are doing business currently. Sorry I can't be of more assistance.

**Comment by yevgenypats** [comment] 2023-02-06 17:02
> You are right this project is active. But I think the answer is still the same do to bandwidth. If you have Google cloud support contract that may be the a channel to bring this sort of thing up with. Other than that I am not sure of a Google channel unless you already have professional ties and are doing business currently. Sorry I can't be of more assistance.

Got it. That's totally fine and I'll try via support / another channel. Thanks again for the reply!
