### ISSUE TITLE
storage: client targets wrong path on server when retrieving bucket object(s) from emulator

### ISSUE THREAD

**Issue by alexgille** [googleapis/google-cloud-go#6139] opened 2022-06-08 14:50 UTC
**Client**

Storage : https://pkg.go.dev/cloud.google.com/go/storage

**Environment**

- macOS Monterey 12.4
- Dockerized GCS emulator : https://github.com/fsouza/fake-gcs-server

**Go Environment**

$ go version

`go version go1.17.2 darwin/amd64`

$ go env

```env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/<stripped>/Library/Caches/go-build"
GOENV="/<stripped>/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/<stripped>/godir/pkg/mod"
GONOPROXY="github.com/<stripped>"
GONOSUMDB="github.com/<stripped>"
GOOS="darwin"
GOPATH="/<stripped>/godir"
GOPRIVATE="github.com/<stripped>"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.2/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/<stripped>/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/fm/57mktm3x6252ls4gdt3863f80000gp/T/go-build808135654=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Code**

**test.go**

```go
package main

import (
	"context"
	"fmt"
	"io/ioutil"
	"os"

	"cloud.google.com/go/storage"
	"google.golang.org/api/option"
)

func main() {
	os.Setenv("STORAGE_EMULATOR_HOST", "localhost:4443")

	fmt.Println("Creating client")
	cl, err := storage.NewClient(context.Background(), option.WithCredentialsFile(""), option.WithEndpoint("http://localhost:4443/storage/v1/"))
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	// create bucket
	fmt.Println("Creating bucket")
	bk := cl.Bucket("test-bucket")
	if err := bk.Create(context.Background(), "projectID", nil); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	// create object
	fmt.Println("Creating object")
	ow := bk.Object("my-object").NewWriter(context.Background())
	if _, err := ow.Write([]byte("abc")); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	// write to remote object
	fmt.Println("Writing object data")
	if err := ow.Close(); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	// read object attrs
	fmt.Println("Reading object attributes")
	attrs, err := bk.Object("my-object").Attrs(context.Background())
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	fmt.Println(" - name: " + attrs.Name)

	// retrieve object
	fmt.Println("Retrieving object")
	or, err := bk.Object("my-object").NewReader(context.Background())
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	// read from remote object
	fmt.Println("Reading object data")
	buff, err := ioutil.ReadAll(or)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	fmt.Println("Read: " + string(buff))
	os.Exit(0)
}
```

**Execute**

```bash
docker run -d --name fake-gcs-server -p 4443:4443/tcp fsouza/fake-gcs-server -backend memory -scheme http
go test.go
```

**Expected behavior**

The created object is retrieved, its content is readable and this program does not fail.

**Actual behavior**

The above code returns an error saying that the object does not exist. Output :

```
Creating client
Creating bucket
Creating object
Writing object data
Reading object attributes
 - name: my-object
Retrieving object
storage: object doesn't exist
exit status 1
```

According to the following logs of the GCS emulator, and according to the "[Objects: get](https://cloud.google.com/storage/docs/json_api/v1/objects/get)" documentation, the client is targeting the wrong path :

```
time="2022-06-08T14:26:15Z" level=info msg="server started at http://[::]:4443"

time="2022-06-08T14:33:50Z" level=info msg="172.17.0.1 - - [08/Jun/2022:14:33:50 +0000] \"POST /storage/v1/b?alt=json&prettyPrint=false&project=projectID HTTP/1.1\" 200 151"

time="2022-06-08T14:33:50Z" level=info msg="172.17.0.1 - - [08/Jun/2022:14:33:50 +0000] \"POST /upload/storage/v1/b/test-bucket/o?alt=json&name=my-object&prettyPrint=false&projection=full&uploadType=multipart HTTP/1.1\" 200 463"

time="2022-06-08T14:33:50Z" level=info msg="172.17.0.1 - - [08/Jun/2022:14:33:50 +0000] \"GET /test-bucket/my-object HTTP/1.1\" 404 10"
```

It uses paths with the syntax `http://<domain>/<bucket>/<object>` while it should be `http://<domain>/storage/v1/b/<bucket>/o/<object>` as per the [documentation](https://cloud.google.com/storage/docs/json_api/v1/objects/get).

However, if I manually target the **right path**, it works fine :

**cURL call**

```bash
curl -i http://localhost:4443/storage/v1/b/test-bucket/o/my-object
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Type: application/json
Date: Wed, 08 Jun 2022 14:36:41 GMT
Content-Length: 508

{"kind":"storage#object","name":"my-object","id":"test-bucket/my-object","bucket":"test-bucket","size":"3","contentType":"text/plain; charset=utf-8","crc32c":"Nks/tw==","acl":[{"bucket":"test-bucket","entity":"projectOwner","object":"my-object","projectTeam":{},"role":"OWNER"}],"md5Hash":"kAFQmDzST7DWlj99KOF/cg==","etag":"\"kAFQmDzST7DWlj99KOF/cg==\"","timeCreated":"2022-06-08T14:33:50.054347Z","timeDeleted":"0001-01-01T00:00:00Z","updated":"2022-06-08T14:33:50.054351Z","generation":"1654698830054352"}
```

**Emulator logs**

```
time="2022-06-08T14:36:41Z" level=info msg="172.17.0.1 - - [08/Jun/2022:14:36:41 +0000] \"GET /storage/v1/b/test-bucket/o/my-object HTTP/1.1\" 200 508"
```

**Additional context**

Occurs currently on `cloud.google.com/go/storage v1.22.1`

**Comment by alexgille** [comment] 2022-06-08 16:49
Note : after upgrading to `cloud.google.com/go/storage` from `v1.10.0` to `v1.22.1`, the error does not occur anymore at the "read object attribute" step, but still occurs when creating a reader from the object, so the issue might be on the reader or on how the reader is created.
I updated my example accordingly.

**Comment by tritone** [comment] 2022-06-13 17:21
I think the reason for the issue is that this library uses the GCS XML API for the Reader (while using the JSON API for all other operations). So, the endpoint and path will follow XML API conventions. See https://cloud.google.com/storage/docs/xml-api/get-object-download

Does your emulator support the XML API for GCS?

**Comment by alexgille** [comment] 2022-06-15 07:50
Hello,
The emulator I use does not support XML API unfortunately. In any case, this looks like a discrepancy and a lack of consistency to have not the same -set of- endpoints targeted at all steps of this linear flow.
Also this is not configurable from the caller, so users of this Go API cannot control what is done under the hood, neither for testing nor for production.
In what way would it make sense that only the Reader targets the XML API while all other steps target the JSON API?

**Comment by tritone** [comment] 2022-06-27 21:27
@alexgille apologies for the belated response. The reason for using the GCS XML API for downloads is that it was more performant than the JSON API for downloads at the time this library was initially implemented. In the years since then, this gap has been (mostly?) closed, but there hasn't been a strong reason to swap back to JSON-- and doing so by default might change behavior for some users who are sending XML-specific headers.

However, we have it on our roadmap to add JSON API downloads, and will hopefully implement that later this year as a non-default option for Reader.

Could you confirm whether the emulator workaround from @lirao would work for you in the mean time?

**Comment by tritone** [comment] 2022-06-27 21:39
Reading into the issues in the emulator repo more deeply, it does look like [fsouza/fake-gcs-server](https://github.com/fsouza/fake-gcs-server) supports both the XML and JSON APIs for GCS and even has examples that use this Go client to download files via the XML API. So I think this is not an issue with the client using XML. I'm going to close the issue; @alexgille feel free to re-open if you are still running into problems. And thanks @lirao for your helpful comment!

**Closed by tritone** 2022-06-27 21:39 UTC
Labels: type: question, api: storage, needs more info
